(function(g){var window=this;var MZ=function(a){a.i||(a.i=new g.Qo,g.H(a,a.i));return a.i},NZ=function(a,b,c){var d=g.V(a.app);
b.event="iv";a.isFullscreen()&&(b.fs=1);b.ux=1;d.logEvent(b,c)},OZ=function(a){a.N("cardstatechange",a.yd()&&a.De()?1:0)},PZ=function(a){var b=g.Oh(a);
a=g.Vh(a);return new g.qh(b.x,b.y,a.width,a.height)},QZ=function(a,b){var c=a.style;
"opacity"in c?c.opacity=b:"MozOpacity"in c?c.MozOpacity=b:"filter"in c&&(c.filter=""===b?"":"alpha(opacity="+100*Number(b)+")")},RZ=function(a){return"none"!=a.style.display},SZ=function(a,b){if(/^\d+px?$/.test(b))return parseInt(b,10);
var c=a.style.left,d=a.runtimeStyle.left;a.runtimeStyle.left=a.currentStyle.left;a.style.left=b;var e=a.style.pixelLeft;a.style.left=c;a.runtimeStyle.left=d;return+e},Lna=function(a){var b=g.Ih(a,"fontSize");
var c=(c=b.match(Ina))&&c[0]||null;if(b&&"px"==c)return parseInt(b,10);if(g.Nd){if(String(c)in Jna)return SZ(a,b);if(a.parentNode&&1==a.parentNode.nodeType&&String(c)in Kna)return a=a.parentNode,c=g.Ih(a,"fontSize"),SZ(a,b==c?"1em":b)}c=g.Sd("SPAN",{style:"visibility:hidden;position:absolute;line-height:0;padding:0;margin:0;border:0;height:1em;"});a.appendChild(c);b=c.offsetHeight;g.Yd(c);return b},Mna=function(a){if(/-[a-z]/.test("pollChoiceIndex"))return null;
if(g.Ok&&a.dataset){if(g.kc()&&!("pollChoiceIndex"in a.dataset))return null;a=a.dataset.pollChoiceIndex;return void 0===a?null:a}return a.getAttribute("data-"+g.id("pollChoiceIndex"))},VZ=function(a){a=g.Qa(a);
delete TZ[a];g.Yb(TZ)&&UZ&&UZ.stop()},WZ=function(){UZ||(UZ=new g.M(function(){Nna()},20));
var a=UZ;a.isActive()||a.start()},Nna=function(){var a=(0,g.B)();
g.Lb(TZ,function(b){XZ(b,a)});
g.Yb(TZ)||WZ()},YZ=function(a,b){g.uf.call(this,a);
this.coords=b.coords;this.x=b.coords[0];this.y=b.coords[1];this.z=b.coords[2];this.duration=b.duration;this.progress=b.progress;this.fps=b.D;this.state=b.g},ZZ=function(a,b,c,d){g.lo.call(this);
if(!g.La(a)||!g.La(b))throw Error("Start and end parameters must be arrays");if(a.length!=b.length)throw Error("Start and end points must be the same length");this.i=a;this.F=b;this.duration=c;this.C=d;this.coords=[];this.progress=this.D=0;this.A=null},XZ=function(a,b){b<a.startTime&&(a.endTime=b+a.endTime-a.startTime,a.startTime=b);
a.progress=(b-a.startTime)/(a.endTime-a.startTime);1<a.progress&&(a.progress=1);a.D=1E3/(b-a.A);a.A=b;$Z(a,a.progress);1==a.progress?(a.g=0,VZ(a),a.Yc(),a.l()):1==a.g&&a.yr()},$Z=function(a,b){g.Na(a.C)&&(b=a.C(b));
a.coords=Array(a.i.length);for(var c=0;c<a.i.length;c++)a.coords[c]=(a.F[c]-a.i[c])*b+a.i[c]},a_=function(a,b,c,d,e){ZZ.call(this,b,c,d,e);
this.element=a},b_=function(a,b,c,d,e){if(2!=b.length||2!=c.length)throw Error("Start and end points must be 2D");
a_.call(this,a,b,c,d,e)},Ona=function(a){return Math.pow(a,3)},Pna=function(a){return 3*a*a-2*a*a*a},c_=function(a){g.G.call(this);
this.i=a||window;this.g=[]},Qna=function(a,b,c,d){c=(0,g.y)(c,d||a.i);
b=g.ls(b,"change",c,"iv-card-poll-choice-input");a.g.push(b)},d_=function(a,b){(0,g.A)(b,function(c){g.vs("visualElementShown",{csn:a,
ve:g.at(c),eventType:4},g.As,void 0,void 0)})},e_=function(a,b){(0,g.A)(b,function(c){g.vs("visualElementHidden",{csn:a,
ve:g.at(c),eventType:8},g.As,void 0,void 0)})},f_=function(a,b,c){this.id=a;
this.timestamp=b.timestamp||0;this.type=b.card_type;this.teaserText=b.teaser_text;this.teaserDurationMs=b.teaser_duration_ms;this.startMs=b.start_ms;this.autoOpen=b.auto_open||!1;this.sd=b.session_data||{};this.l=c;this.sponsored=b.sponsored||!1;a=b.tracking||{};this.i={UD:a.impression,click:a.click,close:a.close,CM:a.teaser_impression,Bs:a.teaser_click};b=b.tracking_params||{};this.D=g.$s(b.card);this.C=g.$s(b.teaser);this.u=g.$s(b.icon)},g_=function(a,b){g.Uf.call(this);
this.Mj=a;this.Lp=b;this[g.wf]=!1},l_=function(a,b,c,d){g_.call(this,a,b);
a=this.Lp;b=this.ha();c?(b.setAttribute("stroke",c.i),b.setAttribute("stroke-opacity",1),c=c.g,g.v(c)&&-1!=c.indexOf("px")?b.setAttribute("stroke-width",parseFloat(c)/Rna(a)):b.setAttribute("stroke-width",c)):b.setAttribute("stroke","none");this.fill=d;c=this.Lp;a=this.ha();if(d instanceof h_)a.setAttribute("fill",d.F),a.setAttribute("fill-opacity",d.H);else if(d instanceof i_){b="lg-"+d.u+"-"+d.C+"-"+d.A+"-"+d.D+"-"+d.g+"-"+d.i;var e=b in c.g?c.g[b]:null;if(!e){e=j_(c,"linearGradient",{x1:d.u,y1:d.C,
x2:d.A,y2:d.D,gradientUnits:"userSpaceOnUse"});var f="stop-color:"+d.g;g.Ga(d.l)&&(f+=";stop-opacity:"+d.l);f=j_(c,"stop",{offset:"0%",style:f});e.appendChild(f);f="stop-color:"+d.i;g.Ga(d.o)&&(f+=";stop-opacity:"+d.o);d=j_(c,"stop",{offset:"100%",style:f});e.appendChild(d);e=k_(c,b,e)}a.setAttribute("fill","url(#"+e+")")}else a.setAttribute("fill","none")},m_=function(){},n_=function(a,b){g_.call(this,a,b)},o_=function(){this.Ta=[];
this.Ca=[];this.Ud=[]},p_=function(a,b,c,d){var e=a.Ad[0]-b*Math.cos(g.ud(d))+b*Math.cos(g.ud(d+90)),f=a.Ad[1]-c*Math.sin(g.ud(d))+c*Math.sin(g.ud(d+90));
a.Ta.push(3);a.Ca.push(1);a.Ud.push(b,c,d,90,e,f);a.Rk=!1;a.Ad=[e,f]},Tna=function(a,b){for(var c=a.Ud,d=0,e=0,f=a.Ta.length;e<f;e++){var k=a.Ta[e],l=Sna[k]*a.Ca[e];
b(k,c.slice(d,d+l));d+=l}},q_=function(a,b,c,d){l_.call(this,a,b,c,d)},r_=function(a,b){this.g=a;
this.i=b},s_=function(a,b,c,d,e){g.Ao.call(this,e);
this.width=a;this.height=b;this.l=c||null;this.I=d||null},Rna=function(a){var b=a.Cj();
return b?b.width/(a.l?new g.xd(a.l,a.I):a.Cj()).width:0},i_=function(a,b,c,d,e,f,k,l){this.u=a;
this.C=b;this.A=c;this.D=d;this.g=e;this.i=f;this.l=g.Ea(k)?k:null;this.o=g.Ea(l)?l:null},h_=function(a,b){this.F=a;
this.H=null==b?1:b},t_=function(a,b){g_.call(this,a,b)},u_=function(a,b,c,d){l_.call(this,a,b,c,d)},v_=function(a,b,c,d,e){s_.call(this,a,b,c,d,e);
this.g={};this.O=g.Pd&&!g.pd(526);this.P=new g.rn(this)},j_=function(a,b,c){a=a.M.g.createElementNS("http://www.w3.org/2000/svg",b);
if(c)for(var d in c)a.setAttribute(d,c[d]);return a},w_=function(a,b,c,d){b=j_(a,"path",{d:Una(b)});
c=new u_(b,a,c,d);a.o.ha().appendChild(c.ha())},Una=function(a){var b=[];
Tna(a,function(c,d){switch(c){case 0:b.push("M");Array.prototype.push.apply(b,d);break;case 1:b.push("L");Array.prototype.push.apply(b,d);break;case 2:b.push("C");Array.prototype.push.apply(b,d);break;case 3:var e=d[3];b.push("A",d[0],d[1],0,180<Math.abs(e)?1:0,0<e?1:0,d[4],d[5]);break;case 4:b.push("Z")}});
return b.join(" ")},k_=function(a,b,c){if(b in a.g)return a.g[b];
var d="_svgdef_"+Vna++;c.setAttribute("id",d);a.g[b]=d;a.C.appendChild(c);return d},Wna=function(){x_||(x_=new g.Ig(400),x_.start());
return x_},y_=function(a,b){function c(l){return l.baseUrl}
function d(l){if(l){var m=l.simpleText;if(m)return m;if(l.runs)return(0,g.C)(l.runs,function(n){return n.text}).join("")}}
function e(l){if(l){var m=[],n=l.videoId;n&&m.push("v="+n);(n=l.playlistId)&&m.push("list="+n);(l=l.startTimeSeconds)&&m.push("t="+l);return"/watch?"+m.join("&")}}
var f={};f.startMs=parseInt(a.startMs,10);f.impressionUrls=(0,g.C)(a.impressionUrls||[],c);f.skip=a.skipEndscreen;a.trackingParams&&(f.visualElement=g.$s(a.trackingParams));var k=(0,g.C)(a.elements||[],function(l,m){var n=l.endscreenElementRenderer;if(!n)return null;var p={},r=n.style,u=n.endpoint||{};p.id="element-"+m;p.type=r;p.title=d(n.title);p.metadata=d(n.metadata);p.callToAction=d(n.callToAction);p.Yu=n.image;p.left=parseFloat(n.left);p.width=parseFloat(n.width);p.top=parseFloat(n.top);p.aspectRatio=
parseFloat(n.aspectRatio);p.startMs=parseInt(n.startMs,10);p.endMs=parseInt(n.endMs,10);p.clickUrls=(0,g.C)(u.loggingUrls||[],c);p.xl=g.Tb(n,"title","accessibility","accessibilityData","label");p.impressionUrls=(0,g.C)(n.impressionUrls||[],c);p.SD=(0,g.C)(n.hovercardShowUrls||[],c);p.sd={itct:n.trackingParams};p.visualElement=g.$s(n.trackingParams);if("VIDEO"==r)p.targetUrl=u.urlEndpoint?u.urlEndpoint.url:e(u.watchEndpoint),p.sm=!1,p.Wn=b,p.videoDuration=d(n.videoDuration);else if("PLAYLIST"==r)p.targetUrl=
u.urlEndpoint?u.urlEndpoint.url:e(u.watchEndpoint),p.sm=!1,p.Wn=b,p.playlistLength=d(n.playlistLength);else if("CHANNEL"==r){if(r=g.Tb(u,"browseEndpoint","browseId"))p.channelId=r,p.targetUrl="/channel/"+r;p.sm=!1;p.Wn="new";p.isSubscribe=!!n.isSubscribe;if(p.isSubscribe){a:{if(r=n.hovercardButton)if(r=r.subscribeButtonRenderer){u=d(r.unsubscribedButtonText);var z=d(r.subscribedButtonText);if(r.subscribed){var D=d(r.subscriberCountWithUnsubscribeText);var E=d(r.subscriberCountText)}else D=d(r.subscriberCountText),
E=d(r.subscriberCountWithSubscribeText);var F=null;if(n.signinEndpoint&&(F=g.Tb(n,"signinEndpoint","webNavigationEndpointData","url"),!F)){n=void 0;break a}if(u&&(z||F)){n={subscribed:r.subscribed,subscribeText:u,subscribeCount:D,unsubscribeText:z,unsubscribeCount:E,enabled:r.enabled,signinUrl:F,classic:n.useClassicSubscribeButton};break a}}n=void 0}p.subscribeButton=n}else p.subscribersText=d(n.subscribersText)}else"WEBSITE"==r&&(p.targetUrl=g.Tb(u,"urlEndpoint","url"),p.sm=!0,p.Wn="new",p.iconUrl=
n.icon.thumbnails[0].url);return p});
f.elements=(0,g.Zd)(k,function(l){return!!l});
return f},z_=function(a){g.RK.call(this,a);
this.i=null;this.H=!1;this.o=null;this.g={};this.C={};this.A=this.l=null;this.I=[];a=g.X(a);this.P=g.$y(a)||g.fz(a);this.sA=!0;this.D=0;this.F=new g.ao;this.u=new g.Ls(this);g.H(this,this.u);this.u.K(this.player,g.pE("creatorendscreen"),this.OE);this.u.K(this.player,"crx_creatorendscreen",this.PE);this.u.K(this.player,"resize",this.ib);this.u.K(window,"focus",this.EL);this.load();var b=g.Td("STYLE");(document.getElementsByTagName("HEAD")[0]||document.body).appendChild(b);g.rf(this,function(){g.Yd(b)});
b.sheet&&(b.sheet.insertRule(".ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAIVBMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///91E4wTAAAACXRSTlMArBbpVOtYrReN+x2FAAAAAWJLR0QKaND0VgAAACFJREFUCNdjYCAWzIQAFBaZ6hgVYLKcJnBWGEyWvYGASwCXtBf7m4i3CQAAAABJRU5ErkJggg==) no-repeat center;background-size:18px;width:18px;height:18px}",0),b.sheet.insertRule(".ytp-ce-size-853 .ytp-ce-playlist-icon, .ytp-ce-size-1280 .ytp-ce-playlist-icon, .ytp-ce-size-1920 .ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJ1BMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///9RfzIKAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAyBs1FjAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0))},A_=function(a){return a.player.getVideoData().Mb?"current":a.P?"new":"current"},B_=function(a){return"creator-endscreen-editor"===a},C_=function(a,b){g.zK(a.player,"creatorendscreen");
a.l&&(a.l.dispose(),a.l=null,a.A.dispose(),a.A=null);for(var c in a.g)a.g[c].dispose();a.g={};a.C={};0<a.I.length&&(a.I.forEach(function(l){l.dispose()}),a.I.length=0);
a.D=0;if((a.i=b)&&b.elements){Xna(a);c=[];var d=new g.mE(b.startMs,0x7ffffffffffff,{id:"ytp-ce-in-endscreen",namespace:"creatorendscreen"});c.push(d);g.X(a.player).g||(a.l=new g.W({B:"div",G:"ytp-ce-shadow"}),g.DK(a.player,a.l.element,4),a.A=new g.nQ(a.l,200));for(d=0;d<b.elements.length;++d){var e=b.elements[d],f=Yna(a,e);a.g[e.id]=f;a.C[e.id]=e;g.DK(a.player,f.element,4);var k=new g.mE(e.startMs,e.endMs,{id:"ytp-ce-element-"+e.id,namespace:"creatorendscreen"});c.push(k);Zna(a,f,e)}g.wK(a.player,
c);a.ib()}},Xna=function(a){var b=g.pt(),c=g.qt();
c&&b&&a.i.visualElement&&g.bt(c,b,[a.i.visualElement],void 0)},Yna=function(a,b){var c=null;
switch(b.type){case "VIDEO":c={B:"div",W:["ytp-ce-element","ytp-ce-video"],L:{tabindex:"0","aria-label":b.xl||"","aria-hidden":"true"},J:[{B:"div",G:"ytp-ce-element-shadow"},{B:"div",G:"ytp-ce-covering-image",L:Y_(b)},{B:"div",G:"ytp-ce-covering-shadow-top"},{B:"a",G:"ytp-ce-covering-overlay",L:{href:l0(a,b.targetUrl),tabindex:"-1"},J:[{B:"div",W:["ytp-ce-video-title","yt-ui-ellipsis","yt-ui-ellipsis-2"],L:{dir:g.bo(a.F,b.title||"")},U:b.title},{B:"div",G:"ytp-ce-video-duration",U:b.videoDuration}]}]};
c=new g.W(c);break;case "PLAYLIST":c={B:"div",W:["ytp-ce-element","ytp-ce-playlist"],L:{tabindex:"0","aria-label":b.xl||"","aria-hidden":"true"},J:[{B:"div",G:"ytp-ce-element-shadow"},{B:"div",G:"ytp-ce-covering-image",L:Y_(b)},{B:"div",G:"ytp-ce-covering-shadow-top"},{B:"a",G:"ytp-ce-covering-overlay",L:{href:l0(a,b.targetUrl),tabindex:"-1"},J:[{B:"div",W:["ytp-ce-playlist-title","yt-ui-ellipsis","yt-ui-ellipsis-2"],L:{dir:g.bo(a.F,b.title||"")},U:b.title},{B:"div",G:"ytp-ce-playlist-count",J:[{B:"div",
G:"ytp-ce-playlist-icon"},{B:"div",G:"ytp-ce-playlist-count-text",U:b.playlistLength}]}]}]};c=new g.W(c);break;case "CHANNEL":c={B:"div",W:["ytp-ce-element","ytp-ce-channel",b.isSubscribe?"ytp-ce-channel-this":"ytp-ce-channel-that"],L:{tabindex:"0","aria-label":b.xl||"","aria-hidden":"true"},J:[{B:"div",G:"ytp-ce-element-shadow"},{B:"div",G:"ytp-ce-expanding-overlay",J:[{B:"div",G:"ytp-ce-expanding-overlay-hider"},{B:"div",G:"ytp-ce-expanding-overlay-background"},{B:"div",G:"ytp-ce-expanding-overlay-content",
J:[{B:"div",G:"ytp-ce-expanding-overlay-body",J:[{B:"div",G:"ytp-ce-expanding-overlay-body-padding",J:[{B:"a",W:["ytp-ce-channel-title","ytp-ce-link"],L:{href:l0(a,b.targetUrl),target:"_blank",tabindex:"-1",dir:g.bo(a.F,b.title||"")},U:b.title},b.subscribeButton?{B:"div",G:"ytp-ce-subscribe-container",J:[{B:"div",G:"ytp-ce-channel-subscribe"}]}:"",b.subscribersText?{B:"div",G:"ytp-ce-channel-subscribers-text",U:b.subscribersText}:"",b.metadata?{B:"div",W:["ytp-ce-channel-metadata","yt-ui-ellipsis",
"yt-ui-ellipsis-3"],U:b.metadata}:""]}]}]}]},{B:"div",G:"ytp-ce-expanding-image",L:Y_(b)}]};c=new g.W(c);var d=g.Gd(document,"div","ytp-ce-channel-subscribe",c.element)[0];if(b.subscribeButton){g.J(d,"ytp-ce-subscribe-button");if(g.X(a.player).g){var e=null;var f=b.sd.itct}else e="endscreen",f=null;e=new g.gW(b.subscribeButton.subscribeText,b.subscribeButton.subscribeCount,b.subscribeButton.unsubscribeText,b.subscribeButton.unsubscribeCount,b.subscribeButton.enabled,b.subscribeButton.classic,b.channelId,
!!b.subscribeButton.subscribed,e,f,b.subscribeButton.signinUrl,a.player);d.appendChild(e.element);a.I.push(e)}break;case "WEBSITE":c={B:"div",W:["ytp-ce-element","ytp-ce-website"],L:{tabindex:"0","aria-label":b.xl||"","aria-hidden":"true"},J:[{B:"div",G:"ytp-ce-element-shadow"},{B:"div",G:"ytp-ce-expanding-overlay",J:[{B:"div",G:"ytp-ce-expanding-overlay-hider"},{B:"div",G:"ytp-ce-expanding-overlay-background"},{B:"div",G:"ytp-ce-expanding-overlay-content",J:[{B:"div",G:"ytp-ce-expanding-overlay-body",
J:[{B:"div",G:"ytp-ce-expanding-overlay-body-padding",J:[{B:"div",G:"ytp-ce-website-title",L:{dir:g.bo(a.F,b.title||"")},U:b.title},{B:"div",G:"ytp-ce-website-metadata",U:b.metadata},{B:"a",W:["ytp-ce-website-goto","ytp-ce-link"],L:{href:l0(a,b.targetUrl),target:"_blank",tabindex:"-1"},U:b.callToAction}]}]}]}]},{B:"div",G:"ytp-ce-expanding-image",L:Y_(b)},{B:"div",G:"ytp-ce-expanding-icon",L:m0(b.iconUrl)}]},c=new g.W(c)}b.g&&g.J(c.element,"ytp-ce-placeholder");return c},Y_=function(a){if(a.Yu)var b=
a.Yu.thumbnails;
return m0(b?b[b.length-1].url:null)},m0=function(a){return a?{style:"background-image: url("+a+")"}:{}},Zna=function(a,b,c){function d(){k(1)}
function e(){k(-1)}
b.ca("mouseenter",(0,g.y)(a.Mq,a,b,c));b.ca("mouseleave",(0,g.y)(a.Fr,a,b,c));g.X(a.player).g||b.ca("click",(0,g.y)(function(l){g.J(l.element,"ytp-ce-element-hover")},a,b));
b.ca("click",(0,g.y)(a.Ay,a,c));b.ca("keypress",(0,g.y)(a.Ay,a,c));b.ca("focus",(0,g.y)(function(l,m){this.Mq(l,m)},a,b,c));
b.ca("blur",(0,g.y)(function(l,m){this.Fr(l,m)},a,b,c));
b.ca("touchstart",(0,g.y)(a.Mq,a,b,c));var f=g.Id("ytp-ce-expanding-overlay-hider",b.element);f&&b.K(f,"touchstart",function(l){l=l||window.event;l.cancelBubble=!0;l.stopPropagation&&l.stopPropagation();g.io(b.element,"ytp-ce-element-hover");g.io(b.element,"ytp-ce-force-expand")});
b.ca("keydown",(0,g.y)(function(l,m){this.sA=9==m.keyCode&&!m.shiftKey},a,b));
var k=(0,g.y)(function(l,m,n){this.D+=n;0<this.D?(g.J(l.element,"ytp-ce-force-expand"),n0(this,m.id,!0)):(g.io(l.element,"ytp-ce-force-expand"),g.io(l.element,"ytp-ce-element-hover"),n0(this,m.id,!1))},a,b,c);
a=(0,g.y)(function(l,m){m&&(l.ca("blur",function(){RZ(m)&&this.sA&&m.focus()}),l.K(m,"focus",d),l.K(m,"blur",e))},a,b);
a(g.Id("ytp-sb-subscribe",b.element));a(g.Id("ytp-sb-unsubscribe",b.element));b.ca("focus",d);b.ca("blur",e)},l0=function(a,b){var c=g.X(a.player);
if(b){if(b.startsWith("//"))return c.protocol+":"+b;if(b.startsWith("/"))return g.Cz(c)+b}else return"";return b},n0=function(a,b,c){a.l&&(c?a.A.show():a.A.hide());
for(var d in a.g)d!=b&&g.K(a.g[d].element,"ytp-ce-element-shadow-show",c)},o0=function(a,b,c){function d(){f||(e++,e==b.length&&(k.stop(),c&&c()))}
if(!b||B_(g.X(a.player).playerStyle))c&&c();else{b=$na(a,b);var e=0,f=!1,k=new g.M(function(){f=!0;c&&c()},1E3,a);
k.start();for(a=0;a<b.length;a++)g.or(b[a],d)}},p0=function(a,b,c){o0(a,b.clickUrls,c);
(a=g.qt())&&b.sm&&g.dt(a,b.visualElement)},$na=function(a,b){var c=a.player.getVideoData().clientPlaybackNonce,d=a.player.getCurrentTime().toFixed(2);
c={CPN:c,AD_CPN:c,MT:d};d=[];for(var e=0;e<b.length;e++)d.push(aoa(b[e],c));return d},aoa=function(a,b){return a.replace(/%5B[a-zA-Z_:]+%5D|\[[a-zA-Z_:]+\]/g,function(c){var d=unescape(c);
d=d.substring(1,d.length-1);return b[d]?escape(b[d]):c})},q0=function(a){return g.La(a)&&a.length?a[0]:a},r0=function(a){var b=/.+/;
return g.v(a)&&null!=b&&null!=a&&a.match(b)?a:""},s0=function(a,b){if(null==a)return b;
var c=parseInt(a,0);if(isNaN(c))return b;c=c.toString(16);return"#"+"000000".substring(0,6-c.length)+c},t0=function(a){return g.v(a)?a:""},u0=function(a,b,c){for(var d in b)if(b[d]==a)return a;
return c},v0=function(a,b){return"true"==a||"false"==a?"true"==a:b},w0=function(a,b){return g.v(a)?parseFloat(a):b},x0=function(a,b,c,d,e){a=parseFloat(a);
if(null!=a&&!isNaN(a)){if(d)return g.rd(a,b,c);if(a>=b&&a<=c)return a}return e},boa=function(a){if(null==a)return 0;
if("never"==a)return-1;a=a.split(":");if(3<a.length)return 0;var b=0,c=1;(0,g.A)(a,function(d){d=parseFloat(d);0>d&&(c=-c);b=60*b+Math.abs(d)});
return c*b},y0=function(a,b){if(null==a)return null;
if(g.Ma(a)){var c=[];(0,g.A)(a,function(e){(e=b(e))&&c.push(e)});
return c}var d=b(a);return d?[d]:[]},coa=function(a){function b(c){return null!=c&&!isNaN(c)}
return(a=a?new g.nh(parseFloat(a.top),parseFloat(a.right),parseFloat(a.bottom),parseFloat(a.left)):null)&&b(a.top)&&b(a.right)&&b(a.bottom)&&b(a.left)?a:null},doa=function(a){function b(c){return(0,g.Zd)(c.split(/ +/),function(d){return""!=d})}
return null==a?[]:b(a)},eoa=function(a){this.externalId=a},foa=function(a,b,c,d){this.value=a;
this.target=b;this.showLinkIcon=c;this.g=d},z0=function(a){if(!a)return null;
var b=g.Dc(t0(a.value));b=g.Ac(b);if(!b)return null;var c=u0(a.target,goa,"current");return null==c?null:new foa(b,c,v0(a.show_link_icon,!0),null!=a.pause_on_navigation?a.pause_on_navigation:!0)},A0=function(a){return a.value?a.value:null},hoa=function(a,b,c,d){this.type=a;
this.trigger=b;this.url=c;this.subscribeData=d},koa=function(a){if(!a)return null;
var b=u0(a.type,ioa),c=u0(a.trigger,joa),d=q0(a.url);d=z0(d?d:null);a=q0(a.subscribeData);var e=a?a:null;e?(a=t0(e.external_user_id),e=t0(e.subscription_token),a=a&&e?new eoa(a):null):a=null;return b?new hoa(b,c,d,a):null},B0=function(a,b,c){var d=(c="xx"==c||"xy"==c)?640:360;
return(d+((c?a.width:a.height)-d)*b)/d},C0=function(a,b,c){var d=(c="xy"==c||"yy"==c)?360:640;
return(d+((c?a.height:a.width)-d)*b)/d},D0=function(a,b,c,d,e,f,k,l,m,n,p){this.x=a;
this.y=b;this.Vi=c;this.l=d;this.t=e;this.u=f;this.A=k;this.C=l;this.o=m;this.i=n;this.g=p},E0=function(a,b){if(!a)return null;
var c=w0(a.x,0),d=w0(a.y,0),e=w0(a.w,0),f=w0(a.h,0),k=boa(a.t),l=w0(a.d,0),m=w0(a.px,0),n=w0(a.py,0),p=w0(a.scaleSlope,1),r=w0(a.scaleSlopeX,p);p=w0(a.scaleSlopeY,p);var u=u0(a.scaleDimension,loa,"xy");return b(c,d,e,f,k,l,m,n,r,p,u)},H0=function(a,b){var c=F0(b,G0(a,new g.qh(a.x,a.y,a.Vi,a.l),b.g)),d=b.g,e=c.clone();
d&&!d.contains(c)&&(c.width<d.width?e.left=g.rd(c.left,d.left,d.left+d.width-c.width):(e.left=d.left,e.width=d.width),c.height<d.height?e.top=g.rd(c.top,d.top,d.top+d.height-c.height):(e.top=d.top,e.height=d.height));return e},G0=function(a,b,c){var d=a.A,e=a.C,f=a.g?a.g:"xy",k=B0(c,a.o,f);
a=C0(c,a.i,f);f=640*b.width*k/100;var l=360*b.height*a/100;return new g.qh(0==d?640*b.left*k/100:0<d?d:c.width+d-f,0==e?360*b.top*a/100:0<e?e:c.height+e-l,f,l)},I0=function(a){return a?E0(a,function(b,c,d,e,f,k,l,m,n,p,r){return new D0(b,c,d,e,f,k,l,m,n,p,r)}):null},J0=function(a,b){this.g=a;
this.i=b||null},F0=function(a,b){var c=a.i?H0(a.i,new J0(a.g)):a.g;
var d=b.clone(),e=c.left;c=c.top;e instanceof g.vd?(d.left+=e.x,d.top+=e.y):(d.left+=e,g.Ga(c)&&(d.top+=c));return d},K0=function(a,b,c,d,e,f,k,l,m,n,p,r,u){D0.call(this,a,b,c,d,e,l,m,n,p,r,u);
this.D=f;this.F=k},moa=function(a){if(!a)return null;
var b=w0(a.sx,0),c=w0(a.sy,0);return E0(a,function(d,e,f,k,l,m,n,p,r,u,z){return new K0(d,e,f,k,l,b,c,m,n,p,r,u,z)})},noa=function(a,b,c,d,e,f,k,l,m,n,p,r,u,z){this.i=a;
this.bgColor=b;this.borderColor=c;this.borderWidth=d;this.g=e;this.A=f;this.l=k;this.textAlign=l;this.textSize=m;this.o=n;this.padding=p;this.effects=r;this.cornerRadius=u;this.u=z},L0=function(a){if(!a)return null;
var b=s0(a.fgColor,"#1A1A1A"),c=s0(a.bgColor,"#FFF"),d=s0(a.borderColor,"#000"),e=x0(a.borderWidth,0,5,!1,0),f=x0(a.bgAlpha,0,1,!1,.8),k=s0(a.highlightFontColor,"#F2F2F2"),l=x0(a.highlightWidth,0,5,!1,3),m=t0(a.textAlign),n=x0(a.textSize,3.3,30.1,!0,3.6107),p=t0(a.fontWeight),r=coa(a.padding),u=doa(a.effects),z=x0(a.cornerRadius,0,10,!0,0);a=q0(a.gradient);if(a=a?a:null){var D=x0(a.x1,0,100,!0,0),E=x0(a.y1,0,100,!0,0),F=x0(a.x2,0,100,!0,100),L=x0(a.y2,0,100,!0,100),ba=s0(a.color1,"#FFF"),qa=s0(a.color2,
"#000");a=new ooa(D,E,F,L,ba,qa,x0(a.opacity1,0,100,!0,100),x0(a.opacity2,0,100,!0,0))}else a=null;return new noa(b,c,d,e,f,k,l,m,n,p,r,u,z,a)},ooa=function(a,b,c,d,e,f,k,l){this.l=a;
this.u=b;this.o=c;this.A=d;this.g=e;this.i=f;this.C=k;this.D=l},poa=function(a,b,c,d){this.type=a;
this.i=b;this.g=c;this.l=d},roa=function(a){if(!a)return null;
var b=u0(a.type,qoa,"rect"),c=y0(a.rectRegion,I0),d=y0(a.anchoredRegion,moa);a=y0(a.shapelessRegion,I0);return new poa(b,c,d,a)},M0=function(a){return a.i&&a.i.length?a.i[0]:a.g&&a.g.length?a.g[0]:a.l&&a.l.length?a.l[0]:null},soa=function(a,b){this.i=a;
this.g=b},toa=function(a,b){this.state=a;
this.ref=b},N0=function(a){if(!a)return null;
var b=u0(a.state,uoa);a=r0(a.ref);return b?new toa(b,a):null},voa=function(a,b,c,d){this.g=a||[];
this.l=b||[];this.o=c;this.i=d;this.value=!1},woa=function(a){if(!a)return null;
var b=y0(a.condition,N0),c=y0(a.notCondition,N0),d=v0(a.show_delay,!1);a=v0(a.hide_delay,!1);return b||c?new voa(b,c,d,a):null},xoa=function(a,b,c){(0,g.A)(a.g,g.Ra(b,!1),c);
(0,g.A)(a.l,g.Ra(b,!0),c)},O0=function(a,b,c,d,e,f,k,l,m,n,p,r,u,z){this.id=a;
this.author=b;this.type=c;this.style=d;this.o=e;this.segment=f;this.l=k||[];this.C=l||[];this.i=m;this.A=n;this.u=p;this.data=r;this.g=u;this.itct=z},Aoa=function(a){if(!a)return null;
var b=r0(a.id),c=r0(a.author),d=u0(a.type,yoa),e=u0(a.style,P0),f=t0(q0(a.TEXT)),k=t0(a.data);k=0!=k.length?JSON.parse(k):{};var l=q0(a.segment);var m=l?l:null;m?(r0(m.timeRelative),l=r0(m.spaceRelative),l=(m=y0(m.movingRegion,roa))?new soa(l,m):null):l=null;m=y0(a.action,koa);var n=y0(a.trigger,woa),p=q0(a.appearance);(p=L0(p?p:null))||(p=L0({}));var r=u0(a.coordinate_system,zoa,"video_relative"),u=v0(a.closeable,!0),z=t0(a.log_data);a=t0(a.itct);return b&&d?new O0(b,c,d,e,f,l,m,n,p,r,u,k,z,a):null},
R0=function(a){return Q0(a,function(b){return"click"==b.trigger})},Q0=function(a,b){return(0,g.Uj)(a.l,b,void 0)},Boa=function(a,b,c){(0,g.A)(a.l,b,c)},Coa=function(a,b){return g.Ya(a.l,b,void 0)},S0=function(a,b,c){(0,g.A)(a.C,b,c)},Doa=function(a,b){(0,g.C)(a.C,b,void 0)},U0=function(a){return(a=T0(a))?M0(a):null},T0=function(a){a.segment?(a=a.segment,a=a.g.length?a.g[0]:null):a=null;
return a},V0=function(a,b){var c=U0(a);
return c&&b?C0(b,c.i,c.g?c.g:"xy"):1},X0=function(a,b,c){this.g={};
this.l=!1;this.u="ivTrigger:"+a;this.i=c;xoa(b,function(d,e){var f=W0(e.state,e.ref);this.i.subscribe(f,(0,g.y)(this.o,this,f,d));this.g[f]=d},this)},W0=function(a,b){var c="ivTriggerCondition:"+a;
return b?c+":"+b:c},Y0=function(){this.g=!1;
this.u=this.i=null},Z0=function(a,b,c){a.i?(a.i.setSize(b,c),a.i.clear()):(b=new v_(b,c,void 0,void 0,void 0),a.i=b,a.i.Qp(),a.u=g.Sd("DIV"),a.u.appendChild(a.i.ha()));
return a.i},$0=function(a,b,c){var d=document.createElementNS("http://www.w3.org/2000/svg",a);
b&&g.Lb(b,function(f,k){d.setAttribute(k,f)});
for(var e=2;e<arguments.length;e++)d.appendChild(arguments[e]);return d},a1=function(a,b){var c=g.zo(g.yo.getInstance());
b.setAttribute("result",c);a.appendChild(b);return c},Eoa=function(a,b){var c=a1(a,$0("feGaussianBlur",{"in":b,
stdDeviation:"1.8"}));c=a1(a,$0("feDiffuseLighting",{"in":c,surfaceScale:"4",diffuseConstant:"1"},$0("feDistantLight",{azimuth:"270",elevation:"15","lighting-color":"white"})));c=a1(a,$0("feComposite",{"in":c,in2:b,operator:"in"}));return a1(a,$0("feComposite",{in2:c,"in":b,operator:"arithmetic",k2:1,k3:.5,k4:0}))},Foa=function(a,b){var c=a1(a,$0("feOffset",{"in":b,
dx:"-7",dy:"-7"}));c=a1(a,$0("feGaussianBlur",{"in":c,stdDeviation:"3"}));c=a1(a,$0("feColorMatrix",{"in":c,type:"matrix",values:"0 0 0 0 0  0 0 0 0 0  0 0 0 0 0  0 0 0 0.5 0"}));var d=a1(a,$0("feColorMatrix",{"in":b,type:"matrix",values:"0 0 0 0 0  0 0 0 0 0  0 0 0 0 0  0 0 0 100 0"}));d=a1(a,$0("feGaussianBlur",{"in":d,stdDeviation:"1"}));c=a1(a,$0("feComposite",{operator:"out","in":c,in2:d}));return a1(a,$0("feComposite",{operator:"over","in":b,in2:c}))},Goa=function(a,b){return b},Hoa=function(a){var b=
$0("filter",{filterUnits:"userSpaceOnUse"}),c="SourceGraphic";
(0,g.A)(a,function(d){a:{switch(d){case "bevel":d=Eoa;break a;case "dropshadow":d=Foa;break a}d=Goa}c=d(b,c)});
return b},Ioa=function(a){a=(0,g.Zd)(a,function(b){return b in b1});
g.rb(a,function(b,c){return b1[b]-b1[c]});
return a},Joa=function(a){return g.Ya(a,function(b){return"dropshadow"==b})?new g.nh(0,7,7,0):new g.nh(0,0,0,0)},c1=function(a,b,c){var d=new o_;
d.moveTo(a.left+b+c,a.top+c);d.dc(a.left+a.width-b-c,a.top+c);p_(d,b,b,-90);d.dc(a.left+a.width-c,a.top+a.height-b-c);p_(d,b,b,0);d.dc(a.left+b+c,a.top+a.height-c);p_(d,b,b,90);d.dc(a.left+c,a.top+b+c);p_(d,b,b,180);d.close();return d},d1=function(a,b,c,d){var e=a.u;
e?a=new i_(e.l*b/100,e.u*c/100,e.o*b/100,e.A*c/100,e.g,e.i,e.C,e.D):(b=a.g,a=new h_(a.bgColor,d?Math.max(b,.9):b));return a},e1=function(a,b){var c=g.rh(a),d=Joa(b);
g.Oa(d)?(c.top-=d.top,c.right+=d.right,c.bottom+=d.bottom,c.left-=d.left):(c.top-=d,c.right+=Number(void 0),c.bottom+=Number(void 0),c.left-=Number(void 0));return new g.qh(c.left,c.top,c.right-c.left,c.bottom-c.top)},f1=function(a,b,c){if(c.length&&(b=g.Gd(document,"g",void 0,b),b.length)){var d=Ioa(c);
if(d){c="effects:"+(d?d.join("|"):"");var e=c in a.g?a.g[c]:null;e?a=e:(d=Hoa(d),a=0<d.childNodes.length?k_(a,c,d):null)}else a=null;a&&b[0].setAttribute("filter","url(#"+a+")")}},g1=function(){Y0.call(this);
this.o=0},Koa=function(a,b){var c=a.top-b.y,d=b.x-a.left-a.width,e=b.y-a.top-a.height,f=a.left-b.x,k=Math.max(c,d,e,f);
if(0>k)return"i";switch(k){case c:return"t";case d:return"r";case e:return"b";case f:return"l"}return"i"},h1=function(){Y0.apply(this,arguments)},i1=function(){Y0.apply(this,arguments)},j1=function(){g1.apply(this,arguments)},k1=function(a,b,c,d,e){g.G.call(this);
this.g=a;this.R=b;this.A=c;this.X=d;this.Z=e;this.F=!1;this.aa=new c_(this);g.H(this,this.aa);this.M=this.u=this.C=this.P=this.i=null;this.V=!1;this.ba=this.H=this.I=null;this.gn=new g.Ll(this.sD,100,this);g.H(this,this.gn);this.D=new g.M(this.jw,500,this);g.H(this,this.D);this.O=this.l=this.o=null},Loa=function(a,b){var c=(0,g.y)(function(d,e,f){e=f?l1(this,e,(0,g.y)(f,this)):l1(this,e);
this.aa.ca(b,d,e)},a);
c("mouseover","G",a.kx);c("mouseout","F",a.zg);c("click","D");c("touchend","D")},Moa=function(a){if(a.g.u){if(Q0(a.g,function(d){return"close"==d.type}))var b=a.i;
else a.o=g.Sd("DIV","annotation-close-button"),g.Wh(a.o,!1),g.Up(a.o,"annotation_id",a.g.id),a.i.appendChild(a.o),b=a.o;var c=function(d){d.stopPropagation()};
a.aa.ca(b,"click",l1(a,"E",c));a.aa.ca(b,"touchend",l1(a,"E",c))}},l1=function(a,b,c){return(0,g.y)(function(d){if(this.Z)c&&c(d);
else if(d.event.target instanceof Element){var e=d.event.target;g.Wh(e,!1);try{var f=document.elementFromPoint(d.event.clientX,d.event.clientY);if(g.he(f,null,"annotation",void 0)){var k=document.createEvent("MouseEvent");k.initMouseEvent(d.event.type,d.event.bubbles,d.event.cancelable,d.event.view,d.event.detail,d.event.screenX,d.event.screenY,d.event.clientX,d.event.clientY,d.event.ctrlKey,d.event.altKey,d.event.shiftKey,d.event.metaKey,d.event.button,d.event.relatedTarget);f.dispatchEvent(k)}}finally{g.Wh(e,
!0)}}e=PZ(d.target);d=new g.vd(d.clientX,d.clientY);"F"==b&&e.contains(d)||this.X.N(b,this.g)},a)},o1=function(a){if(a.i||a.l){var b=U0(a.g);
if(b){var c=m1(a);if(a.i){b=H0(b,c);var d=g.pK(a.A).getVideoContentRect();g.Uh(a.i,b.width,b.height);g.Kh(a.i,b.left,b.top);a.P=new g.qh(d.left+b.left,d.top+b.top,b.width,b.height);var e=(e=U0(a.g))&&d?B0(d,e.o,e.g?e.g:"xy"):1;var f=V0(a.g,d);d=a.g.i;d.padding?d=d.padding:(d="speech"==a.g.style?1.6:.8,d=new g.nh(d,d,d,d));d=new g.nh(360*d.top*f/100,640*d.right*e/100,360*d.bottom*f/100,640*d.left*e/100);a.u&&(d.right+=1.5*c.g.height/100);a.i.style.padding=d.top+"px "+d.right+"px "+d.bottom+"px "+d.left+
"px";"label"==a.g.style&&a.C&&(a.C.style.padding=a.i.style.padding);d=c.g;var k=!1,l=0,m=0;var n=g.pK(a.A).getVideoContentRect();var p=g.uK(a.A);g.sh(n,p)?n=null:(p.top+=20,p.height-=40,"player_relative"!=a.g.A&&(p.left-=n.left,p.top-=n.top),n=p);n&&(l=n.top-(b.top+b.height),m=b.top-(n.top+n.height),k=0<l||0<m);if(k&&n){d=l;e=m;if(a.u){f=n1(a,23,b,d,e);if(a.o){var r=43-f.width;0<r&&(b.left+f.left-r>n.left&&(f.left-=r),f.width+=r)}r=f;g.Uh(a.u,f.width,f.height);g.Kh(a.u,f.left,f.top)}a.o&&(r?b=new g.vd(r.left+
r.width-23-18,a.V?r.top+2:r.top+r.height-18-2):(r=n1(a,18,b,d,e),b=new g.vd(r.left,r.top),g.Uh(a.o,r.width,r.height)),g.Kh(a.o,b));a.M=new g.qh(a.P.left+r.left,a.P.top+r.top,r.width,r.height);a.I=a.aa.ca(g.pK(a.A),"mousemove",a.CF,a)}else a.u&&(r=e/f*d.height*4.2/100,r=new g.xd(r,r),"highlight"==a.g.type||"label"==a.g.style?(e=1.5*d.height/100,r=new g.qh(b.width-r.width-e,b.height-r.height-e,r.width,r.height)):r=new g.qh(b.width-r.width-3*d.height/100,(b.height-r.height)/2,r.width,r.height),g.Uh(a.u,
r.width,r.height),g.Kh(a.u,r.left,r.top)),a.o&&(r=9<=d.left+d.width-(b.left+b.width),e=9<=b.top-d.top,g.Kh(a.o,r&&e?new g.vd(b.width-9,-9):r?new g.vd(b.width-9,45<b.height?9:b.height-9):e?new g.vd(45<b.width?b.width-9-18:-9,-9):b.width/d.width>b.height/d.height?new g.vd(45<b.width?b.width-9-18:-9,b.height-9):new g.vd(-9,45<b.height?9:b.height-9)))}a.l&&a.l.l(a.g,c);if(a.i){c=a.i;b=a.g.i;c.style.color="highlightText"==a.g.style?b.A:b.i;r=g.pK(a.A).getVideoContentRect();c.style.fontSize=360*b.textSize*
V0(a.g,r)/100+"px";r=a.g.style;c.style.textAlign=b.textAlign?b.textAlign:"title"==r||"highlightText"==r?"center":"left";b.o&&(c.style.fontWeight=b.o);a=a.i;c=a.style.overflow;r=(b=g.Id("annotation-link-icon",a))?RZ(b):!1;e=(d=g.Id("annotation-close-button",a))?RZ(d):!1;r&&g.Wh(b,!1);e&&g.Wh(d,!1);m=f="";if(n=g.Id("inner-text",a))f=n.style.overflow,m=n.style.position,n.style.overflow="visible",n.style.position="static";a.style.overflow="scroll";if(a.scrollHeight>a.offsetHeight||a.scrollWidth>a.offsetWidth){l=
k=Lna(a);p=5;for(var u=Math.floor(k/2);u;)a.scrollHeight<=a.offsetHeight&&a.scrollWidth<=a.offsetWidth?(p=l,l=Math.min(l+u,k)):l=Math.max(l-u,p),u=Math.floor(u/2),a.style.fontSize=l+"px";l!=p&&(a.scrollHeight>a.offsetHeight||a.scrollWidth>a.offsetWidth)&&(a.style.fontSize=p+"px")}a.style.overflow=c;n&&(n.style.overflow=f,n.style.position=m);e&&g.Wh(d,!0);r&&g.Wh(b,!0)}}}},n1=function(a,b,c,d,e){var f=0<e;
b=new g.qh(0,c.height-b,Math.max(c.width,b),b);0<d&&(b.top=c.height,20<d&&(b.height+=d-20),g.J(a.i,"annotation-extend-down"));f&&(b.top=-b.height,20<e&&(c=e-20,b.top-=c,b.height+=c),g.J(a.i,"annotation-extend-up"),a.V=!0);return b},p1=function(a){return"label"!=a.g.style||a.l.g},m1=function(a){var b=g.pK(a.A).getVideoContentRect();
if("player_relative"==a.g.A){var c=g.pK(a.A).getPlayerSize();b=new g.qh(-b.left,-b.top,c.width,c.height)}else b=new g.qh(0,0,b.width,b.height);return new J0(b,a.O?U0(a.O):null)},q1=function(a,b){return b?new g.qh(a.x+b.left,a.y+b.top,b.width,b.height):null},r1=function(a,b,c){g.G.call(this);
this.i=a;this.annotation=b;this.view=c;this.g=null;this.l=this.isVisible=!1;Noa(b,a)},Noa=function(a,b){Doa(a,function(c){return new X0(a.id,c,b)})},s1=function(a){a.i.unsubscribe("resize",a.jx,a);
a.i.unsubscribe("onVideoAreaChange",a.Zy,a)},t1=function(a){a.g&&(a.g.stop(),a.g=null)},u1=function(a,b,c){f_.call(this,a,b,c);
this.channelId=b.channel_id;this.customMessage=b.custom_message;this.o=b.image_url;this.title=b.title;this.metaInfo=b.meta_info;this.url=z0({pause_on_navigation:b.pause_on_navigation,target:b.target||"new",value:b.url})},v1=function(a,b,c){f_.call(this,a,b,c);
this.o=b.image_url;this.playlistVideoCount=b.playlist_video_count;this.customMessage=b.custom_message;this.title=b.title;this.metaInfo=b.meta_info;this.url=z0({pause_on_navigation:b.pause_on_navigation,target:b.target||"new",value:b.url})},w1=function(a,b,c){f_.call(this,a,b,c);
this.A=this.id.replace(/[^a-z0-9-]/gi,"-");this.title=b.title;this.choices=b.choices;this.g=b.hasOwnProperty("old_vote")?b.old_vote:null;this.o=null;if(a=b.signin_url)this.o=z0({target:"current",value:a});this.F=b.hasOwnProperty("xsrf_token")?b.xsrf_token:null},x1=function(a,b,c){f_.call(this,a,b,c);
this.imageUrl=b.image_url;this.displayDomain=b.display_domain;this.showLinkIcon=b.show_link_icon;this.o=b.button_icon_url;this.title=b.title;this.customMessage=b.custom_message;this.url=z0({pause_on_navigation:b.pause_on_navigation,target:b.target||"new",value:b.url});this.g=null;if(a=b.signin_url)this.g=z0({target:"current",value:a});this.F=b.signin_title||null;this.A=b.signin_message||null},y1=function(a,b,c){x1.call(this,a,b,c);
this.offers=[];a=b.offers||[];for(b=0;b<a.length;b++)this.offers.push(new Ooa(a[b]))},Ooa=function(a){this.merchant=g.bd(a.merchant);
this.price=g.bd(a.price)},z1=function(a,b,c){f_.call(this,a,b,c);
this.o=b.image_url;this.videoDuration=b.video_duration||null;this.customMessage=b.custom_message;this.title=b.title;this.metaInfo=b.meta_info;this.isLiveNow=!!b.is_live_now;this.url=z0({pause_on_navigation:b.pause_on_navigation,target:b.target||"new",value:b.url})},A1=function(a,b,c){f_.call(this,a,b,c);
this.F=b.image_url;this.o=b.badge_symbol||"";this.priceText=b.price_text||"";this.title=b.title;this.metaInfo=b.meta_info;this.A=!!b.is_paygated;this.H=!!b.user_has_entitlement;this.url=z0({target:b.target||"new",value:b.url})},Poa=function(a){this.g=a;
this.i={}},Qoa=function(a){var b={};
b=(b["iv-event"]=1,b);NZ(a.g,b,void 0)},E1=function(a,b,c,d){if(b){var e=B1(a,b);
a.i[b]=e["p-time"];e["iv-event"]=e.link||e["l-class"]||e["link-id"]?2:7;b=C1(a,"cta_annotation_shown",e,c);D1(a,e,Roa(b,d))}},F1=function(a,b,c,d,e,f){if(b){var k=B1(a,b);
k["iv-event"]=3;k["i-time"]=a.i[b]||"";d&&g.fc(k,d);b=C1(a,"cta_annotation_clicked",k,e);D1(a,k,b,c,f)}},G1=function(a,b){if(b){var c=B1(a,b);
c["iv-event"]=4;c["i-time"]=a.i[b]||"";var d=C1(a,"cta_annotation_closed",c);D1(a,c,d)}},Roa=function(a,b){return b?(0,g.C)(a,g.Ra(function(c,d){return g.un(d,c)},b)):a},C1=function(a,b,c,d){d=d?g.gb(d):[];
var e=c["a-type"];if(30==e||31==e&&g.Q(g.X(a.g).experiments,"enable_async_click_tracking")){a:{c=c["a-id"];a=a.g.getVideoData();if(a.ku){if((b=a.ku[b])&&g.pv(b)){a=g.Xc("[ANNOTATION_ID]");0<=b.indexOf("[ANNOTATION_ID]")?b=b.replace("[ANNOTATION_ID]",c):0<=b.indexOf(a)&&(b=b.replace(a,c));break a}}else if(a.zn){b=g.Dq(a.zn,{label:b,value:"a_id="+c});break a}b=""}b&&d.push(b)}return d},D1=function(a,b,c,d,e){var f=1,k=-1;
if(d){var l=!1;var m=function(){f--;f||l||(clearTimeout(k),l=!0,d())};
k=setTimeout(function(){l=!0;d()},1E3)}(0,g.A)(c||[],function(n){f++;
g.or(n,m)});
e&&(f++,0!=e&&a.g.sendVideoStatsEngageEvent(e,m));NZ(a.g,b,m)},B1=function(a,b){var c={};
if(b){var d=new g.jn(b);(0,g.A)(d.Id(),function(e){c[e]=escape(d.get(e,""))})}c["p-time"]=a.g.getCurrentTime().toFixed(2);
c.ps=g.X(a.g).playerStyle;return c},H1=function(a,b,c,d,e){e=B1(a,e);
e["iv-event"]=c;b&&(e.ei=b);e["a-id"]||(e["a-id"]="card:drawer");e["a-type"]=51;D1(a,e,d)},I1=function(a,b,c,d){c&&(c=B1(a,c),c["iv-event"]=b,D1(a,c,d))},Soa=function(a,b,c,d,e,f,k){this.g=a;
this.l=b;this.Ab=c;this.videoData=d;this.logger=e;this.Y=f;this.i=k},J1=function(a,b){this.g=a;
this.o=b;this.i=new g.ao},Toa=function(a,b){var c=[];
(0,g.A)(b.choices,function(k){c.push({B:"li",G:b.A+"-"+k.index.toString(),J:[{B:"label",J:[{B:"input",G:"iv-card-poll-choice-input",L:{type:"checkbox",role:"radio",name:b.A+k.index.toString(),value:k.index.toString(),"data-poll-choice-index":k.index.toString()}},{B:"span",G:"iv-card-poll-choice-text",J:[{B:"span",G:"iv-card-poll-choice-percent"},K1(this,"span",void 0,k.desc)]}]},{B:"div",G:"iv-card-poll-result",J:[{B:"div",G:"iv-card-poll-result-bar"}]}]})},a);
var d={B:"ul",L:{role:"radiogroup"},J:c},e={};b.o&&(e["aria-label"]=g.BN("$POLL_TITLE - Sign in to vote.",{POLL_TITLE:b.title}));var f=["iv-card","iv-card-poll"];d=[{B:"div",G:"iv-card-content",J:[K1(a,"h2",e,b.title),{B:"form",J:[{B:"fieldset",J:[d]}]}]}];b.o&&(f.push("iv-card-unavailable"),d.push({B:"div",W:["iv-card-sign-in"],J:[{B:"h2",U:"Want to vote?"},{B:"a",W:["iv-card-sign-in-button","iv-button"],L:{href:A0(b.o)},J:[{B:"span",W:["iv-button-content"],U:"Sign in"}]}]}));f=new g.W({B:"div",
W:f,J:d});d=f.element;L1(b,d);Qna(a.g.g,d,g.Ra(a.u,b),a);(0,g.A)(g.Hd("iv-card-poll-choice-input",d),function(k){this.g.g.ca(k,"focus",g.Ra(this.l,!0));this.g.g.ca(k,"blur",g.Ra(this.l,!1))},a);
b.o&&(d=g.Id("iv-card-sign-in-button",d),a.o(d,b.o,b.id,b.sd,b.l,b.i.click,5));return f},P1=function(a,b,c){var d=["yt-badge",
"standalone-ypc-badge-renderer-icon",b.H?"standalone-ypc-badge-renderer-icon-purchased":"standalone-ypc-badge-renderer-icon-available"],e={};d=b.A&&b.o?{B:"span",W:d,L:e,U:b.o}:"";c={B:"div",W:["iv-card",c],J:[{B:"a",G:"iv-click-target",L:{href:A0(b.url)},J:[M1(b.F,d?{B:"div",G:"iv-card-image-text",J:[d,b.priceText]}:""),{B:"div",G:"iv-card-content",J:[{B:"h2",G:"iv-card-primary-link",U:b.title},N1(a,b)]}]}]};c=new g.W(c);O1(a,c,b);return c},Q1=function(a,b){return b.customMessage?K1(a,"div","iv-card-message",
b.customMessage):""},M1=function(a,b){var c="background-image: url("+a+");",d=[];
b&&d.push(b);return{B:"div",G:"iv-card-image",L:{style:c},J:d}},N1=function(a,b){if(!b.metaInfo||0==b.metaInfo.length)return"";
var c=[];(0,g.A)(b.metaInfo,function(d){c.push(K1(this,"li","",d))},a);
return{B:"ul",G:"iv-card-meta-info",J:c}},K1=function(a,b,c,d){c?g.v(c)?c={"class":c}:g.La(c)&&(c={"class":c.join(" ")}):c={};
c.dir=g.bo(a.i,d);return{B:b,L:c,U:d}},R1=function(a,b){if(!b.customMessage)return"";
var c=["iv-card-action","iv-card-primary-link"],d={};b.o&&(c.push("iv-card-action-icon"),d.style="background-image: url("+b.o+");");d.dir=g.bo(a.i,b.customMessage);var e=[{B:"span",U:b.customMessage}];b.showLinkIcon&&(e.push("\u00a0"),e.push({B:"span",G:"iv-card-link-icon"}));return{B:"div",W:c,L:d,J:e}},L1=function(a,b){var c=0;
(0,g.A)(a.choices,function(m){c+=m.count});
c=c||1;for(var d=0;d<a.choices.length;d++){var e=a.choices[d],f=g.Id(a.A+"-"+e.index.toString(),b);e=e.count/c;null==a.g&&(e=0);g.K(f.getElementsByTagName("label")[0],"iv-card-poll-choice-checked",a.g==d);f.getElementsByTagName("input")[0].checked=a.g==d;var k=Math.floor(100*e).toFixed(0),l=g.Id("iv-card-poll-choice-percent",f);g.ce(l,g.BN("$PERCENT%",{PERCENT:k}));f=g.Id("iv-card-poll-result-bar",f);g.Ch(f,"transform","scaleX("+e.toFixed(2)+")")}g.K(b,"iv-card-poll-voted",null!=a.g);g.K(b,"iv-card-poll-expanded",
null!=a.g&&1<a.choices.length)},O1=function(a,b,c,d,e){c.g&&S1(a,g.Hd("iv-card-sign-in-button",b.element),c,c.g,e);
c.url&&S1(a,g.Hd("iv-click-target",b.element),c,c.url,d)},S1=function(a,b,c,d,e){(0,g.A)(b,function(f){if(e){var k=(0,g.y)(function(l){l.stopPropagation();
l.preventDefault();e();return!1},this);
this.g.g.ca(f,"click",k)}else d&&this.o(f,d,c.id,c.sd,c.l,c.i.click,5)},a)},T1=function(a){var b=0;
-1!=a.indexOf("h")&&(a=a.split("h"),b=3600*a[0],a=a[1]);-1!=a.indexOf("m")&&(a=a.split("m"),b=60*a[0]+b,a=a[1]);-1!=a.indexOf("s")?(a=a.split("s"),b=1*a[0]+b):b=1*a+b;return b},V1=function(a){var b;
(b=a)&&!(b=1<a.length?"/"==a.charAt(0)&&"/"!=a.charAt(1):"/"==a)&&(b=U1(a),b="com"==b[0]&&"youtube"==b[1]||"be"==b[0]&&"youtu"==b[1]);return b?-1==a.indexOf("/redirect?"):!1},U1=function(a){a=a.replace(/^(https?:)?\/\//,"");
a=a.split("/",1);return!a||1>a.length||!a[0]?[]:a[0].toLowerCase().split(".").reverse()},Uoa=function(a){a=A0(a);
if(!a)return null;a=a.replace(/https?:\/\//g,"");var b;(b=!V1(a))||(b=g.Ug(g.Tg(a)[5]||null)||"",b=b.split("/"),b="/"+(1<b.length?b[1]:""),b="/watch"!=b);if(b)return null;b=g.Bq(a);if(!b||!b.v)return null;if(b=b.t)return T1(b);a=a.split("#",2);return!a||2>a.length?null:(a=g.zq(a[1]))&&a.t?T1(a.t):-1},W1=function(a){a=A0(a);
a=a.replace(/https?:\/\//g,"");return V1(a)?(a=g.Bq(a))&&a.v?a.v:null:null},Voa=function(a,b,c){c=c.replace(/\/(u|b)\/[0-9]+/g,"");
var d=/^[0-9]+$/;a&&d.test(a)&&(c="/b/"+a+c);b&&d.test(b)&&(c="/u/"+b+c);return c},X1=function(a,b){return b?b:V1(a)?"current":"new"},Y1=function(a,b){g.G.call(this);
this.Ba=a;this.context=b;this.Us=!1;this.X=0},Woa=function(a){return(0,g.B)()-a.X},Xoa=function(a,b,c,d,e,f){var k=A0(b);
if(k){var l=X1(k,b.target),m=(0,g.y)(function(){b.g&&this.context.Y.pauseVideo();var p=this.context.videoData.Mb||!1,r=g.Bq(k||"");p&&r&&(r.v||r.list)?g.mY(this.context.Y.app,r.v,c,r.list,!1,void 0):g.JL(k||"","current"==l?"_top":void 0,c)},a);
"new"==l&&(m(),m=null);var n={};n.interval=Woa(a);F1(a.context.logger,d,m,n,e,f);V1(k)||(a=g.qt(),d=c.itct,a&&d&&g.dt(a,g.$s(d)))}},a2=function(a,b,c){Y1.call(this,b,c);
var d=this;this.i=a;this.R=null;this.V=this.xa=this.u=this.wa=!1;this.ba=null;this.M=new g.M(g.Ia,c.Ab.fd?4E3:3E3);g.H(this,this.M);this.ka=new g.M(g.Ia);g.H(this,this.ka);this.D=new J1(c,(0,g.y)(this.Ki,this),(0,g.y)(this.Fm,this));this.F=new g.W({B:"div",G:"iv-drawer",L:{id:"iv-drawer"},J:[{B:"div",G:"iv-drawer-header",L:{"aria-role":"heading"},J:[{B:"span",G:"iv-drawer-header-text"},{B:"button",W:["iv-drawer-close-button","ytp-button"],L:{"aria-label":"Hide cards",tabindex:"0"}}]},{B:"div",G:"iv-drawer-content"}]});
g.H(this,this.F);this.A=this.F.element;this.va=new g.nQ(this.F,330);g.H(this,this.va);this.ya=g.Id("iv-drawer-header-text",this.A);this.o=g.Id("iv-drawer-content",this.A);this.l=[];this.na=this.O=this.C=this.Z=this.g=null;this.I=[];this.addCueRange(0,1E3*c.videoData.lengthSeconds,"",function(){d.xa&&Z1(d,"YOUTUBE_DRAWER_AUTO_OPEN")},function(){(d.xa=d.u)&&$1(d)});
this.P=this.H=this.fa=null},apa=function(a,b){var c=b&&b.data&&b.data.card_type;
if(c&&b2[c]){c=new b2[c](b.id,b.data,b.g);if(!a.wa){g.ho(a.ha(),["html5-stop-propagation","iv-drawer-manager"]);g.DK(a.i,a.A,5);Yoa(a);a.O=g.Id("ytp-cards-button",a.i.getRootNode());var d=g.Id("iv-drawer-close-button",a.A);a.na=d;a.wa=!0}c2(a,c.id);var e=Zoa(a,c);if(e){d={Fb:c,Vo:e.element,Hw:!1};var f=$oa(a,d);g.lb(a.l,f,0,d);e.g(a.o,f);a.Fl();c.autoOpen?a.addCueRange(c.startMs,0x8000000000000,c.id,g.Ra(a.oM,d)):(e=1E3*a.context.Y.getCurrentTime(),5E3>e&&e>c.startMs&&a.Zz(d),a.addCueRange(c.startMs,
c.startMs+1,c.id,g.Ra(a.Zz,d)),d2(a))}}},bpa=function(a,b){b.data.autoOpenMs&&a.addCueRange(b.data.autoOpenMs,0x8000000000000,"",function(){Z1(a,"YOUTUBE_DRAWER_AUTO_OPEN")});
b.data.autoCloseMs&&a.addCueRange(b.data.autoCloseMs,0x8000000000000,"",function(){$1(a)});
var c=b.data.headerText;g.ce(a.ya,c);a.O&&a.O.setAttribute("title",c);b.data.eventId&&(a.R=b.data.eventId);a.fa=g.$s(b.data.trackingParams);a.P=g.$s(b.data.closeTrackingParams);a.H=g.$s(b.data.iconTrackingParams)},c2=function(a,b){var c=cpa(a,b);
c&&(c==a.g&&(a.g=null),a.i.removeCueRange(c.Fb.id),g.Yd(c.Vo),g.db(a.l,c),a.Fl(),d2(a))},Z1=function(a,b,c,d){if(!a.u){a.va.show();
a.Z=new g.M(function(){g.J(a.context.Y.getRootNode(),"ytp-iv-drawer-open")},0);
a.Z.start();a.ba=g.cs(a.o,"mousewheel",(0,g.y)(a.eF,a));a.u=!0;a.X=(0,g.B)();H1(a.context.logger,a.R,7,void 0,d&&d.Fb?d.Fb.l:void 0);var e=g.qt();e&&a.fa&&a.P&&d_(e,[a.fa,a.P]);var f={TRIGGER_TYPE:b};(0,g.A)(a.l,function(k){k.Hw||(k.Hw=!0,E1(a.context.logger,k.Fb.l,k.Fb.i.UD,f));e&&d_(e,[k.Fb.D])});
OZ(a.i);c&&(a.C=new g.M(function(){a.ea=a.O;a.na.focus()},330),a.C.start())}},$1=function(a){a.u&&(a.va.hide(),g.ds(a.ba),a.ba=null,g.io(a.context.Y.getRootNode(),"ytp-iv-drawer-open"),a.u=!1,OZ(a.i),a.C&&a.C.stop(),a.C=new g.M(function(){a.ea&&(a.ea.focus(),a.ea=null)},330),a.C.start())},Yoa=function(a){var b=g.Id("iv-drawer-close-button",a.A);
a.context.g.ca(b,"click",a.sC,a);a.context.g.ca(a.o,"touchend",function(){a.M.start()});
a.context.g.ca(a.o,"scroll",a.BC,a);a.context.i.subscribe("onHideControls",function(){a.V=!0});
a.context.i.subscribe("onShowControls",function(){a.V=!1});
a.context.i.subscribe("onVideoAreaChange",function(){a.V=g.go(a.i.getRootNode(),"ytp-autohide")});
a.I.push(g.dq("iv-button-shown",a.mE,a));a.I.push(g.dq("iv-button-hidden",a.lE,a));a.I.push(g.dq("iv-teaser-shown",a.pE,a));a.I.push(g.dq("iv-teaser-hidden",a.oE,a));a.I.push(g.dq("iv-teaser-clicked",a.nE,a))},Zoa=function(a,b){switch(b.type){case "simple":var c=a.D,d=b.displayDomain?{B:"div",
G:"iv-card-image-text",U:b.displayDomain}:"",e=R1(c,b),f=["iv-card"];b.g&&f.push("iv-card-unavailable");d=[{B:"a",G:"iv-click-target",L:{href:A0(b.url)},J:[M1(b.imageUrl,d),{B:"div",G:"iv-card-content",J:[K1(c,"h2",void 0,b.title),e]}]}];b.g&&d.push({B:"div",W:["iv-card-sign-in"],J:[K1(c,"h2",void 0,b.F||""),{B:"p",U:b.A},{B:"a",W:["iv-card-sign-in-button","iv-button"],L:{href:A0(b.g)},J:[K1(c,"span","iv-button-content","Sign in")]}]});f=new g.W({B:"div",W:f,J:d});O1(c,f,b,void 0,void 0);return f;
case "collaborator":return c=a.D,f={B:"div",W:["iv-card","iv-card-channel"],J:[{B:"a",W:["iv-click-target"],L:{href:A0(b.url),"data-ytid":b.channelId},J:[M1(b.o),{B:"div",G:"iv-card-content",J:[Q1(c,b),{B:"h2",G:"iv-card-primary-link",U:b.title},N1(c,b)]}]}]},f=new g.W(f),O1(c,f,b),f;case "episode":return P1(a.D,b,"iv-card-episode");case "movie":return P1(a.D,b,"iv-card-movie");case "playlist":return c=a.D,f={B:"div",W:["iv-card","iv-card-playlist"],J:[{B:"a",G:"iv-click-target",L:{href:A0(b.url)},
J:[M1(b.o,{B:"div",G:"iv-card-image-overlay",J:[{B:"span",G:"iv-card-playlist-video-count",U:b.playlistVideoCount.toString()}]}),{B:"div",G:"iv-card-content",J:[Q1(c,b),K1(c,"h2","iv-card-primary-link",b.title),N1(c,b)]}]}]},f=new g.W(f),O1(c,f,b),f;case "poll":return Toa(a.D,b);case "productListing":c=a.D;e=0!=b.offers.length;f=["iv-card"];d="";var k=R1(c,b);e&&(f.push("iv-card-product-listing"),d="iv-card-primary-link",e=b.offers[0],k=[],e.price&&k.push({B:"div",G:"iv-card-offer-price",U:e.price}),
e.merchant&&k.push({B:"div",G:"iv-card-offer-merchant",U:e.merchant}),k={B:"div",J:k});f={B:"div",W:f,L:{tabindex:"0"},J:[{B:"a",W:["iv-card-image","iv-click-target"],L:{style:"background-image: url("+b.imageUrl+");",href:A0(b.url),"aria-hidden":"true",tabindex:"-1"}},{B:"div",G:"iv-card-content",J:[b.sponsored?{B:"div",G:"iv-card-sponsored",J:["Sponsored",{B:"div",G:"iv-ad-info-container",J:[{B:"div",G:"iv-ad-info",U:"{{adInfo}}"},{B:"div",G:"iv-ad-info-icon-container",J:[{B:"div",G:"iv-ad-info-icon"},
{B:"div",G:"iv-ad-info-callout"}]}]}]}:"",{B:"a",G:"iv-click-target",L:{href:A0(b.url)},J:[K1(c,"h2",d,b.title),k]}]}]};f=new g.W(f);d=g.Td("span");g.ce(d,"You are seeing this product because we think it is relevant to the video. Google may be compensated by the merchant.");f.kb(d,"adInfo");O1(c,f,b);return f;case "video":return c=a.D,f=b.isLiveNow?{B:"span",W:["yt-badge","yt-badge-live"],U:"LIVE NOW"}:"",f={B:"div",W:["iv-card","iv-card-video"],J:[{B:"a",G:"iv-click-target",L:{href:A0(b.url)},J:[M1(b.o,
b.videoDuration?{B:"span",G:"iv-card-video-duration",U:b.videoDuration}:""),{B:"div",G:"iv-card-content",J:[Q1(c,b),K1(c,"h2","iv-card-primary-link",b.title),N1(c,b),f]}]}]},f=new g.W(f),O1(c,f,b),f}return null},$oa=function(a,b){if(0==a.l.length)return 0;
var c=g.Za(a.l,function(d){return b.Fb.startMs>d.Fb.startMs||b.Fb.startMs==d.Fb.startMs&&b.Fb.timestamp>=d.Fb.timestamp?!0:!1});
return-1==c?0:c+1},dpa=function(a){return a.g?"productListing"==a.g.Fb.type:(0,g.mj)(a.l,function(b){return"productListing"==b.Fb.type})},d2=function(a){g.K(a.i.getRootNode(),"ytp-cards-shopping-active",dpa(a))},e2=function(a,b){if(a.F.Fa()){var c=new ZZ([0,
a.o.scrollTop],[0,b.Vo.offsetTop],600,Pna);a.context.l.ca(c,"animate",function(d){a.o.scrollTop=d.y});
a.context.l.ca(c,"finish",function(d){a.o.scrollTop=d.y});
c.play()}else g.gD(a.F,!0),a.o.scrollTop=b.Vo.offsetTop,g.gD(a.F,!1)},f2=function(a){return a.g&&a.g.Fb?a.g.Fb:a.l[0]&&a.l[0].Fb?a.l[0].Fb:null},cpa=function(a,b){return g.Ya(a.l,function(c){return c.Fb.id==b})},g2=function(a,b,c){Y1.call(this,a,b);
this.annotation=c;this.isActive=!1},epa=function(a){var b=a.annotation.data;
"start_ms"in b&&"end_ms"in b&&a.addCueRange(a.annotation.data.start_ms,a.annotation.data.end_ms,a.annotation.id,function(){a.show()},function(){a.hide()})},h2=function(a,b,c){g2.call(this,a,b,c);
this.i=null;this.D=!1;this.l=null;this.o=!1;this.u=0;this.g=this.C=this.A=null},i2=function(a,b,c){g2.call(this,a,b,c);
this.F=this.u=this.H=!1;this.C=5E3;this.o=null;this.D=g.Sd("DIV","iv-promo-contents");this.i=this.l=this.g=null;this.A=new g.M(function(){this.g.setAttribute("aria-hidden",!0);g.Wh(this.l,!1);g.Wh(this.i,!0)},700,this);
g.H(this,this.A)},fpa=function(a){var b=a.annotation.data;
if("cta"==a.annotation.style)var c=6;else if("video"==a.annotation.style||"playlist"==a.annotation.style)c=7;a.C=b.collapse_delay_ms||a.C;var d=["iv-promo","iv-promo-inactive"];a.ha().setAttribute("aria-hidden",!0);a.ha().setAttribute("aria-label","Promotion");a.ha().tabIndex=0;var e=a.annotation.Gb(),f=b.image_url;if(f){var k=g.Sd("DIV",["iv-promo-img","iv-click-target"]);f=g.Sd("IMG",{src:f,"aria-hidden":"true"});k.appendChild(f);b.video_duration&&!b.is_live?(f=g.Sd("SPAN","iv-promo-video-duration",
b.video_duration),k.appendChild(f)):b.playlist_length&&(f=g.Sd("SPAN","iv-promo-playlist-length",b.playlist_length.toString()),k.appendChild(f));e&&a.Ki(k,e,a.annotation.id,b.session_data,a.annotation.g,void 0,c)}e?(f=g.Sd("A","iv-promo-txt"),g.Uc(f,A0(e)),a.g=f):a.g=g.Sd("DIV","iv-promo-txt");switch(a.annotation.style){case "cta":case "website":var l=g.Sd("P",null,g.Sd("STRONG",null,b.text_line_1));var m=g.Sd("P",null,g.Sd("SPAN","iv-promo-link",b.text_line_2));if(f=b.text_line_3){d.push("iv-promo-website-card-cta-redesign");
g.Q(a.context.Ab.experiments,"web_action_cta_larger_ui")&&d.push("iv-promo-website-card-cta-larger-ui");var n=g.Sd("BUTTON",["iv-promo-round-expand-icon","ytp-button"]);f=g.Sd("BUTTON",["iv-button","iv-promo-button"],g.Sd("SPAN","iv-button-content",f));var p=g.Sd("DIV","iv-promo-button-container");p.appendChild(f);e&&a.Ki(a.ha(),e,a.annotation.id,b.session_data,a.annotation.g,void 0,c)}g.J(a.g,"iv-click-target");e&&a.Ki(a.g,e,a.annotation.id,b.session_data,a.annotation.g,void 0,c);break;case "playlist":case "video":l=
g.Sd("P",null,g.Sd("SPAN",null,b.text_line_1)),m=g.Sd("P",null,g.Sd("STRONG",null,b.text_line_2)),b.is_live&&(l=m,m=g.Sd("SPAN",["yt-badge","iv-promo-badge-live"],"LIVE NOW")),g.J(a.g,"iv-click-target"),e&&a.Ki(a.g,e,a.annotation.id,b.session_data,a.annotation.g,void 0,c),d.push("iv-promo-video")}l&&a.g.appendChild(l);m&&a.g.appendChild(m);a.D.appendChild(a.g);p&&a.D.appendChild(p);c=g.Sd("DIV","iv-promo-actions");a.i=g.Sd("BUTTON",["iv-promo-expand","ytp-button"]);a.i.title="Expand";a.context.g.ca(a.i,
"click",g.Ra(a.Sp,5E3),a);c.appendChild(a.i);g.Wh(a.i,!1);a.context.g.ca(a.ha(),"mouseover",a.uD,a);a.context.g.ca(a.ha(),"mouseout",a.tD,a);a.context.g.ca(a.ha(),"touchend",g.Ra(a.Sp,5E3),a);a.l=g.Sd("BUTTON",["iv-promo-close","ytp-button"]);a.l.title="Close";a.context.g.ca(a.l,"click","cta"==a.annotation.style&&b.text_line_3?a.mD:a.lD,a);c.appendChild(a.l);g.ho(a.ha(),d);k&&(a.ha().appendChild(k),n&&k.appendChild(n));a.ha().appendChild(a.D);a.ha().appendChild(c)},j2=function(a){a.u||a.F||a.o||(g.J(a.ha(),
"iv-promo-collapsed"),a.u=!0,a.A.start())},k2=function(a){a.A.stop();
a.u&&(g.jo(a.ha(),["iv-promo-collapsed","iv-promo-collapsed-no-delay"]),a.u=!1,a.g&&a.g.removeAttribute("aria-hidden"),g.Wh(a.i,!1),g.Wh(a.l,!0))},m2=function(a,b){a.o||(a.o=g.Jg(function(){l2(this);
j2(this)},b,a))},l2=function(a){a.o&&(g.w.clearTimeout(a.o),a.o=null)},n2=function(a){g.RK.call(this,a);
this.I=!1;this.H=0;this.i={};this.P={};this.D=new Poa(a);this.A=new g.Ls(this);g.H(this,this.A);this.C=this.l=null;this.A.K(this.player,"onVideoAreaChange",(0,g.y)(this.N,this,"onVideoAreaChange"));this.A.K(this.player,"onHideControls",(0,g.y)(this.N,this,"onHideControls"));this.A.K(this.player,"onShowControls",(0,g.y)(this.N,this,"onShowControls"));this.A.K(this.player,"resize",(0,g.y)(this.N,this,"resize"));this.A.K(this.player,"presentingplayerstatechange",(0,g.y)(this.N,this,"presentingplayerstatechange"));
this.subscribe("onHideControls",this.VI,this);this.subscribe("onShowControls",this.RK,this);this.subscribe("presentingplayerstatechange",this.aK,this);this.subscribe("resize",this.Gr,this);this.subscribe("G",this.ME,this);this.subscribe("F",this.zg,this);this.subscribe("D",this.SH,this);this.subscribe("E",this.uI,this);g.X(this.player).I.subscribe("vast_info_card_add",this.Yy,this);this.R=new g.Ls(this);g.H(this,this.R);this.R.K(this.player,g.pE("annotations_module"),this.KE);this.R.K(this.player,
"crx_annotations_module",this.LE);this.O=g.Sd("DIV",["video-legacy-annotations","html5-stop-propagation"]);this.V=g.Sd("DIV","video-custom-annotations");this.u=new g.W({B:"div",W:["ytp-player-content","ytp-iv-player-content"]});g.H(this,this.u);g.DK(this.player,this.u.element,4);this.u.hide();this.o=new g.W({B:"div",W:["ytp-iv-video-content"]});g.H(this,this.o);g.Vd(this.o.element,g.Sd("DIV","video-annotations",this.O,this.V));this.F=this.g=null;this.M=[];gpa(this)&&this.load();var b=g.Td("STYLE");
(document.getElementsByTagName("HEAD")[0]||document.body).appendChild(b);g.rf(this,function(){g.Yd(b)});
if(a=b.sheet)a.insertRule(".iv-promo .iv-promo-contents .iv-promo-txt .iv-promo-link:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUBAMAAAB/pwA+AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAHlBMVEVMaXH////////////////////////////////////Z6AnKAAAACXRSTlMA+/A2IuI1mJIldm0CAAAAAWJLR0QB/wIt3gAAAEVJREFUCNdjYGCYCQUMBJlACOIzIDElIcyZkwxgojOVWWDMSQauMKYySySUOSnBdSaUOZ0lEsac2YqwYiZ+JhwgM7E5HACgzVCI/YJ59AAAAABJRU5ErkJggg==) no-repeat center;background-size:10px;width:10px;height:10px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-close:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAkAAAAJBAMAAAASvxsjAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAVaQDpaimqQbl5rjXUFUAAAABYktHRAH/Ai3eAAAAPUlEQVQI12MQMmAwEmDwDmaOTmAw39663YCBuXp2MQMDQ+fOBgYG5ujVwQwMptvbgeLaxczVCQwiBgxmAgBkXg1FN5iwiAAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-expand:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAJBAMAAADnQZCTAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXHMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMz////eMKB4AAAAC3RSTlMAOpE7k5Uvj5kpfRaQSaQAAAABYktHRAsf18TAAAAAHklEQVQI12MQYGBQZmBwTWCo0GSo6AKRQDZQRIABADXXA/UkIpvtAAAAAElFTkSuQmCC) no-repeat center;background-size:4px 9px;width:4px;height:9px}",0),a.insertRule(".iv-promo-website-card-cta-redesign .iv-promo-round-expand-icon:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAQAAAD9CzEMAAAAAmJLR0QA/4ePzL8AAAAJcEhZcwAACxMAAAsTAQCanBgAAAAHdElNRQfgCgUUEztsNfqrAAAAXklEQVRYw+3Uuw2AQAwEUUNXfBpDIvBRMhQwJJAScNrA0r4CdiQHjjAzK4NGKucPAFmCnZcmwcTphBNO9CTGH4VB+/Zm6YlYis9fhedXz38FNvFriCCl808iw8ysrBu65gCeuV/CfgAAAABJRU5ErkJggg==) no-repeat center;background-size:18px 18px;width:18px;height:18px}",
0),a.insertRule(".iv-card-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAGFBMVEVMaXG7u7u7u7u7u7u7u7u7u7u7u7v///+WKTAlAAAABnRSTlMAFdQWbGj9GiOuAAAAAWJLR0QHFmGI6wAAAEhJREFUCNdjYACBNCBgQGMxMKrBWEJJaRAJRjVlKEsoSQDIAqtSZICwgEIQFkgIZBRECMxiBqsCsVjAqsCygQwwFgMeFgQgswBg2xjLrfC4mgAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",0),a.insertRule(".iv-card-playlist-video-count:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAH/Ai3eAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0),a.insertRule(".iv-drawer-close-button:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAMAgMAAAArG7R0AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACVBMVEVMaXH////////OZTV/AAAAAnRSTlMAoKBFbtAAAAABYktHRAH/Ai3eAAAAKUlEQVQI12MIYGBlSGGQBMIUBjbHCQyM0xwYGDIZwBjEBomB5EBqgGoBolQGzYuy51cAAAAASUVORK5CYII=) no-repeat center;background-size:12px;width:12px;height:12px}",0),a.insertRule(".iv-ad-info-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAsAAAALCAMAAACecocUAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAVFBMVEVMaXGUlJSYmJiZmZmYmJiXl5eZmZmZmZmWlpaVlZWOjo6ZmZmSkpKXl5eYmJiYmJiZmZmZmZmZmZmZmZmYmJiJiYmXl5eZmZmYmJiWlpaZmZn///+81lbeAAAAGnRSTlMAE5DM80DliTMMEjccWIM5p1UjaTQNgB5cLlr5mgUAAAABYktHRBsCYNSkAAAAVElEQVQI102NRw7AIBADhw7ppIf/PzQLJ/ZgWSNrFlDaWKMVcs6HmGLwTqjEME6CFDrAXBYIGhNh3TJEg02wHydctvFc7sbrvnXZV8/zfs3T+7u/P7CrAso35YfPAAAAAElFTkSuQmCC) no-repeat center;background-size:11px;width:11px;height:11px}",
0),a.insertRule(".annotation-close-button {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAALVBMVEVMaXEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/Pz9aWloBAQGZmZlbW1v///+X9wUzAAAACHRSTlMANprf+g6lyRmB9hUAAAABYktHRA5vvTBPAAAAWUlEQVQI12NgYBAycVZkAIKwDiBIZWBgrQAx2gMY2DrAIIFBomPWju6VHY0MGh1rbu891dHEYNGx9+yd2x3NDB4d3XfO7uhoQTDgUnDFcO1wA+FWwC2FOQMAdKg6tUSAFEAAAAAASUVORK5CYII=) no-repeat center}",0),a.insertRule(".annotation-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACIAAAAiCAMAAAANmfvwAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAUVBMVEVMaXH////////////////////////////////////////////////////////////////////////////////////////////////////////JzkR1AAAAGnRSTlMAfXf+c3xsdGdv/GJoXPtXXflSVk5L7DBH9VeFfsQAAAABYktHRAH/Ai3eAAAAgElEQVQ4y93SSQ6AIAwFULSOOOJs739Qf9SF0VA2uNCu+psHaQJK7cVCqY+Rg92PXA++Q84KnCR03UIRJrFEKMEgZYFQhpyzQHSBWJJAdIVUENtJ3SC0mu3EdOh7zXZiBrRdzQLJ0Y1GfOlpVstD3HaZktX9X/gvRCxvxL6FR7IBS1RTM5xIpLoAAAAASUVORK5CYII=) no-repeat center}",
0)},o2=function(a){switch(a){case "annotation-editor":case "live-dashboard":return!0}return!1},gpa=function(a){var b=g.X(a.player);
a=a.player.getVideoData();return 1==(b.Uf||a.Uf)&&!a.VA||null!==b.I.get(a.videoId)},p2=function(a,b,c){a.I=!0;
a.C=g.Uq(b,c)},q2=function(a,b){for(var c={},d=0;d<b.attributes.length;d++){var e=b.attributes[d];
c[e.name]=e.nodeValue}for(d=0;d<b.childNodes.length;d++)if(e=b.childNodes[d],e.tagName){if(c[e.tagName])var f=c[e.tagName];else if("data"==e.tagName){0<e.childNodes.length&&(f=e.childNodes[0].nodeValue,c[e.tagName]="string"==typeof f?f.trim():f);continue}else f=[],c[e.tagName]=f;e&&"TEXT"==e.tagName?1==e.childNodes.length&&3==e.childNodes[0].nodeType?f.push(e.childNodes[0].nodeValue):f.push(""):e&&f.push(q2(a,e))}return c},r2=function(a,b,c){return!(a.loaded&&a.H==b&&a.player.getVideoData().videoId==
c)},ipa=function(a,b){var c=hpa(a,b);
if(!c&&"marker"!=b.type)return null;S0(b,function(e){e=(0,g.y)(this.pL,this,b.id,e);this.subscribe("ivTrigger:"+b.id,e)},a);
var d=new r1(a.va,b,c);g.H(d,c);return d},jpa=function(a,b){var c=g.Sd("DIV",["annotation",
"annotation-type-custom"]);g.Wh(c,!1);var d=null;switch(b.type){case "branding":if(g.X(a.player).Hh)break;a.u.element.appendChild(c);d=new h2(c,s2(a),b);break;case "promotion":g.DK(a.player,c,4),d=new i2(c,s2(a),b)}d&&d.Qn();return d},kpa=function(a){var b=a.player.getVideoData();
if(b.Gd){var c=g.X(a.player),d=c.I.get(b.videoId);if(d){var e={format:"XML",Ec:{},method:"POST",withCredentials:!0};"gaming"==c.playerStyle&&(e.Ec.gaming="1");e.Yc=(0,g.y)(function(f,k,l){r2(this,f,k)||(f=g.Oq(l)&&l.responseXML?l.responseXML:null)&&t2(this,f)},a,a.H,b.videoId);
g.rq()&&(e.Yc=u2(a,e.Yc));e.qb={ic_only:"1"};v2(e,d);a.I=!0;g.Uq(b.Gd,e)}}},v2=function(a,b){a.method="POST";
a.qb=a.qb||{};b.Kl&&(a.qb.ic_coll=b.Kl);b.Ll&&(a.qb.ic_xml=b.Ll);b.Is&&(a.qb.ic_track=b.Is)},lpa=function(a){var b=new g.W({B:"div"});
g.Wh(b.element,!1);var c=new a2(a.player,b.element,s2(a));g.H(c,b);b.g(a.u.element);c.Qn();return c},s2=function(a){if(!a.F){var b=new c_(a);
g.H(a,b);var c=new g.rn(a);g.H(a,c);a.F=new Soa(b,c,g.X(a.player),a.player.getVideoData(),a.D,a.player,a.va)}return a.F},t2=function(a,b){var c=!1;
mpa(b);for(var d=b.getElementsByTagName("annotation"),e=0;e<d.length;e++){var f=q2(a,d[e]),k=null;try{k=Aoa(f)}catch(l){}if(k){a:{switch(k.type){case "branding":case "promotion":f=!0;break a}f=!1}if(f){if(f=jpa(a,k))g.H(a,f),a.P[k.id]=f}else if("card"==k.type||"drawer"==k.type)a.g||(a.g=lpa(a),g.H(a,a.g)),"card"==k.type?apa(a.g,k):bpa(a.g,k),c=!0;else if(f=ipa(a,k))g.H(a,f),a.i[k.id]=f}}c&&(OZ(a.player),a.Gr());g.Lb(a.i,function(l){if(l.view){var m=l.annotation;(l=l.view)&&m.segment&&m.segment.i&&
(m=this.i[m.segment.i])&&(l.O=m.annotation)}},a)},mpa=function(a){if((a=a.getElementsByTagName("annotations"))&&!(1>a.length)&&(a=a[0].getAttribute("itct"))){var b=g.qt();
if(b){var c=g.pt();c&&g.bt(b,c,[g.$s(a)])}}},npa=function(a,b,c,d){d?w2(a,b,c):x2(a,b,c)},x2=function(a,b,c){if(b=a.i[b])t1(b),c&&c.i?(a=(0,g.y)(a.iw,a,b),b.g=new g.M(a,2E3),b.g.start()):a.iw(b)},w2=function(a,b,c){if(b=a.i[b])t1(b),c&&c.o?(a=(0,g.y)(a.kA,a,b),b.g=new g.M(a,2E3),b.g.start()):a.kA(b)},y2=function(a,b){var c=a.player.getVideoData();
if(!c.zl)return!1;var d=A0(b);if(!d)return!1;d=d.replace(/https?:\/\//g,"");if(!V1(d))return!1;d=g.Bq(d);return d.list||d.p?!1:(d=W1(b))?c.videoId==d?!0:"new"!=b.target&&g.X(a.player).i?!0:!1:!1},hpa=function(a,b){if(opa(b)){var c=b.u||Q0(b,function(d){return"click"==d||"rollOut"==d||"rollOut"==d});
return new k1(b,(0,g.y)(a.O.appendChild,a.O),a.player,a.va,c)}return null},opa=function(a){if("highlight"==a.type||"widget"==a.type)return!0;
if("text"==a.type)for(var b in P0)if(a.style==P0[b])return!0;return!1},z2=function(a,b,c,d){a.N(W0(b,d),c,d)},u2=function(a,b){return(0,g.y)(function(){if(!this.da()){var c=Array.prototype.slice.call(arguments,0);
c.unshift(b);b=g.Ra.apply(window,c);this.M.push(g.pq(b))}},a)};
g.jK.prototype.Hi=g.da(14,function(a,b){var c=g.kK(this).l;c&&c.Hi(a,b)});
g.Ao.prototype.Qp=g.da(0,function(){this.i=this.M.createElement("DIV")});
var Ina=/[^\d]+$/,Jna={cm:1,"in":1,mm:1,pc:1,pt:1},Kna={em:1,ex:1},TZ={},UZ=null;g.Ta(YZ,g.uf);g.Ta(ZZ,g.lo);g.h=ZZ.prototype;g.h.getDuration=function(){return this.duration};
g.h.play=function(a){if(a||0==this.g)this.progress=0,this.coords=this.i;else if(1==this.g)return!1;VZ(this);this.startTime=a=(0,g.B)();-1==this.g&&(this.startTime-=this.duration*this.progress);this.endTime=this.startTime+this.duration;this.A=this.startTime;this.progress||this.o();this.Yd("play");-1==this.g&&this.Yd("resume");this.g=1;var b=g.Qa(this);b in TZ||(TZ[b]=this);WZ();XZ(this,a);return!0};
g.h.stop=function(a){VZ(this);this.g=0;a&&(this.progress=1);$Z(this,this.progress);this.Yd("stop");this.l()};
g.h.pause=function(){1==this.g&&(VZ(this),this.g=-1,this.Yd("pause"))};
g.h.T=function(){0==this.g||this.stop(!1);this.Yd("destroy");ZZ.Xa.T.call(this)};
g.h.destroy=function(){this.dispose()};
g.h.yr=function(){this.Yd("animate")};
g.h.Yd=function(a){this.dispatchEvent(new YZ(a,this))};
g.Ta(a_,ZZ);a_.prototype.u=g.Ia;a_.prototype.yr=function(){this.u();a_.Xa.yr.call(this)};
a_.prototype.l=function(){this.u();a_.Xa.l.call(this)};
a_.prototype.o=function(){this.u();a_.Xa.o.call(this)};
g.Ta(b_,a_);b_.prototype.u=function(){this.element.style.left=Math.round(this.coords[0])+"px";this.element.style.top=Math.round(this.coords[1])+"px"};
g.t(c_,g.G);c_.prototype.ca=function(a,b,c,d){c=(0,g.y)(c,d||this.i);a=g.cs(a,b,c);this.g.push(a);return a};
c_.prototype.Gm=function(a,b,c,d){c=(0,g.y)(c,d||this.i);a=g.ms(a,b,c);this.g.push(a);return a};
c_.prototype.La=function(a){g.ds(a);g.db(this.g,a)};
c_.prototype.T=function(){g.ds(this.g);this.g.length=0;g.G.prototype.T.call(this)};g.Ta(g_,g.Uf);g.h=g_.prototype;g.h.Lp=null;g.h.Mj=null;g.h.ha=function(){return this.Mj};
g.h.addEventListener=function(a,b,c,d){g.Ef(this.Mj,a,b,c,d)};
g.h.removeEventListener=function(a,b,c,d){g.Mf(this.Mj,a,b,c,d)};
g.h.T=function(){g_.Xa.T.call(this);var a=this.Mj;if(a)if(g.xf(a))a.me&&g.Bf(a.me);else if(a=g.Hf(a)){var b=0,c;for(c in a.listeners)for(var d=a.listeners[c].concat(),e=0;e<d.length;++e)g.Nf(d[e])&&++b}};g.Ta(l_,g_);l_.prototype.fill=null;g.Ta(n_,g_);o_.prototype.Ee=null;o_.prototype.Ad=null;o_.prototype.Rk=!0;var Sna=[2,2,6,6,0];g.h=o_.prototype;g.h.clear=function(){this.Ta.length=0;this.Ca.length=0;this.Ud.length=0;delete this.Ee;delete this.Ad;delete this.Rk;return this};
g.h.moveTo=function(a,b){0==g.Wa(this.Ta)?this.Ud.length-=2:(this.Ta.push(0),this.Ca.push(1));this.Ud.push(a,b);this.Ad=this.Ee=[a,b];return this};
g.h.dc=function(a){var b=g.Wa(this.Ta);if(null==b)throw Error("Path cannot start with lineTo");1!=b&&(this.Ta.push(1),this.Ca.push(0));for(b=0;b<arguments.length;b+=2){var c=arguments[b],d=arguments[b+1];this.Ud.push(c,d)}this.Ca[this.Ca.length-1]+=b/2;this.Ad=[c,d]};
g.h.close=function(){var a=g.Wa(this.Ta);if(null==a)throw Error("Path cannot start with close");4!=a&&(this.Ta.push(4),this.Ca.push(1),this.Ad=this.Ee);return this};
g.h.clone=function(){var a=new this.constructor;a.Ta=this.Ta.concat();a.Ca=this.Ca.concat();a.Ud=this.Ud.concat();a.Ee=this.Ee&&this.Ee.concat();a.Ad=this.Ad&&this.Ad.concat();a.Rk=this.Rk;return a};
g.h.transform=function(a){if(!this.Rk)throw Error("Non-simple path");a.transform(this.Ud,0,this.Ud,0,this.Ud.length/2);this.Ee&&a.transform(this.Ee,0,this.Ee,0,1);this.Ad&&this.Ee!=this.Ad&&a.transform(this.Ad,0,this.Ad,0,1);return this};
g.h.isEmpty=function(){return 0==this.Ta.length};g.Ta(q_,l_);g.Ta(s_,g.Ao);s_.prototype.o=null;s_.prototype.Cj=function(){return this.bh?g.Vh(this.ha()):g.Ga(this.width)&&g.Ga(this.height)?new g.xd(this.width,this.height):null};
s_.prototype.resume=function(){};g.Ta(i_,m_);g.Ta(h_,m_);g.Ta(t_,n_);t_.prototype.clear=function(){g.Wd(this.ha())};
t_.prototype.setSize=function(a,b){var c=this.ha(),d={width:a,height:b},e;for(e in d)c.setAttribute(e,d[e])};
g.Ta(u_,q_);var x_;g.Ta(v_,s_);var Vna=0;g.h=v_.prototype;g.h.Qp=function(){var a=j_(this,"svg",{width:this.width,height:this.height,overflow:"hidden"}),b=j_(this,"g");this.C=j_(this,"defs");this.o=new t_(b,this);a.appendChild(this.C);a.appendChild(b);this.i=a;this.l&&(this.ha().setAttribute("preserveAspectRatio","none"),this.O?this.LA():this.ha().setAttribute("viewBox","0 0 "+(this.l?this.l+" "+this.I:"")))};
g.h.LA=function(){if(this.bh){var a=this.Cj();0==a.width?this.ha().style.visibility="hidden":(this.ha().style.visibility="",this.o.ha().setAttribute("transform","scale("+a.width/this.l+" "+a.height/this.I+") translate(0 0)"))}};
g.h.setSize=function(a,b){g.Uh(this.ha(),a,b)};
g.h.Cj=function(){if(!g.Eh)return this.bh?g.Vh(this.ha()):v_.Xa.Cj.call(this);var a=this.width,b=this.height,c=g.v(a)&&-1!=a.indexOf("%"),d=g.v(b)&&-1!=b.indexOf("%");if(!this.bh&&(c||d))return null;if(c){var e=this.ha().parentNode;var f=g.Vh(e);a=parseFloat(a)*f.width/100}d&&(e=e||this.ha().parentNode,f=f||g.Vh(e),b=parseFloat(b)*f.height/100);return new g.xd(a,b)};
g.h.clear=function(){this.o.clear();g.Wd(this.C);this.g={}};
g.h.rj=function(){v_.Xa.rj.call(this);this.O&&this.P.La(Wna(),"tick",this.LA)};
g.h.T=function(){delete this.g;delete this.C;delete this.o;this.P.dispose();delete this.P;v_.Xa.T.call(this)};g.t(z_,g.RK);g.h=z_.prototype;
g.h.load=function(){g.RK.prototype.load.call(this);if(!B_(g.X(this.player).playerStyle)){var a=g.cC(this.player.getVideoData());if(a)a=y_(a,A_(this)),C_(this,a);else{var b=this.player.getVideoData();a=b.videoId;this.o&&this.o.abort();a={method:"POST",Yc:(0,g.y)(this.LI,this,a),Ec:{v:a},withCredentials:!0};"gaming"==g.X(this.player).playerStyle&&(a.Ec.gaming="1");this.P&&(a.Ec.ptype="embedded");var c=this.player.getVideoData().cv;c&&(a.qb={ad_tracking:c});if(b=g.bC(b))if(b=g.Dc(b),b=g.Ac(b))this.o=
g.Uq(b,a)}}};
g.h.unload=function(){C_(this,null);this.o&&(this.o.abort(),this.o=null);g.RK.prototype.unload.call(this)};
g.h.Zb=function(a,b){if(!B_(g.X(this.player).playerStyle))return null;if("loadCustomEndscreenRenderer"==a){var c=y_(b,"new");C_(this,c);return!0}return null};
g.h.getOptions=function(){return B_(g.X(this.player).playerStyle)?["loadCustomEndscreenRenderer"]:[]};
g.h.LI=function(a,b){var c=this.o=null;if(200==b.status){var d=b.responseText;")]}"==d.substring(0,3)&&(d=d.substring(3),c=JSON.parse(d),c=y_(c,A_(this)))}C_(this,c)};
g.h.ib=function(){if(this.i&&this.i.elements){var a=this.player.getVideoContentRect();if(a&&0!=a.width&&0!=a.height){var b=this.player.getPlayerSize();if(b&&0!=b.width&&0!=b.height){var c=a.width/a.height;var d=0;for(var e=-1,f=0;f<A2.length;f++){var k=Math.abs(b.width-A2[f]);if(-1==e||d>=k)e=f,d=k}d=B2[e];this.l&&g.Ch(this.l.element,"outline-width",Math.max(b.width,b.height)+"px");for(b=0;b<this.i.elements.length;++b)if(f=this.i.elements[b].id,e=this.g[f],k=this.C[f],e&&k){var l=k.width*c/k.aspectRatio;
f=Math.round(l*a.height);var m=a.left+Math.round(k.left*a.width),n=a.top+Math.round(k.top*a.height);g.Uh(e.element,Math.round(k.width*a.width),f);g.Kh(e.element,m,n);g.jo(e.element,ppa);m=k.left+k.width/2;k=k.top+l/2;g.J(e.element,.5>=m&&.5>=k?"ytp-ce-top-left-quad":.5<m&&.5>=k?"ytp-ce-top-right-quad":.5>=m&&.5<k?"ytp-ce-bottom-left-quad":"ytp-ce-bottom-right-quad");g.jo(e.element,B2);g.J(e.element,d);(e=g.Gd(document,"div","ytp-ce-expanding-overlay-body",e.element)[0])&&g.Ch(e,"height",f+"px")}}}}};
g.h.OE=function(a){if(this.i)if("ytp-ce-in-endscreen"==a.getId())this.H=!1,this.i.skip&&1==this.player.getPlayerState()?(g.sK(this.player,!0),this.player.seekTo(Infinity),this.H=!0):(o0(this,this.i.impressionUrls),(a=g.qt())&&this.i.visualElement&&g.ct(a,this.i.visualElement));else if(!this.H){a=a.getId().substring(15);var b=this.g[a],c=this.C[a];g.J(b.element,"ytp-ce-element-show");b.element.removeAttribute("aria-hidden");b=this.player.getRootNode();g.J(b,"ytp-ce-shown");o0(this,c.impressionUrls);
(b=g.qt())&&g.ct(b,c.visualElement);g.X(this.player).sb&&this.player.la("endscreenelementshown",a)}};
g.h.PE=function(a){if("ytp-ce-in-endscreen"!=a.getId()&&!this.H){a=a.getId().substring(15);var b=this.g[a];g.io(b.element,"ytp-ce-element-show");b.element.setAttribute("aria-hidden",!0);b=this.player.getRootNode();g.io(b,"ytp-ce-shown");g.X(this.player).sb&&this.player.la("endscreenelementhidden",a)}};
g.h.EL=function(a){var b=this;a.target===window&&(new g.M(function(){for(var c in b.g)g.jo(b.g[c].element,["ytp-ce-force-expand","ytp-ce-element-hover","ytp-ce-element-shadow-show"])},0)).start()};
g.h.Ay=function(a,b){if(a.targetUrl&&(!b||"keypress"!=b.type||13==b.keyCode)){for(var c=b.target;c&&!g.go(c,"ytp-ce-element");){g.go(c,"subscribe-label")&&p0(this,a);if(g.go(c,"ytp-ce-channel-subscribe"))return;c=g.ae(c)}if(!c||g.go(c,"ytp-ce-element-hover")){b.preventDefault();b.stopPropagation();if(c=this.g[a.id])this.Fr(c,a),c.element.blur();b.ctrlKey||b.metaKey||"new"==a.Wn?(p0(this,a),this.Tz(),this.player.pauseVideo(),c=g.Dc(l0(this,a.targetUrl)),c=g.Ac(c),g.JL(c,void 0,a.sd)):(c=this.player.getVideoData().Mb,
c=(0,g.y)(this.vM,this,c,l0(this,a.targetUrl),a.sd),c=(0,g.y)(this.Tz,this,c),p0(this,a,c))}}};
g.h.vM=function(a,b,c){var d=g.Bq(b);a&&d&&(d.v||d.list)?g.mY(this.player.app,d.v,c,d.list,!1,void 0):g.IL(b,c)};
g.h.Mq=function(a,b){g.go(a.element,"ytp-ce-element-hover")||("VIDEO"==b.type||"PLAYLIST"==b.type?g.J(a.element,"ytp-ce-element-hover"):g.X(this.player).g?(new g.M(function(){g.J(a.element,"ytp-ce-element-hover")},200)).start():g.J(a.element,"ytp-ce-element-hover"),o0(this,b.SD),n0(this,b.id,!0))};
g.h.Fr=function(a,b){g.io(a.element,"ytp-ce-element-hover");g.io(a.element,"ytp-ce-force-expand");n0(this,b.id,!1)};
g.h.Tz=function(a){this.player.sendVideoStatsEngageEvent(17,a)};
var A2=[346,426,470,506,570,640,853,1280,1920],B2="ytp-ce-size-346 ytp-ce-size-426 ytp-ce-size-470 ytp-ce-size-506 ytp-ce-size-570 ytp-ce-size-640 ytp-ce-size-853 ytp-ce-size-1280 ytp-ce-size-1920".split(" "),ppa=["ytp-ce-top-left-quad","ytp-ce-top-right-quad","ytp-ce-bottom-left-quad","ytp-ce-bottom-right-quad"];var goa={WN:"current",eP:"new"};var ioa={CLOSE:"close",iP:"openUrl",UB:"subscribe"},joa={RN:"click",CLOSE:"close",zO:"hidden",IP:"rollOut",NB:"rollOver",PB:"shown"};var loa={nQ:"xx",oQ:"xy",pQ:"yx",qQ:"yy"};g.t(K0,D0);var qoa={iB:"anchored",EP:"rect",LP:"shapeless"};var uoa={CLOSED:"closed",rP:"playerControlShow",NB:"rollOver",PB:"shown"};O0.prototype.Gb=function(){var a=Coa(this,function(b){return"openUrl"==b.type&&null!=b.url});
return a?a.url:null};
O0.prototype.showLinkIcon=function(){return Q0(this,function(a){return null!=a.url&&a.url.showLinkIcon})};
var P0={iB:"anchored",lB:"branding",CHANNEL:"channel",VN:"cta",BO:"highlightText",PO:"label",PLAYLIST:"playlist",uP:"popup",PP:"speech",UB:"subscribe",ZP:"title",VIDEO:"video",jQ:"website"},yoa={lB:"branding",IN:"card",cO:"drawer",AO:"highlight",XO:"marker",zP:"promotion",TEXT:"text",lQ:"widget"},zoa={hQ:"video_relative",sP:"player_relative"};X0.prototype.o=function(a,b,c,d){this.g[a]=b?!c:c;a=g.Pb(this.g,function(e){return e});
this.l!=a&&(this.l=a,this.i.N(this.u,a,d))};Y0.prototype.ha=function(){return this.u};
Y0.prototype.l=function(){};var b1={bevel:1,dropshadow:2};g.t(g1,Y0);
g1.prototype.l=function(a,b){var c=U0(a);if(c){var d=H0(c,b);if(!(0>=d.width||0>=d.height)){var e;if(e=(c=(c=T0(a))&&c.g?c.g:null)&&c.length?c[0]:null){var f=g.th(F0(b,G0(e,new g.qh(e.D,e.F,e.Vi,e.l),b.g))),k=d.clone();c=new g.qh(f.x,f.y,1,1);var l=Math.max(k.left+k.width,c.left+c.width),m=Math.max(k.top+k.height,c.top+c.height);k.left=Math.min(k.left,c.left);k.top=Math.min(k.top,c.top);k.width=l-k.left;k.height=m-k.top;c=a.i;k=e1(k,c.effects);l=Z0(this,k.width,k.height);m=d1(c,k.width,k.height,this.g);
d=new g.qh(d.left-k.left,d.top-k.top,d.width,d.height);var n=new g.vd(f.x-k.left,f.y-k.top);this.o=17*C0(b.g,e.i,e.g?e.g:"xy");e=c.cornerRadius;f=a.i;var p=this.g&&R0(a),r=p?f.borderWidth+1:f.borderWidth;p=(f=r?new r_(r,p?f.i:f.borderColor):null)?f.g/2:0;r=Koa(d,n);var u=this.A(d,e,n,r),z=n.x;n=n.y;var D=d.width,E=d.height,F=d.left;d=d.top;var L=new o_;L.moveTo(F+e+p,d+p);"t"==r&&(L.dc(u.start,d+p),L.dc(z,n),L.dc(u.end,d+p));L.dc(F+D-e-p,d+p);p_(L,e,e,-90);"r"==r&&(L.dc(F+D-p,u.start),L.dc(z,n),L.dc(F+
D-p,u.end));L.dc(F+D-p,d+E-e-p);p_(L,e,e,0);"b"==r&&(L.dc(u.end,d+E-p),L.dc(z,n),L.dc(u.start,d+E-p));L.dc(F+e+p,d+E-p);p_(L,e,e,90);"l"==r&&(L.dc(F+p,u.end),L.dc(z,n),L.dc(F+p,u.start));L.dc(F+p,d+e+p);p_(L,e,e,180);L.close();w_(l,L,f,m);if(m=this.ha())g.J(m,"annotation-shape"),g.J(m,"annotation-speech-shape"),g.Kh(m,k.left,k.top),g.Uh(m,k.width,k.height),f1(l,m,c.effects)}}}};
g1.prototype.A=function(a,b,c,d){function e(f,k,l,m){f=Math.min(Math.max(m-2*b,0),f);k=g.rd(k-f/2,l+b,l+m-f-b);return new g.Ei(k,k+f)}
return"t"==d||"b"==d?e(this.o,c.x,a.left,a.width):"l"==d||"r"==d?e(this.o,c.y,a.top,a.height):new g.Ei(0,0)};g.t(h1,Y0);h1.prototype.l=function(a,b){var c=U0(a);if(c){var d=H0(c,b);if(!(0>=d.width||0>=d.height)){var e=a.i;c=e1(d,e.effects);var f=Z0(this,c.width,c.height),k=new r_(!e.l&&this.g?1:e.l,e.bgColor),l=new h_("#000",0);d=c1(new g.qh(0,0,d.width,d.height),e.cornerRadius,k?k.g/2+1:0);w_(f,d,k,l);f=this.ha();g.J(f,"annotation-shape");e=e.g;QZ(f,this.g?Math.max(e,.9):e);g.Kh(f,c.left,c.top);g.Uh(f,c.width,c.height)}}};g.t(i1,Y0);
i1.prototype.l=function(a,b){var c=U0(a);if(c){var d=H0(c,b);if(!(0>=d.width||0>=d.height)){c=a.i;var e=e1(d,c.effects),f=Z0(this,e.width,e.height),k=new g.qh(0,0,d.width,d.height);d=d1(c,d.width,d.height,this.g);var l=c.cornerRadius;var m=a.i;var n=this.g&&R0(a),p=n?m.borderWidth+1:m.borderWidth;m=p?new r_(p,n?m.i:m.borderColor):null;k=c1(k,l,m?m.g/2+1:0);w_(f,k,m,d);if(k=this.ha())g.J(k,"annotation-shape"),g.J(k,"annotation-popup-shape"),g.Kh(k,e.left,e.top),g.Uh(k,e.width,e.height),f1(f,k,c.effects)}}};g.t(j1,g1);j1.prototype.A=function(a,b,c,d){function e(f,k,l,m){f=Math.min(Math.max(m-2*b,0),f);k=k<=l+m/2?Math.max(l+m/4-f/2,l+b):Math.min(l+3*m/4-f/2,l+m-f-b);return new g.Ei(k,k+f)}
return"t"==d||"b"==d?e(this.o,c.x,a.left,a.width):"l"==d||"r"==d?e(this.o,c.y,a.top,a.height):new g.Ei(0,0)};g.t(k1,g.G);g.h=k1.prototype;g.h.kx=function(){this.F||(this.o&&g.Wh(this.o,!0),this.u&&g.Wh(this.u,!0),this.l&&(this.l.g=!0,QZ(this.i,p1(this)?1:0),this.l.l(this.g,m1(this))),this.D.isActive()&&this.D.stop(),this.F=!0,this.H=this.aa.Gm(g.pK(this.A),"mouseleave",function(a){this.gn.stop();this.zg(a)}))};
g.h.zg=function(){this.F&&(this.M?this.D.start():this.jw(),this.l&&(this.l.g=!1,QZ(this.i,p1(this)?1:0),this.l.l(this.g,m1(this))),this.F=!1,this.H&&(this.aa.La(this.H),this.H=null))};
g.h.jw=function(){this.o&&g.Wh(this.o,!1);this.u&&g.Wh(this.u,!1)};
g.h.CF=function(a){this.ba=a;this.gn.Kj()};
g.h.sD=function(){var a=this.ba,b=new g.vd(a.clientX,a.clientY),c=g.Oh(this.A.getRootNode()),d=q1(c,this.P);c=(this.u&&RZ(this.u)||this.o&&RZ(this.o))&&q1(c,this.M);d&&d.contains(b)||c&&c.contains(b)?this.kx(a):this.zg(a)};
g.h.show=function(){var a=this.g.i;a=(a&&0==a.g||"title"==this.g.style||"highlightText"==this.g.style?!1:!0)&&!this.l;var b=!this.i;if(a){var c=m1(this),d=null;"highlight"==this.g.type||"label"==this.g.style?d=new h1:"popup"==this.g.style?d=new i1:"anchored"==this.g.style?d=new g1:"speech"==this.g.style&&(d=new j1);d&&(d.l(this.g,c),this.l=d,c=d.ha())&&(g.Wh(c,!1),g.J(c,"annotation-type-"+this.g.type.toLowerCase()),this.R(c))}if(b){c=["annotation"];"highlightText"!=this.g.style||c.push("annotation-no-mouse");
c.push("annotation-type-"+this.g.type.toLowerCase());this.i=g.Sd("DIV",c);g.Wh(this.i,!1);this.g.o&&(this.C=g.Sd("DIV","inner-text"),"label"==this.g.style&&(g.J(this.C,"player-label-text"),this.C.style.backgroundColor=this.g.i.bgColor),g.ce(this.C,this.g.o),this.i.appendChild(this.C));g.Up(this.i,"annotation_id",this.g.id);this.R(this.i);Loa(this,this.i);if(R0(this.g)&&this.g.showLinkIcon()){if(d=this.g.Gb())c=this.i,d=new g.cn(A0(d)),c.title=d.g+d.i;this.u=g.Sd("SPAN","annotation-link-icon");g.Wh(this.u,
!1);this.i.appendChild(this.u)}Moa(this);R0(this.g)||(this.i.style.cursor="default")}if(a||b){a:{a=this.g.segment.g;if(a.length&&(a=M0(a[0]))){a=a.u;break a}a=0}this.i&&(this.i.style.zIndex=a);this.l&&this.l.ha()&&(this.l.ha().style.zIndex=a)}g.Wh(this.i,!0);QZ(this.i,p1(this)?1:0);o1(this);this.l&&this.l.ha()&&g.Wh(this.l.ha(),!0)};
g.h.hide=function(){this.i&&g.Wh(this.i,!1);this.l&&this.l.ha()&&g.Wh(this.l.ha(),!1);this.I&&(this.aa.La(this.I),this.I=null)};g.t(r1,g.G);g.h=r1.prototype;g.h.hide=function(){this.isVisible=!1;this.view&&(s1(this),this.view.hide())};
g.h.show=function(){this.isVisible=!0;this.view&&(this.view.show(),this.i.subscribe("resize",this.jx,this),this.i.subscribe("onVideoAreaChange",this.Zy,this))};
g.h.destroy=function(){if(this.view){s1(this);var a=this.view,b=a.aa;g.ds(b.g);b.g.length=0;a.gn.dispose();a.D.dispose();a.i&&g.Yd(a.i);a.l&&a.l.ha()&&g.Yd(a.l.ha())}t1(this)};
g.h.Zy=function(){o1(this.view)};
g.h.jx=function(){o1(this.view)};g.t(u1,f_);g.t(v1,f_);g.t(w1,f_);g.t(x1,f_);g.t(y1,x1);g.t(z1,f_);g.t(A1,f_);J1.prototype.l=function(a,b){var c=g.he(b.target,"label");c&&g.K(c,"iv-card-poll-choice-focused",a)};
J1.prototype.u=function(a,b){var c=g.he(b.target,null,"iv-card-poll",void 0);if(c)if(a.o)g.Id("iv-card-sign-in-button",c).click();else{var d=parseInt(Mna(b.target),10);if(null==a.g)a.choices[d].count++,a.g=d;else if(a.g!=d){var e=a.choices[a.g];e.count=Math.max(e.count-1,0);a.choices[d].count++;a.g=d}else e=a.choices[a.g],e.count=Math.max(e.count-1,0),a.g=null;L1(a,c);g.Yq(this.g.videoData.Gd,{Ec:{action_poll_vote:1},qb:{poll_id:a.id,index:d,session_token:a.F}});F1(this.g.logger,a.l,void 0,{"link-id":d},
a.i.click,5);(c=g.qt())&&g.dt(c,a.D)}};g.t(Y1,g.G);g.h=Y1.prototype;g.h.addCueRange=function(a,b,c,d,e){a=new g.mE(a,b,{id:c});g.H(this,a);a.namespace="annotations_module";d&&MZ(a).subscribe("onEnter",d,this);e&&MZ(a).subscribe("onExit",e,this);g.wK(this.context.Y,[a])};
g.h.Qn=function(){this.context.i.subscribe("resize",this.Fl,this)};
g.h.ha=function(){return this.Ba};
g.h.Ki=function(a,b,c,d,e,f,k){this.context.g.ca(a,"click",g.Ra(this.Fm,b,c,d,e,f||[],k||0),this);this.context.g.ca(a,"touchstart",g.Ra(function(){this.Us=!1}),this);
this.context.g.ca(a,"touchmove",g.Ra(function(){this.Us=!0}),this)};
g.h.Fm=function(a,b,c,d,e,f,k){if(this.Us)return!1;k&&(k.stopPropagation(),k.preventDefault());Xoa(this,a,c,d,e,f);return!1};
g.h.show=function(){this.X=(0,g.B)()};
g.h.hide=function(){};
g.h.destroy=function(){g.Yd(this.ha())};
g.h.Fl=function(){};g.t(a2,Y1);g.h=a2.prototype;g.h.isAvailable=function(){var a;if(a=!!this.l.length)(a=this.i.getRootNode())?(a=g.Vh(a),a=173<a.width&&173<a.height):a=!1;return a};
g.h.Fl=function(){var a=this.isAvailable();g.Wh(this.ha(),a);g.K(this.context.Y.getRootNode(),"ytp-iv-drawer-enabled",a);OZ(this.i)};
g.h.destroy=function(){this.i.Hi(!1);this.i.getRootNode().removeChild(this.A);g.eq(this.I);g.ds(this.ba);this.Z&&this.Z.dispose();this.C&&this.C.dispose();Y1.prototype.destroy.call(this)};
g.h.eF=function(a){this.M.start();a.preventDefault();a=a||window.event;var b=0;"MozMousePixelScroll"==a.type?b=0==(a.axis==a.HORIZONTAL_AXIS)?a.detail:0:window.opera?b=a.detail:b=0==a.wheelDelta%120?"WebkitTransform"in document.documentElement.style?window.chrome&&0==navigator.platform.indexOf("Mac")?a.wheelDeltaY/-30:a.wheelDeltaY/-1.2:a.wheelDelta/-1.6:a.wheelDeltaY/-3;if(a=b)this.o.scrollTop+=a};
g.h.Zz=function(a){if(!g.go(this.i.getRootNode(),"ytp-cards-teaser-shown")){if(this.g!=a){var b=g.qt(),c=this.g?this.g.Fb.u:this.H;b&&c&&e_(b,[c]);this.g=a;d2(this)}RZ(this.ha())&&(2==this.context.Y.getPresentingPlayerType()?b=1==(isNaN(void 0)?this.context.Y.getAdState():void 0):(b=isNaN(void 0)?this.context.Y.getPlayerState():void 0,b=1==b||0==b&&0===this.context.Y.getCurrentTime()),b&&a.Fb.teaserDurationMs&&this.i.Hi(!0,{teaserText:a.Fb.teaserText,durationMs:a.Fb.teaserDurationMs}));this.ka.isActive()||
((!this.u||!this.M.isActive()&&this.V)&&e2(this,a),this.ka.start(910+a.Fb.teaserDurationMs))}};
g.h.oM=function(a){this.u||(this.g=a,d2(this),e2(this,a),Z1(this,"YOUTUBE_DRAWER_AUTO_OPEN",!1,a))};
g.h.sC=function(){if(this.u){H1(this.context.logger,this.R,4,f2(this).i.close);var a=g.qt();a&&this.P&&g.dt(a,this.P);$1(this)}};
g.h.BC=function(){g.K(this.A,"iv-drawer-scrolled",0<this.o.scrollTop)};
g.h.mE=function(){var a=g.qt(),b=f2(this);b=b?b.u:this.H;a&&b&&d_(a,[b])};
g.h.lE=function(){var a=g.qt(),b=f2(this);b=b?b.u:this.H;a&&b&&e_(a,[b])};
g.h.pE=function(){var a=f2(this);I1(this.context.logger,8,a.l,a.i.CM);var b=g.qt();b&&a&&d_(b,[a.C,a.u])};
g.h.oE=function(){var a=g.qt(),b=f2(this);a&&b&&e_(a,[b.C])};
g.h.nE=function(a){var b=f2(this),c=g.qt();this.g?a?(a=this.context.logger,I1(a,9,b.l,b.i.Bs),a.g.sendVideoStatsEngageEvent(4,void 0),c&&g.dt(c,b.C)):(a=this.context.logger,I1(a,12,b.l,b.i.Bs),a.g.sendVideoStatsEngageEvent(4,void 0),c&&g.dt(c,b.u)):(a=this.context.logger,H1(a,this.R,12,b.i.Bs),a.g.sendVideoStatsEngageEvent(4,void 0),c&&this.H&&g.dt(c,this.H))};
var b2={collaborator:u1,episode:A1,movie:A1,playlist:v1,poll:w1,productListing:y1,simple:x1,video:z1};g.t(g2,Y1);g2.prototype.Qn=function(){Y1.prototype.Qn.call(this);epa(this)};
g2.prototype.show=function(){Y1.prototype.show.call(this);var a=g.qt(),b=this.annotation.data;a&&b&&(b=b.session_data)&&d_(a,[g.$s(b.itct)])};
g2.prototype.hide=function(){Y1.prototype.hide.call(this);var a=g.qt(),b=this.annotation.data;a&&b&&(b=b.session_data)&&e_(a,[g.$s(b.itct)])};g.t(h2,g2);g.h=h2.prototype;g.h.wM=function(a,b,c,d){this.l.stop();if(!this.o){var e=g.Vh(a);this.g||(g.Th(a,e.width),g.Th(b,e.width));g.Ch(c,"top",e.height-Math.max(Math.min(e.height,d)/2+10,20)+"px");g.Ch(c,"right","1px");this.o=!0;g.Wh(a,!0);this.A=new g.M(function(){g.J(this.ha(),"iv-branding-active")},0,this);
this.A.start()}};
g.h.QD=function(a,b){g.io(this.ha(),"iv-branding-active");this.C=new g.M((0,g.y)(function(){g.Wh(a,!1);this.g||g.Th(b,0)},this),250);
this.C.start();this.o=!1};
g.h.show=function(){if(!this.isActive){g2.prototype.show.call(this);if(!this.D){g.J(this.ha(),"iv-branding");var a=this.annotation.data;this.u=a.image_width;this.i=g.Sd("IMG",{src:a.image_url,"class":"branding-img iv-click-target",width:a.image_width,height:a.image_height});g.Wh(this.i,!1);var b=g.Sd("DIV","branding-img-container",this.i);this.ha().appendChild(b);var c=g.Sd("DIV","iv-branding-context-name");g.ce(c,a.channel_name);var d=g.Sd("DIV","iv-branding-context-subscribe");if(b=a.standalone_subscribe_button_data)this.g=
new g.gW(b.subscribeText,b.subscribeCount,b.unsubscribeText,b.unsubscribeCount,!!b.enabled,!!b.classic,a.channel_id,!!b.subscribed,b.feature,a.session_data.itct,b.signinUrl,this.context.Y),this.g.g(d);b=g.Sd("DIV","iv-branding-context-subscribe-caret");c=g.Sd("DIV","branding-context-container-inner",b,c,d);g.Wh(c,!1);d=g.Sd("DIV","branding-context-container-outer",c);g.Ch(d,"right",this.u+"px");this.ha().appendChild(d);var e=this.annotation.Gb();e&&this.Ki(this.i,e,this.annotation.id,a.session_data,
this.annotation.g);this.l=new g.M(g.Ra(this.QD,c,d),500,this);g.H(this,this.l);this.context.g.ca(this.ha(),"mouseover",(0,g.y)(this.wM,this,c,d,b,a.image_height));this.context.g.ca(this.ha(),"mouseout",(0,g.y)(this.l.start,this.l,void 0));this.D=!0}E1(this.context.logger,this.annotation.g);g.Wh(this.ha(),!0);this.isActive=!0;if(this.i){a=this.i;var f=void 0===f?0:f;b=PZ(a).width;c=g.Ga(void 0)?void 0:b;g.Kh(a,c);f=new b_(a,[c,a.offsetTop],[c-b-f,a.offsetTop],200,Ona);g.H(this,f);this.context.l.ca(f,
"begin",g.Ra(g.Wh,a,!0));f.play()}}};
g.h.hide=function(){this.isActive&&(g2.prototype.hide.call(this),g.Wh(this.ha(),!1),this.isActive=!1)};
g.h.destroy=function(){this.g&&(this.g.dispose(),this.g=null);g2.prototype.destroy.call(this)};g.t(i2,g2);g.h=i2.prototype;g.h.show=function(){this.isActive||(g2.prototype.show.call(this),this.H||(fpa(this),this.H=!0),g.Wh(this.ha(),!0),this.annotation&&this.annotation.g&&E1(this.context.logger,this.annotation.g),g.Jg(function(){g.io(this.ha(),"iv-promo-inactive")},100,this),this.ha().removeAttribute("aria-hidden"),this.isActive=!0,l2(this),k2(this),m2(this,this.C))};
g.h.hide=function(){this.isActive&&(g.J(this.ha(),"iv-promo-inactive"),this.isActive=!1,this.ha().setAttribute("aria-hidden",!0))};
g.h.Fm=function(a,b,c,d,e,f,k){return this.u?!1:g2.prototype.Fm.call(this,a,b,c,d,e,f,k)};
g.h.Sp=function(a,b){b.stopPropagation();k2(this);m2(this,a);this.g.focus()};
g.h.uD=function(a){this.F=!0;this.Sp(500,a)};
g.h.tD=function(){this.F=!1;j2(this)};
g.h.lD=function(a){a.stopPropagation();this.hide();G1(this.context.logger,this.annotation.g)};
g.h.mD=function(a){a.stopPropagation();l2(this);this.u=!0;g.J(this.ha(),"iv-promo-collapsed-no-delay");this.A.start();G1(this.context.logger,this.annotation.g)};
g.h.destroy=function(){this.A.dispose();g2.prototype.destroy.call(this)};g.t(n2,g.RK);g.h=n2.prototype;g.h.Zb=function(a,b){if(!o2(g.X(this.player).playerStyle))return null;switch(a){case "loadCustomAnnotationsXml":var c=g.ko(b);c&&t2(this,c);return!0;case "removeCustomAnnotationById":return b&&this.g&&(c2(this.g,b),OZ(this.player)),!0}return null};
g.h.getOptions=function(){return o2(g.X(this.player).playerStyle)?["loadCustomAnnotationsXml","removeCustomAnnotationById"]:[]};
g.h.Gr=function(){if(this.o){var a=g.pK(this.player).getVideoContentRect(!0);g.Uh(this.o.element,a.width,a.height);g.Kh(this.o.element,a.left,a.top)}if(this.g){var b=g.uK(this.player);a=this.g;b=b.width;g.K(a.A,"iv-drawer-small",426>=b);g.K(a.A,"iv-drawer-big",1280<=b)}};
g.h.aK=function(a){this.hc(a.state);g.U(a.state,2)&&(this.yd()&&this.De()&&2!=this.player.getPresentingPlayerType()&&this.setCardsVisible(!1),this.Hi(!1))};
g.h.load=function(){g.RK.prototype.load.call(this);this.hc(g.oK(this.player));this.H++;var a=this.player.getVideoData(),b=a.videoId,c=(0,g.y)(this.MI,this,b,this.H),d=(0,g.y)(function(){this.C=null},this);
g.rq()&&(c=u2(this,c));c={format:"XML",Yc:c,onError:d,Ec:{}};a.isPharma&&(c.Ec.pharma="1");c.method="POST";c.withCredentials=!0;d=g.X(this.player);"gaming"==d.playerStyle&&(c.Ec.gaming="1");(b=d.I.get(b))&&v2(c,b);b=b&&(b.Ll||b.Kl);if(!a.yl||b)a.Gd?p2(this,a.Gd,c):(this.l=(0,g.y)(this.NE,this,c),this.player.addEventListener("videodatachange",this.l));g.DK(this.player,this.o.element,4);this.Gr()};
g.h.hc=function(a){a=!a.isCued()&&!g.U(a,1024);g.gD(this.u,a);g.gD(this.o,a)};
g.h.NE=function(a){var b=this.player.getVideoData();b.Gd&&(this.l&&(this.player.removeEventListener("videodatachange",this.l),this.l=null),p2(this,b.Gd,a))};
g.h.unload=function(){Qoa(this.D);g.zK(this.player,"annotations_module");g.Lb(this.i,function(a){a.destroy()});
g.Lb(this.P,function(a){a.destroy()});
this.F=null;this.g&&(this.g.destroy(),this.g=null,OZ(this.player));this.I=!1;this.C&&(this.C.abort(),this.C=null);this.i={};this.P={};this.u.hide();g.RK.prototype.unload.call(this);g.fD(this.o);this.l&&(this.player.removeEventListener("videodatachange",this.l),this.l=null)};
g.h.MI=function(a,b,c){this.C=null;if(!r2(this,b,a)&&(a=g.Oq(c)&&c.responseXML?c.responseXML:null)){t2(this,a);g.J(this.player.getRootNode(),"iv-module-loaded");a=[];for(var d in this.i){b=this.i[d].annotation;if(b.segment)if(c=b.segment,c.g.length)if(c=c.g[0].i||c.g[0].g||c.g[0].l,!c||2>c.length)c=null;else{var e=c.length-1;c=0>=c[0].t&&0>=c[e].t?null:{start:c[0].t,end:c[e].t}}else c=null;else c=null;if(e=c)if(c=1E3*e.start,e=1E3*e.end,0==c&&(c++,e++),!(e<c)){var f={id:d,namespace:"annotations_module"};
"marker"==b.type&&(f.style="ytp-chapter-marker",f.tooltip=b.o,f.visible=!0);b=new g.mE(c,e,f);a.push(b)}}g.wK(this.player,a)}};
g.h.Yy=function(a){a==this.player.getVideoData().videoId&&(this.loaded?kpa(this):this.load())};
g.h.KE=function(a){a=a.getId();var b=this.i[a];b&&!b.l&&(b=b.annotation,w2(this,a),E1(this.D,b.g))};
g.h.LE=function(a){x2(this,a.getId())};
g.h.iw=function(a){a&&(a.hide(),z2(this,"shown",!1,a.annotation.id),this.Tl(a.annotation,"hidden"))};
g.h.kA=function(a){a&&(a.show(),z2(this,"shown",!0,a.annotation.id),this.Tl(a.annotation,"shown"))};
g.h.pL=function(a,b,c){var d=this.i[a];if(d&&b.value!=c){b.value=c;var e=!1;S0(d.annotation,function(f){e=e||f.value});
npa(this,a,b,e)}};
g.h.SH=function(a){if(a&&a.id){var b=a.Gb();if(b){var c=A0(b);if(c){var d=(0,g.y)(this.Tl,this,a,"click");if("new"==X1(c,b.target)||y2(this,b))d(),d=null;F1(this.D,a.g,d)}}}};
g.h.Tl=function(a,b){Boa(a,function(c){if(c.trigger==b&&"openUrl"==c.type&&c.url){var d=this.player.getVideoData(),e;if(!(e=!y2(this,c.url))){e=W1(c.url);var f=Uoa(c.url);e?(d.videoId==e?this.player.seekTo(f||0):(d=s2(this).Y,g.mY(d.app,e,void 0,void 0,void 0,void 0),f&&s2(this).Y.ec()&&s2(this).Y.seekTo(f)),d=!0):d=!1;e=!d}e&&(e=g.X(this.player),(d=A0(c.url))?(f=U1(d),e&&"com"==f[0]&&"google"==f[1]&&"plus"==f[2]&&(e=g.Ra(Voa,e.pageId,e.kc),d=new g.cn(d),e=e(d.i),d.i=e,d=d.toString())):d=null,d&&
(this.player.pauseVideo(),c=X1(d,c.url.target),e=a.itct,"ei"in g.Bq(d)&&(d=g.kh(d,"ei")),g.JL(d,"current"==c?"_top":void 0,{itct:e})))}},this)};
g.h.VI=function(){z2(this,"playerControlShow",!1)};
g.h.RK=function(){z2(this,"playerControlShow",!0)};
g.h.ME=function(a){z2(this,"rollOver",!0,a.id)};
g.h.zg=function(a){z2(this,"rollOver",!1,a.id)};
g.h.uI=function(a){a&&a.id&&(this.i[a.id].l=!0,x2(this,a.id),G1(this.D,a.g),this.Tl(a,"close"),z2(this,"closed",!0,a.id))};
g.h.yd=function(){return!!this.g&&this.g.isAvailable()};
g.h.De=function(){this.yd();return!!this.g&&this.g.u};
g.h.setCardsVisible=function(a,b,c){b=void 0===b?!1:b;this.yd();this.g&&(a?c?Z1(this.g,c,b):Z1(this.g,"YOUTUBE_DRAWER_AUTO_OPEN",b):$1(this.g))};
g.h.Hi=function(a,b){this.player.N(a?"cardsteasershow":"cardsteaserhide",b)};
g.h.T=function(){g.X(this.player).I.unsubscribe("vast_info_card_add",this.Yy,this);g.io(this.player.getRootNode(),"ytp-iv-drawer-open");for(var a=this.M,b=0,c=a.length;b<c;b++)g.sq(a[b]);this.M.length=0;g.RK.prototype.T.call(this)};g.oV.annotations_module=n2;g.oV.creatorendscreen=z_;})(_yt_player);
