(function(g){var window=this;var C2=function(a){var b={languageCode:a.i,languageName:a.l,displayName:g.Lz(a),kind:a.o,name:a.u,id:a.Ea,is_servable:a.C,is_default:a.isDefault,is_translateable:a.D,vss_id:a.A};a.g&&(b.translationLanguage=a.g);return b},D2=function(a){return a.g?a.g.languageCode:a.i},qpa=function(a,b){var c=new g.Kz;
c.i=a.i;c.l=a.l;c.u=a.u;c.o=a.o;c.isDefault=!1;c.C=a.C;c.D=a.D;c.A=a.A;c.F=a.F;c.g=b;return c},E2=function(a){if(!rpa.test(a))throw Error("'"+a+"' is not a valid hex color");
4==a.length&&(a=a.replace(spa,"#$1$1$2$2$3$3"));a=a.toLowerCase();a=parseInt(a.substr(1),16);return[a>>16,a>>8&255,a&255]},tpa=function(){this.i=[];
this.g=[]},F2=function(a,b){return b?a.g.concat(a.i):a.g},G2=function(a,b){switch(b.o){case "asr":var c=a.i;
g.Ya(c,(0,g.y)(b.Nq,b))||c.push(b);break;default:c=a.g,g.Ya(c,(0,g.y)(b.Nq,b))||c.push(b)}},H2=function(){g.G.call(this);
this.i=new tpa;this.u=[]},I2=function(a,b,c){H2.call(this,a);
this.g=null;this.u=b.qu;this.l=c},J2=function(){this.Ta=[]},K2=function(a,b,c,d,e,f){g.G.call(this);
this.I=a;this.o=b;this.A=new J2;this.g=null;this.F=d;this.P=f;this.i=this.l=null;this.D=c;this.C=e||!1;this.H=new g.M(this.Gw,1E3,this);g.H(this,this.H);this.u=new g.Ls(this);g.H(this,this.u);g.Q(g.X(b).experiments,"html5_disable_captions_seek_complete")?this.u.K(b,"seekto",this.rx):this.u.K(b,"seekcomplete",this.NF);this.rx(b.getCurrentTime());this.Gw()},L2=function(a,b){b-=a.o.ac();
var c=a.g;a.g=g.Wa(a.D.vf(b).g);c!=a.g&&a.P&&a.P()},M2=function(a,b){var c=g.Qv(b,a.I,{}).Gb(),d={format:"RAW",
withCredentials:!0};a.C&&(d.responseType="arraybuffer");a.i=g.tr(c,d,3,100).then((0,g.y)(a.xK,a));a.l=b;c=a.A;d=a.l.g[0].i;var e=g.pb(c.Ta,d);0<=e||0>e&&1==(-e-1)%2||(e=-e-1,0<e&&1==d-c.Ta[e-1]&&e<c.Ta.length&&1==c.Ta[e]-d?(g.cb(c.Ta,e),g.cb(c.Ta,e-1)):0<e&&1==d-c.Ta[e-1]?c.Ta[e-1]=d:e<c.Ta.length&&1==c.Ta[e]-d?c.Ta[e]=d:(g.lb(c.Ta,e,0,d),g.lb(c.Ta,e+1,0,d)))},N2=function(a,b){H2.call(this,g.X(b));
this.g=a;this.C=b;this.l=null;this.o=!1;this.A=g.vz(g.X(this.C))&&!this.g.i},O2=function(a,b){var c=[],d;
for(d in a.g.g){var e=a.g.g[d];if(g.hV(e,b||null)){var f="en",k="English",l=".en",m="";if(e=e.info.captionTrack)f=e.languageCode,k=e.displayName,l=e.vssId,m=e.kind;c.push(new g.Kz({id:d,languageCode:f,languageName:k,is_servable:!0,is_default:!0,is_translateable:!1,vss_id:l,kind:m}))}}return c},upa=function(a,b){return null!=b&&b in a.g.g?a.g.g[b]:null},P2=function(a,b,c){var d=[],e;
for(e in a.g.g){var f=a.g.g[e];if(g.hV(f,c||null)){var k=f.info.captionTrack;k&&k.languageCode==b&&d.push(f)}}return d.length?d[0]:null},Q2=function(a,b,c,d,e){H2.call(this,e||null);
c=c||g.Bq(a).hl||"";c=c.split("_").join("-");this.o=g.Dq(a,{hl:c});this.l=b;this.A=!!d;this.C={};this.g=null},R2=function(a,b,c,d,e,f,k){f=void 0===f?!1:f;
k=void 0===k?null:k;g.mE.call(this,a,a+b,{priority:c,namespace:"captions"});this.windowId=d;this.text=e;this.l=f;this.g=k},S2=function(a,b,c,d,e){g.mE.call(this,a,a+b,{priority:c,
namespace:"captions"});this.id=d;this.params=e;this.g=[]},U2=function(a){a=void 0===a?{}:a;
var b="_"+T2++;return new S2(0,0x8000000000000,0,b,a)},W2=function(a,b,c,d,e,f){var k={};
g.Sa(k,b);g.Sa(k,a.params);g.Sa(k,c);var l={};g.Sa(l,b.wb);a.params.wb&&g.Sa(l,a.params.wb);g.Sa(l,c.wb);k.wb=l;g.W.call(this,{B:"div",G:"caption-window",L:{id:"caption-window-"+a.id,dir:1==k.Ae?"rtl":"ltr",tabindex:"0","aria-live":"assertive",lang:k.lang},J:[{B:"span",G:"captions-text",L:{style:"word-wrap: normal; display: block;"}}]});this.C=[];this.O=!1;this.o=a;this.V=this.R=null;this.Qa=e;this.Pa=f;this.D=null;this.X=.96*e;this.xa=.96*f;this.l=k;this.Ja=c;this.A=this.i["captions-text"];this.Ba=
null!=this.A.style["box-decoration-break"]||null!=this.A.style["-webkit-box-decoration-break"];this.Z=d/360*16;this.type=0;this.ka=this.Z*V2(l);a=new g.Rs(this.element,!0);g.H(this,a);a.subscribe("dragstart",this.MF,this);a.subscribe("dragmove",this.LF,this);a.subscribe("dragend",this.KF,this);this.wa=this.na=0;b="";this.l.windowOpacity&&(a=E2(this.l.windowColor),b="rgba("+a[0]+","+a[1]+","+a[2]+","+this.l.windowOpacity+")");a={"background-color":b,display:!1===this.l.isVisible?"none":"","text-align":vpa[this.l.textAlign]};
this.Ba&&(a["border-radius"]=b?this.ka/8+"px":"");if(this.u=2==this.o.params.Ae||3==this.o.params.Ae)b=this.element,c="vertical-rl",1==this.l.uA&&(c="vertical-lr"),g.Nd&&(c="vertical-lr"==c?"tb-lr":"tb-rl"),g.Ch(b,"-o-writing-mode",c),g.Ch(b,"-webkit-writing-mode",c),g.Ch(b,"writing-mode",c),g.Ch(b,"text-orientation","upright"),g.J(b,"ytp-vertical-caption"),3==this.o.params.Ae&&(g.Ch(b,"text-orientation",""),g.Ch(b,"transform","rotate(180deg)"));g.Ch(this.element,a);switch(this.l.Tf){case 0:case 1:case 2:g.J(this.element,
"ytp-caption-window-top");break;case 6:case 7:case 8:g.J(this.element,"ytp-caption-window-bottom")}},V2=function(a){var b=1+.25*(a.fontSizeIncrement||0);
if(0==a.offset||2==a.offset)b*=.8;return b},X2=function(a,b){var c={},d=b.background?b.background:a.l.wb.background;
if(null!=b.backgroundOpacity||b.background){var e=null!=b.backgroundOpacity?b.backgroundOpacity:a.l.wb.backgroundOpacity;d=E2(d);c.background="rgba("+d[0]+","+d[1]+","+d[2]+","+e+")";a.Ba&&(c["box-decoration-break"]="clone",c["border-radius"]=a.ka/8+"px")}if(null!=b.fontSizeIncrement||null!=b.offset)c["font-size"]=a.Z*V2(b)+"px";d=1;e=b.color||a.l.wb.color;if(b.color||null!=b.textOpacity)e=E2(e),d=null==b.textOpacity?a.l.wb.textOpacity:b.textOpacity,e="rgba("+e[0]+","+e[1]+","+e[2]+","+d+")",c.color=
e,c.fill=e;var f=b.charEdgeStyle;0==f&&(f=null);if(f){e="rgba(34, 34, 34, "+d+")";var k="rgba(204, 204, 204, "+d+")";b.zu&&(k=e=b.zu);var l=a.Z/16/2,m=Math.max(l,1),n=Math.max(2*l,1),p=Math.max(3*l,1),r=Math.max(5*l,1);d=[];switch(f){case 4:for(;p<=r;p+=l)d.push(n+"px "+n+"px "+p+"px "+e);break;case 1:n=2<=window.devicePixelRatio?.5:1;for(f=m;f<=p;f+=n)d.push(f+"px "+f+"px "+e);break;case 2:d.push(m+"px "+m+"px "+k);d.push("-"+m+"px -"+m+"px "+e);break;case 3:for(p=0;5>p;p++)d.push("0 0 "+n+"px "+
e)}c["text-shadow"]=d.join(", ")}e="";switch(b.fontFamily){case 1:e='"Courier New", Courier, "Nimbus Mono L", "Cutive Mono", monospace';break;case 2:e='"Times New Roman", Times, Georgia, Cambria, "PT Serif Caption", serif';break;case 3:e='"Deja Vu Sans Mono", "Lucida Console", Monaco, Consolas, "PT Mono", monospace';break;case 5:e='"Comic Sans MS", Impact, Handlee, fantasy';break;case 6:e='"Monotype Corsiva", "URW Chancery L", "Apple Chancery", "Dancing Script", cursive';break;case 7:e=g.br()?'"Carrois Gothic SC", sans-serif-smallcaps':
'"Arial Unicode Ms", Arial, Helvetica, Verdana, "Marcellus SC", sans-serif';break;case 0:case 4:e='"YouTube Noto", Roboto, "Arial Unicode Ms", Arial, Helvetica, Verdana, "PT Sans Caption", sans-serif'}e&&(c["font-family"]=e);e=b.offset;null==e&&(e=a.l.wb.offset);switch(e){case 0:c["vertical-align"]="sub";break;case 2:c["vertical-align"]="super"}7==b.fontFamily&&(c["font-variant"]="small-caps");b.bold&&(c["font-weight"]="bold");b.Pe&&(c["font-style"]="italic");b.underline&&(c["text-decoration"]="underline");
b.PD&&(c.visibility="hidden");1==b.RD&&a.u&&(c["text-combine-upright"]="all",c["text-orientation"]="mixed",e=g.xz||g.yz,3==a.o.params.Ae?c.transform=e?"rotate(90deg)":"rotate(180deg)":e&&(c.transform="rotate(-90deg)"));if(1==b.ze||2==b.ze||3==b.ze||4==b.ze||5==b.ze)if(g.xz)c["font-weight"]="bold";else switch(c["text-emphasis"]="filled circle",c["webkit-text-emphasis"]="filled circle",b.ze){case 4:case 3:c["text-emphasis-position"]="under right";c["webkit-text-emphasis-position"]="under right";break;
case 5:case 2:c["text-emphasis-position"]="over left",c["webkit-text-emphasis-position"]="over left"}return c},Y2=function(a){a.D=g.Td("SPAN");
g.Ch(a.D,{display:"block"});g.J(a.D,"caption-visual-line");a.A.appendChild(a.D)},Z2=function(a,b){var c=g.Td("SPAN");
g.Ch(c,{display:"inline-block","white-space":"pre-wrap"});g.Ch(c,X2(a,b));c.classList.add("ytp-caption-segment");a.D.appendChild(c);c.previousElementSibling&&(g.Ch(c.previousElementSibling,{"border-top-right-radius":"0","border-bottom-right-radius":"0"}),g.Ch(c,{"border-top-left-radius":"0","border-bottom-left-radius":"0"}));return c},$2=function(a,b,c){a.O=a.O||!!c;
var d={};g.Sa(d,a.l.wb);g.Sa(d,c||b.g);g.Sa(d,a.Ja.wb);(c=!a.D)&&Y2(a);for(var e=a.R&&a.V&&g.bc(d,a.V)?a.R:Z2(a,d),f=g.v(b.text),k=f?b.text.split("\n"):[b.text],l=0;l<k.length;l++){var m=0<l||!b.l,n=k[l];m&&!c?(Y2(a),e=Z2(a,d)):m&&c&&(c=!1);n&&(e.appendChild(f?g.Ud(n):n),f||"RUBY"!=n.tagName||4!=n.childElementCount||g.xz||!g.Gh(n.children[2],"text-emphasis")||(m=a.u?"padding-right":"padding-top",g.Gh(n.children[2],"text-emphasis-position")&&(m=a.u?"padding-left":"padding-bottom"),g.Pd?g.Ch(e,m,"1em"):
g.Ch(e,m,"0.5em")))}a.V=d;a.R=e;a.C.push(b)},a3=function(){},c3=function(){this.o=this.i=this.mode=this.l=0;
this.u=new b3(this);this.A=new b3(this);this.g=[];this.clear()},wpa=function(a,b,c){if(255==a&&255==b||!a&&!b)return{Cl:a,
Dl:b,result:0};a=d3[a];b=d3[b];if(a&128){if(!(b&128)&&0!=c.g&&c.i==b)return{Cl:a,Dl:b,result:1}}else if(b&128&&1<=a&&31>=a)return{Cl:a,Dl:b,result:2};return{Cl:a,Dl:b,result:3}},xpa=function(a,b,c,d){255==b&&255==c||!b&&!c?(45==++a.o&&a.reset(),a.u.g.clear(),a.A.g.clear()):(a.o=0,e3(a.u,b,c,d))},ypa=function(a,b){a.g.sort(function(e,f){var k=e.time-f.time;
return 0==k?e.order-f.order:k});
for(var c=0;c<a.g.length;c++){var d=a.g[c];a.i=d.time;0==d.type?xpa(a,d.tu,d.uu,b):1==d.type&&a.l&496&&e3(a.A,d.tu,d.uu,b)}a.g.length=0},f3=function(){this.g=0},g3=function(){this.i=this.l=this.g=0},h3=function(){this.timestamp=this.Sd=0},i3=function(a){this.l=[];
for(var b=0;15>=b;b++){this.l[b]=[];for(var c=0;32>=c;c++)this.l[b][c]=new h3}this.g=this.i=this.row=0;this.style=new f3;this.u=a;this.o=0},j3=function(a,b){if(3==a.style.g){for(var c=0,d=0,e=a.u.i+0,f="",k="",l=e,m=1;15>=m;++m){for(var n=!1,p=d?d:1;32>=p;++p){var r=a.l[m][p];
if(0!=r.Sd){0==c&&(c=m,d=p);n=String.fromCharCode(r.Sd);var u=r.timestamp;u<e&&(e=u);r.timestamp=l;k&&(f+=k,k="");f+=n;n=!0}if((0==r.Sd||32==p)&&n){k="\n";break}else if(d&&!n)break}if(c&&!n)break}f&&b.u(c,d,e,l,f)}else for(d=c=0,f=e=a.u.i+0,k=1;15>=k;++k)for(l="",m=1;32>=m;++m)if(p=a.l[k][m],r=p.Sd,0!=r&&(0==c&&(c=k,d=m),n=String.fromCharCode(r),u=p.timestamp,u<=e&&(e=u),l+=n,p.reset()),32==m||0==r)l&&b.u(c,d,e,f,l),e=f,l="",d=c=0},Dpa=function(a,b){switch(a){case 0:return zpa[(b&127)-32];
case 1:return Apa[b&15];case 2:return Bpa[b&31];case 3:return Cpa[b&31]}return 0},k3=function(a){return a.l[a.row][a.i]},l3=function(a,b,c){2<=b&&1<a.i&&(--a.i,k3(a).Sd=0);
var d=k3(a);d.timestamp=a.u.i+0;d.Sd=Dpa(b,c);32>a.i&&a.i++},m3=function(a,b,c,d){for(var e=0;e<d;e++)for(var f=0;32>=f;f++)a.l[b+e][f].dg(a.l[c+e][f])},n3=function(a,b,c){for(var d=0;d<c;d++)for(var e=0;32>=e;e++)a.l[b+d][e].reset()},o3=function(a){a.row=0<a.g?a.g:1;
a.i=1;n3(a,0,15)},p3=function(a){this.o=a;
this.u=0;this.style=new f3;this.A=new i3(a);this.C=new i3(a);this.D=new i3(a);this.i=this.A;this.l=this.C;this.g=this.i},q3=function(a,b,c){var d=a.i,e=!1;
switch(a.style.get()){case 4:if(0<d.g)break;case 1:case 2:j3(d,c),o3(a.i),o3(a.l),d.row=15,d.g=b,e=!0}a.style.set(3);a.g=d;a.g.style=a.style;a.o.mode=1<<d.o;e?d.i=1:d.g!=b&&(d.g>b?(j3(d,c),n3(d,d.row-d.g,b)):d.row<b&&(b=d.g),d.g=b)},r3=function(a){a.style.set(1);
a.g=a.l;a.g.g=0;a.g.style=a.style;a.o.mode=1<<a.g.o},s3=function(a){a.style.set(4);
a.g=a.D;a.g.style=a.style;a.o.mode=1<<a.g.o},b3=function(a){this.i=a;
this.g=new g3;this.u=0;this.l=new p3(a);this.A=new p3(a);this.o=this.l},e3=function(a,b,c,d){a.g.update();
b=wpa(b,c,a.g);switch(b.result){case 0:return;case 1:case 2:return}var e=b.Cl;c=b.Dl;if(32<=e||!e)a.i.mode&a.i.l&&(b=e,b&128&&(b=127),c&128&&(c=127),a=a.o.g,b&96&&l3(a,0,b),c&96&&l3(a,0,c),0!=b&&0!=c&&3==a.style.g&&j3(a,d));else if(e&16)a:if(!a.g.matches(e,c)&&(b=a.g,b.l=e,b.i=c,b.g=2,b=e&8?a.A:a.l,a.o=b,a.i.mode=1<<(a.u<<2)+(b.u<<1)+(4==b.style.g?1:0),(a.i.mode|1<<(a.u<<2)+(b.u<<1)+(4!=b.style.g?1:0))&a.i.l))if(c&64){d=[11,11,1,2,3,4,12,13,14,15,5,6,7,8,9,10][(e&7)<<1|c>>5&1];a=c&16?4*((c&14)>>1):
0;c=b.g;switch(b.style.get()){case 4:d=c.row;break;case 3:if(d!=c.row){if(d<c.g&&(d=c.g,d==c.row))break;var f=1+c.row-c.g,k=1+d-c.g;m3(c,k,f,c.g);b=f;e=c.g;k<f?(f=k+e-f,0<f&&(b+=f,e-=f)):(f=f+e-k,0<f&&(e-=f));n3(c,b,e)}}c.row=d;c.i=a+1}else switch(e&7){case 1:switch(c&112){case 32:l3(b.g,0,32);break a;case 48:57==c?(d=b.g,k3(d).Sd=0,32>d.i&&d.i++):l3(b.g,1,c&15)}break;case 2:c&32&&l3(b.g,2,c&31);break;case 3:c&32&&l3(b.g,3,c&31);break;case 4:case 5:if(32<=c&&47>=c)switch(c){case 32:r3(b);break;case 33:d=
b.g;1<d.i&&(--d.i,k3(d).Sd=0);break;case 36:d=b.g;b=k3(d);for(a=0;15>=a;a++)for(c=0;32>=c;c++)if(d.l[a][c]==b){for(;32>=c;c++)d.l[a][c].reset();break}break;case 37:q3(b,2,d);break;case 38:q3(b,3,d);break;case 39:q3(b,4,d);break;case 40:l3(b.g,0,32);break;case 41:b.style.set(2);b.g=b.i;b.g.g=0;b.g.style=b.style;b.o.mode=1<<b.g.o;break;case 42:d=b.D;d.g=15;d.style.set(4);o3(d);s3(b);break;case 43:s3(b);break;case 44:a=b.i;switch(b.style.get()){case 1:case 2:case 3:j3(a,d)}n3(a,0,15);break;case 45:b:{a=
b.g;switch(b.style.get()){default:case 2:case 1:break b;case 4:if(15>a.row){++a.row;a.i=1;break b}case 3:}2>a.g&&(a.g=2,a.row<a.g&&(a.row=a.g));b=a.row-a.g+1;j3(a,d);m3(a,b,b+1,a.g-1);n3(a,a.row,1)}break;case 46:n3(b.l,0,15);break;case 47:j3(b.i,d),b.l.updateTime(b.o.i+0),d=b.l,b.l=b.i,b.i=d,r3(b)}break;case 7:switch(c){case 33:case 34:case 35:d=b.g,32<(d.i+=c&3)&&(d.i=32)}}},t3=function(a,b,c,d,e,f,k){var l=f[0],m=k[l.getAttribute("p")];
if(1==m.Zc){var n=f[1],p=f[2],r=f[3];l.getAttribute("p");l.getAttribute("t");n.getAttribute("t");p.getAttribute("t");r.getAttribute("t");f=g.Td("RUBY");l=l.textContent;var u=g.Td("SPAN");u.innerText=l;f.appendChild(u);n.getAttribute("p");u=g.Td("RP");l=n.textContent;u.innerText=l;f.appendChild(u);k=k[p.getAttribute("p")];l=p.textContent;p=g.Td("RT");p.innerText=l;f.appendChild(p);l=k.Zc;if(10==l||11==l||12==l||13==l||14==l)if(g.Ch(p,"text-emphasis","filled circle"),g.Ch(p,"webkit-text-emphasis","filled circle"),
k.Zc==k.Zc==11||13==k.Zc)g.Ch(p,"webkit-text-emphasis-position","under left"),g.Ch(p,"text-emphasis-position","under left");if(4==k.Zc||7==k.Zc||12==k.Zc||14==k.Zc)g.Ch(f,"ruby-position","over"),g.Ch(f,"-webkit-ruby-position","before");else if(5==k.Zc||6==k.Zc||11==k.Zc||13==k.Zc)g.Ch(f,"ruby-position","under"),g.Ch(f,"-webkit-ruby-position","after");r.getAttribute("p");l=r.textContent;r=g.Td("RP");r.innerText=l;f.appendChild(r);return new R2(a,b,e,c,f,d,m)}switch(m.Zc){case 9:case 10:m.ze=1;break;
case 11:m.ze=2;break;case 12:m.ze=3;break;case 13:m.ze=4;break;case 14:m.ze=5}return new R2(a,b,e,c,l.textContent||"",d,m)},u3=function(){g.G.apply(this,arguments)},v3=function(a){u3.call(this);
this.l={};this.F={};this.H={};this.u="_"+T2++;this.A=a;this.D={};this.i=this.g=null;this.C=!0},w3=function(a,b){var c=a.getAttribute(b);
if(null!=c)return parseFloat(c)},x3=function(a,b){var c=a.getAttribute(b);
if(null!=c)return"1"==c},y3=function(a,b){var c=w3(a,b);
return void 0!=c?c:null},A3=function(a,b){var c=a.getAttribute(b);
if(null!=c)return z3.test(c),c},B3=function(a,b){var c={},d=b.getAttribute("ws");
g.Sa(c,d?a.H[d]:a.A);d=y3(b,"mh");null!=d&&(c.Iq=d);d=y3(b,"ju");null!=d&&(c.textAlign=d);d=y3(b,"pd");null!=d&&(c.Ae=d);d=y3(b,"sd");null!=d&&(c.uA=d);d=A3(b,"wfc");null!=d&&(c.windowColor=d);d=w3(b,"wfo");void 0!=d&&(c.windowOpacity=d/255);return c},C3=function(a,b){var c={},d=b.getAttribute("wp");
d&&g.Sa(c,a.F[d]);d=y3(b,"ap");null!=d&&(c.Tf=d);d=w3(b,"cc");null!=d&&(c.Ol=d);d=w3(b,"ah");null!=d&&(c.Qe=d);d=w3(b,"rc");null!=d&&(c.Hk=d);d=w3(b,"av");null!=d&&(c.Fg=d);return c},D3=function(a,b,c,d){var e={};
g.Sa(e,C3(a,b));g.Sa(e,B3(a,b));d?g.bc(e,a.A)?(d=a.u,e=a.A):d="_"+T2++:d=b.getAttribute("id")||"_"+T2++;a=w3(b,"t")+c;b=w3(b,"d")||0x8000000000000;if(2==e.Ae||3==e.Ae)c=e.Hk,e.Hk=e.Ol,e.Ol=c;return new S2(a,b,0,d,e)},E3=function(a,b,c,d,e,f,k){W2.call(this,a,b,c,d,e,f,k);
this.type=1},F3=function(a,b,c){this.C=c;
this.version=this.A=this.o=this.g=0;this.i=new DataView(a);this.l=[]},G3=function(a){var b=a.g;
a.g+=1;return a.i.getUint8(b)},H3=function(a){var b=a.g;
a.g+=4;return a.i.getUint32(b)},I3=function(a,b){u3.call(this);
this.i=a;this.track="CC3"==b.l?4:0;this.g=new c3;this.g.l=1<<this.track},K3=function(a){if(g.v(a))return!1;
a=new F3(a,8,0);return J3(a)},J3=function(a){if(!(a.g<a.i.byteLength)||1380139777!=H3(a))return!1;
a.version=G3(a);if(1<a.version)return!1;G3(a);G3(a);G3(a);return!0},L3=function(a,b,c,d,e,f,k){W2.call(this,a,b,c,d,e,f,k);
g.J(this.element,"ytp-caption-window-rollup");this.type=2;this.F=[];this.I=this.H=this.fa=0;this.M=NaN;this.ya=0;this.Ga=null;this.ea=new g.M(this.CK,433,this);g.H(this,this.ea)},Epa=function(a,b){return(a.u?b.offsetHeight:b.offsetWidth)+1},Fpa=function(a){if(isNaN(a.M)){var b=a.l.Ol;
if(b){var c=g.Td("SPAN");g.ce(c,"\u2013".repeat(b));g.Ch(c,X2(a,a.l.wb));a.A.appendChild(c);a.M=c.offsetWidth;a.A.removeChild(c)}else a.M=0}return a.M},Gpa=function(a,b){if(!b)return"";
a.u&&1!=a.o.params.uA&&(b*=-1);return"translate"+(a.u?"X":"Y")+"("+b+"px)"},M3=function(a){a.F=[].concat(g.fa(document.getElementsByClassName("caption-visual-line")));
for(var b=a.o.params.Hk,c=0,d=0,e=a.F.length-1;c<b&&-1<e;){var f=a.F[e];d+=a.u?f.offsetWidth:f.offsetHeight;c++;e--}a.F.length<b&&(d*=b/a.F.length);a.H=d;a.I=Math.max(Fpa(a),a.ya,Epa(a,a.A))},Hpa=function(a,b){M3(a);
var c=a.F.reduce(function(e,f){return(a.u?f.offsetWidth:f.offsetHeight)+e},0);
c=a.H-c;if(c!=a.fa){var d=0<c&&0==a.fa;b||isNaN(c)||d||(g.J(a.element,"ytp-rollup-mode"),g.vo(a.ea));g.Ch(a.A,"transform",Gpa(a,c));a.fa=c}M3(a)},N3=function(){u3.call(this)},O3=function(a,b,c,d,e,f,k,l,m){switch(k.tagName){case "b":l.bold=!0;
break;case "i":l.Pe=!0;break;case "u":l.underline=!0}for(var n=0;n<k.childNodes.length;n++){var p=k.childNodes[n];if(3==p.nodeType){p=new R2(b,c,d,e.id,p.nodeValue,f||0<n,g.Yb(l)?void 0:l);m.push(p);var r=e;g.H(r,p);r.g.push(p)}else r={},g.Sa(r,l),O3(a,b,c,d,e,!0,p,r,m)}},P3=function(a){var b=0;
a=g.q(a.split(":"));for(var c=a.next();!c.done;c=a.next())b=60*b+parseFloat(c.value);return 1E3*b},Q3=function(a,b,c,d){d=Object.assign({Iq:0},d);
return new S2(a,b,c,"_"+T2++,d)},R3=function(a){g.G.call(this);
this.i=a;this.g=null},U3=function(a){g.RK.call(this,a);
this.u=g.X(a);this.l=a.getVideoData();this.xa=g.pK(a);this.I=a;var b=null,c=g.gp("yt-html5-player-modules::subtitlesModuleData");c&&(b=new g.Ro(c));this.ba=b;this.o={wb:{}};this.A={wb:{}};this.H=[];this.M={};this.V={};this.P=!1;this.na=g.iV(this.l,this.I);this.ya=!!this.l.captionTracks.length;this.Ba=!!this.l.ij;this.ka="3"==this.u.l;b=a.app.u;c=!(!b||!b.Uk());this.wa=!(!b||!b.Bh());this.C=this.ka&&c&&!this.na;this.R=!this.C&&this.ka&&this.wa&&this.na;this.i=this.D=this.F=this.O=this.ea=null;this.Z=
new R3(this.u);g.H(this,this.Z);c=b=this.g=null;this.C||(b=new g.oo(this.JA,void 0,this),g.H(this,b),c=new g.M(this.bM,2E3,this),g.H(this,c));this.X=b;this.fa=c;this.aa=new g.Ls(this);g.H(this,this.aa);this.C||this.aa.K(a,"resize",this.Ns);this.aa.K(a,"onPlaybackAudioChange",this.bI);this.aa.K(a,g.pE("captions"),this.WE,this);this.aa.K(a,"crx_captions",this.XE,this);S3(this,T3(this,"display-settings")||{})},V3=function(a){if(1==a.u.Yf||1==a.l.Yf||"alwayson"==g.RB(a.l,"yt:cc"))return!0;
if(2==a.u.Yf){var b=T3(a,"module-enabled");if(null!=b)return!!b}if(a.l.captionTracks.length)var c=a.player.getAudioTrack().Uo;return"ON"==c||"on"==g.RB(a.l,"yt:cc")},W3=function(a,b){if(a.g&&(void 0===b||!b)||!a.l.captionTracks.length)return!1;
var c=a.player.getAudioTrack();return!!c.Wl||"FORCED_ON"==c.Uo},Y3=function(a,b){if(a.i){if(a.D&&a.D.g)return a.D.g;
var c=b;c||(c=a.Ba?!1:a.ya?!1:!0);c=F2(a.i.i,c);for(var d=[a.l.Xf,a.u.Xf,g.RB(a.l,"yt:cc_default_lang")],e=0;e<d.length;e++)for(var f=0;f<c.length;f++)if(D2(c[f])==d[e])return c[f];return a.D&&a.D.lp?a.D.lp:(d=c.find(function(k){return k.isDefault}))?d:c[0]||X3(a)}return null},X3=function(a){return a.D&&a.D.Wl},Z3=function(a){var b=X3(a);
return!!b&&a.g==b},$3=function(a,b){for(var c=a.I.app.u.ha().textTracks,d=a.g.toString(),e=0;e<c.length;e++){var f=c[e];
f.id==d&&(b?"showing"!=f.mode&&(f.mode="showing"):"showing"==f.mode&&(f.mode="disabled"))}},b4=function(a,b,c){a.loaded&&a.unload();
null!=c&&(a.P=c,a.P&&a4(a,"module-enabled",!!b));a.g=b;W3(a)&&(a.g=X3(a));a.load()},Ipa=function(a,b){var c=a.xa.getVideoContentRect(!0).height;
if(!c)return null;var d=a.xa.getPlayerSize();switch(null!=b.params.Iq?b.params.Iq:1<b.g.length?1:0){case 1:return new E3(b,a.o,a.A,c,d.width,d.height,a.u.experiments);case 2:return new L3(b,a.o,a.A,c,d.width,d.height,a.u.experiments);default:return new W2(b,a.o,a.A,c,d.width,d.height,a.u.experiments)}},S3=function(a,b,c){var d=c4.wb;
a.o={};g.Sa(a.o,c4);a.o.wb={};g.Sa(a.o.wb,d);a.A={wb:{}};var e=b.backgroundOverride?a.A:a.o,f=b.background||d.background;z3.test(f);e.wb.background=f;e=b.colorOverride?a.A:a.o;f=b.color||d.color;z3.test(f);e.wb.color=f;e=b.windowColorOverride?a.A:a.o;f=b.windowColor||c4.windowColor;z3.test(f);e.windowColor=f;e=b.backgroundOpacityOverride?a.A:a.o;f=b.backgroundOpacity;null==f&&(f=d.backgroundOpacity);e.wb.backgroundOpacity=f;e=b.fontSizeIncrementOverride?a.A:a.o;f=b.fontSizeIncrement;null==f&&(f=d.fontSizeIncrement);
e.wb.fontSizeIncrement=f;f=b.fontStyleOverride?a.A:a.o;e=b.fontStyle;null==e&&(e=d.bold&&d.Pe?3:d.bold?1:d.Pe?2:0);f=f.wb;switch(e){case 1:f.bold=!0;delete f.Pe;break;case 2:delete f.bold;f.Pe=!0;break;case 3:f.bold=!0;f.Pe=!0;break;default:delete f.bold,delete f.Pe}e=b.textOpacityOverride?a.A:a.o;f=b.textOpacity;null==f&&(f=d.textOpacity);e.wb.textOpacity=f;e=b.windowOpacityOverride?a.A:a.o;f=b.windowOpacity;null==f&&(f=c4.windowOpacity);e.windowOpacity=f;e=b.charEdgeStyleOverride?a.A:a.o;f=b.charEdgeStyle;
null==f&&(f=d.charEdgeStyle);e.wb.charEdgeStyle=f;e=b.fontFamilyOverride?a.A:a.o;f=b.fontFamily;null==f&&(f=d.fontFamily);e.wb.fontFamily=f;a.loaded&&a.Ns();c&&a4(a,"display-settings",b)},e4=function(a,b){if(b&&!a.F){var c=U2({Ae:0,
lang:"en"});a.F=[c,new R2(c.start,c.end-c.start,0,c.id,"Captions look like this")];g.wK(a.player,a.F)}else!b&&a.F&&(d4(a,a.F),a.F=null)},d4=function(a,b){g.yK(a.player,b);
(0,g.A)(b,function(c){g.db(this.H,c)},a);
a.X.Jj()},T3=function(a,b){if(!a.ba)return null;
try{var c=a.ba.get(b)}catch(d){a.ba.remove(b)}return c},a4=function(a,b,c){if(a.ba)try{a.ba.set(b,c)}catch(d){}};
g.zC.prototype.kj=g.da(13,function(){for(var a=g.Gd(document,"track",void 0,this.g),b=0;b<a.length;b++)g.Yd(a[b])});
g.ZW.prototype.kj=g.da(12,function(){this.g.kj()});
g.zC.prototype.Uk=g.da(11,function(){return!!this.g.textTracks});
g.ZW.prototype.Uk=g.da(10,function(){return this.g.Uk()});
g.zC.prototype.dj=g.da(9,function(a){for(var b=0;b<a.length;b++)this.g.appendChild(a[b])});
g.ZW.prototype.dj=g.da(8,function(a){this.g.dj(a)});
g.qC.prototype.Bh=g.da(7,function(){});
g.zC.prototype.Bh=g.da(6,function(){return!(!this.g.textTracks||!this.g.textTracks.addEventListener)});
g.ZW.prototype.Bh=g.da(5,function(){return this.g.Bh()});
g.Kz.prototype.Nq=g.da(3,function(a){return a?this.toString()==a.toString():!1});
g.Gt.prototype.jm=g.da(2,function(a){return(a=this.gg(a))?a.i:0});
g.Bw.prototype.jm=g.da(1,function(){return 0});
var Jpa=/^(ar|ckb|dv|he|iw|fa|nqo|ps|sd|ug|ur|yi|.*[-_](Adlm|Arab|Hebr|Nkoo|Rohg|Thaa))(?!.*[-_](Latn|Cyrl)($|-|_))($|-|_)/i,spa=/#(.)(.)(.)/,rpa=/^#(?:[0-9a-f]{3}){1,2}$/i,z3=/^#(?:[0-9a-f]{3}){1,2}$/i;g.t(H2,g.G);H2.prototype.pz=function(){return!1};
H2.prototype.T=function(){this.Gg();g.G.prototype.T.call(this)};
g.t(I2,H2);I2.prototype.Fq=function(a,b,c){b=this.Fj(a,b);var d=(0,g.y)(function(e){this.g=null;c(e.responseText,a)},this);
this.Gg();this.g=g.Uq(b,{format:"RAW",onSuccess:d,withCredentials:!0})};
I2.prototype.Gq=function(a){if(this.l)for(var b=g.q(this.l.captionTracks),c=b.next();!c.done;c=b.next())G2(this.i,c.value);a()};
I2.prototype.Fj=function(a,b){var c=a.Gb(),d={fmt:b};a.g&&(d.tlang=D2(a));return g.Dq(c,d)};
I2.prototype.Gg=function(){this.g&&this.g.abort()};
J2.prototype.contains=function(a){a=g.pb(this.Ta,a);return 0<=a||0>a&&1==(-a-1)%2};
J2.prototype.length=function(){return this.Ta.length/2};
g.t(K2,g.G);g.h=K2.prototype;g.h.T=function(){g.G.prototype.T.call(this);this.i&&this.i.cancel()};
g.h.rx=function(a){var b=this;if(this.D.hi())var c=this.u.K(this.o,"progresssync",function(){b.D.index.Eb()&&(b.reset(),b.g=null,L2(b,b.o.getCurrentTime()),b.u.La(c))});
else L2(this,a)};
g.h.NF=function(){L2(this,this.o.getCurrentTime())};
g.h.reset=function(){this.A=new J2;this.i&&(this.i.cancel(),this.i=null)};
g.h.Gw=function(){var a;if(a=null!==this.g)a=this.g,a=a.g.Gf(a);!a||this.i||this.g&&30<this.g.startTime-this.o.getCurrentTime()||(a=this.g,a=a.g.pi(a),a.g[0].duration&&(this.A.contains(a.g[0].i)||M2(this,a),this.g=g.Wa(a.g)));this.H.start()};
g.h.xK=function(a){var b=!(this.C?a.response:a.responseText)||400<=a.status,c=g.Iw(a);c?(a=g.Qv(this.l,this.I,{}),b=this.l,g.Lv(b.i,a,c),b.requestId=a.get("req_id"),M2(this,this.l)):(b||null===this.F||(this.C?this.F(a.response,1E3*(this.l.g[0].startTime+this.o.ac())):this.F(a.responseText,1E3*(this.l.g[0].startTime+this.o.ac()))),this.i=this.l=null)};
g.t(N2,H2);g.h=N2.prototype;g.h.Fq=function(a,b,c){this.Gg();b=upa(this,a.getId());b||(b=a.i,b=this.g.i?P2(this,b,"386"):P2(this,b));if(b){var d=1E3*(b.index.jm(b.index.oe())-b.index.Ic(b.index.oe()));this.l=new K2(new g.gv,this.C,b,function(e,f){c(e,a,f,d)},this.A||g.$u(b.info),(0,g.y)(function(){this.l&&this.l.reset();
this.o=!0},this))}};
g.h.pz=function(){var a=this.o;this.o=!1;return a};
g.h.Gq=function(a){var b;this.A?b=[new g.Kz({id:"rawcc",languageCode:"rawcc",languageName:"CC1",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"}),new g.Kz({id:"rawcc",languageCode:"rawcc",languageName:"CC3",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"})]:b=this.g.i?O2(this,"386"):O2(this);b=g.q(b);for(var c=b.next();!c.done;c=b.next())G2(this.i,c.value);a()};
g.h.Gg=function(){this.l&&(this.l.dispose(),this.l=null)};
g.h.Fj=function(){return""};
g.t(Q2,H2);Q2.prototype.Fq=function(a,b,c){b=this.Fj(a,b);var d=(0,g.y)(function(e){this.g=null;c(e.responseText,a)},this);
this.Gg();this.g=g.Uq(b,{format:"RAW",onSuccess:d,withCredentials:!0})};
Q2.prototype.Gq=function(a){var b=this.o,c={type:"list",tlangs:1,v:this.l,vssids:1};this.A&&(c.asrs=1);b=g.Dq(b,c);c=(0,g.y)(function(d){this.g=null;if((d=d.responseXML)&&d.firstChild){for(var e=g.q(d.getElementsByTagName("track")),f=e.next();!f.done;f=e.next()){var k=f.value;f=k.getAttribute("lang_code");var l=k.getAttribute("lang_translated"),m=k.getAttribute("name"),n=k.getAttribute("kind"),p=k.getAttribute("id"),r="true"==k.getAttribute("lang_default"),u="true"==k.getAttribute("cantran");k=k.getAttribute("vss_id");
G2(this.i,new g.Kz({languageCode:f,languageName:l,name:m,kind:n,id:p,is_servable:!0,is_translateable:u,vss_id:k,is_default:r}))}d=d.getElementsByTagName("target");e=d.length;for(f=0;f<e;f++)l=d[f].getAttribute("lang_code"),m=d[f].getAttribute("lang_translated"),n=d[f].getAttribute("lang_original"),p=d[f].getAttribute("id"),r="true"==d[f].getAttribute("lang_default"),l={languageCode:l,languageName:m,languageOriginal:n,id:p,isDefault:r},this.C[l.languageCode]=l.languageName,this.u.push(l)}a()},this);
this.Gg();this.g=g.Uq(b,{format:"RAW",onSuccess:c,withCredentials:!0})};
Q2.prototype.Fj=function(a,b){var c=this.o,d={v:this.l,type:"track",lang:a.i,name:a.getName(),kind:a.o,fmt:b};a.g&&(d.tlang=D2(a));return c=g.Dq(c,d)};
Q2.prototype.Gg=function(){this.g&&this.g.abort()};var vpa=["left","right","center","justify"];var c4={windowColor:"#080808",windowOpacity:0,textAlign:2,Tf:7,Qe:50,Fg:100,wb:{background:"#080808",backgroundOpacity:.75,charEdgeStyle:0,color:"#fff",fontFamily:4,fontSizeIncrement:0,textOpacity:1,offset:1}};g.t(R2,g.mE);R2.prototype.toString=function(){return g.mE.prototype.toString.call(this)};g.t(S2,g.mE);S2.prototype.toString=function(){return g.mE.prototype.toString.call(this)};
var T2=0;g.t(W2,g.W);g.h=W2.prototype;g.h.MF=function(a,b){var c=g.Sh(this.element,this.element.parentElement);this.na=a-c.x;this.wa=b-c.y;g.J(this.element,"ytp-dragging")};
g.h.LF=function(a,b){var c=g.Vh(this.element),d=a-this.na-.02*this.Qa,e=b-this.wa-.02*this.Pa,f=(d+c.width/2)/this.X*3;f=Math.floor(g.rd(f,0,2));var k=(e+c.height/2)/this.xa*3;k=Math.floor(g.rd(k,0,2));var l=f+3*k;d=(d+f/2*c.width)/this.X;d=100*g.rd(d,0,1);c=(e+k/2*c.height)/this.xa;c=100*g.rd(c,0,1);this.o.params.Tf=l;this.o.params.Fg=c;this.o.params.Qe=d;this.l.Tf=l;this.l.Fg=c;this.l.Qe=d;this.Nz()};
g.h.KF=function(){g.io(this.element,"ytp-dragging")};
g.h.Nz=function(){this.yh(this.C)};
g.h.yh=function(a){var b=Math.min(this.Ev(),this.X),c=this.Dv(),d="";3==this.o.params.Ae&&(d="rotate(180deg)");g.Ch(this.element,{top:0,left:0,right:"",bottom:"",width:b?b+"px":"",height:c?c+"px":"","max-width":"96%","max-height":"96%",margin:"",transform:""});this.Io(a);a={transform:d,top:"",left:"",width:b?b+"px":"",height:c?c+"px":"","max-width":"","max-height":""};var e=.96*this.l.Qe+2;d=this.l.Tf;switch(d){case 0:case 3:case 6:a.left=e+"%";break;case 1:case 4:case 7:a.left=e+"%";e=this.A.offsetWidth;
b||e?(b=b||e+1,a.width=b+"px",a["margin-left"]=b/-2+"px"):a.transform+=" translateX(-50%)";break;case 2:case 5:case 8:a.right=100-e+"%"}b=.96*this.l.Fg+2;switch(d){case 0:case 1:case 2:a.top=b+"%";break;case 3:case 4:case 5:a.top=b+"%";(c=c||this.element.clientHeight)?(a.height=c+"px",a["margin-top"]=c/-2+"px"):a.transform+=" translateY(-50%)";break;case 6:case 7:case 8:a.bottom=100-b+"%"}g.Ch(this.element,a)};
g.h.Io=function(a){var b;for(b=0;b<a.length&&a[b]==this.C[b];b++);if(this.O||this.C.length>b)b=0,this.O=!1,this.C=[],this.D=this.V=this.R=null,g.Wd(this.A);for(;b<a.length;b++)$2(this,a[b])};
g.h.Ev=function(){return 0};
g.h.Dv=function(){return 0};
g.h.toString=function(){return g.W.prototype.toString.call(this)};a3.prototype.u=function(){};c3.prototype.clear=function(){this.o=this.i=this.mode=0;this.g=[];this.reset()};
c3.prototype.reset=function(){this.mode=0;this.u.reset(0);this.A.reset(1)};
var d3=[128,1,2,131,4,133,134,7,8,137,138,11,140,13,14,143,16,145,146,19,148,21,22,151,152,25,26,155,28,157,158,31,32,161,162,35,164,37,38,167,168,41,42,171,44,173,174,47,176,49,50,179,52,181,182,55,56,185,186,59,188,61,62,191,64,193,194,67,196,69,70,199,200,73,74,203,76,205,206,79,208,81,82,211,84,213,214,87,88,217,218,91,220,93,94,223,224,97,98,227,100,229,230,103,104,233,234,107,236,109,110,239,112,241,242,115,244,117,118,247,248,121,122,251,124,253,254,127,0,129,130,3,132,5,6,135,136,9,10,139,
12,141,142,15,144,17,18,147,20,149,150,23,24,153,154,27,156,29,30,159,160,33,34,163,36,165,166,39,40,169,170,43,172,45,46,175,48,177,178,51,180,53,54,183,184,57,58,187,60,189,190,63,192,65,66,195,68,197,198,71,72,201,202,75,204,77,78,207,80,209,210,83,212,85,86,215,216,89,90,219,92,221,222,95,96,225,226,99,228,101,102,231,232,105,106,235,108,237,238,111,240,113,114,243,116,245,246,119,120,249,250,123,252,125,126,255];f3.prototype.set=function(a){this.g=a};
f3.prototype.get=function(){return this.g};
g3.prototype.clear=function(){this.g=0};
g3.prototype.update=function(){this.g=2==this.g?1:0};
g3.prototype.matches=function(a,b){return 0!=this.g&&a==this.l&&b==this.i};
h3.prototype.dg=function(a){this.Sd=a.Sd;this.timestamp=a.timestamp};
h3.prototype.reset=function(){this.timestamp=this.Sd=0};
i3.prototype.updateTime=function(a){for(var b=1;15>=b;++b)for(var c=1;32>=c;++c)this.l[b][c].timestamp=a};
i3.prototype.debugString=function(){for(var a="\n",b=1;15>=b;++b){for(var c=1;32>=c;++c){var d=this.l[b][c];a=0==d.Sd?a+"_":a+String.fromCharCode(d.Sd)}a+="\n"}return a};
i3.prototype.reset=function(a){for(var b=0;15>=b;b++)for(var c=0;32>=c;c++)this.l[b][c].reset();this.o=a;this.g=0;this.i=this.row=1};
var zpa=[32,33,34,35,36,37,38,39,40,41,225,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,233,93,237,243,250,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,231,247,209,241,9632],Apa=[174,176,189,191,8482,162,163,9834,224,32,232,226,234,238,244,251],Bpa=[193,201,211,218,220,252,8216,161,42,39,9473,169,8480,183,8220,8221,192,194,199,200,202,203,235,
206,207,239,212,217,249,219,171,187],Cpa=[195,227,205,204,236,210,242,213,245,123,125,92,94,95,124,126,196,228,214,246,223,165,164,9475,197,229,216,248,9487,9491,9495,9499];p3.prototype.reset=function(a,b){this.u=b;this.style.set(2);this.i=this.A;this.l=this.C;this.g=this.i;var c=(a<<2)+(b<<1);this.A.reset(c);this.C.reset(c);this.D.reset((a<<2)+(b<<1)+1)};
b3.prototype.reset=function(a){this.u=a;this.g.clear();this.o=this.l;this.l.reset(a,0);this.A.reset(a,1)};g.t(u3,g.G);u3.prototype.reset=function(){};g.t(v3,u3);v3.prototype.reset=function(){this.D={};this.i=this.g=null;this.C=!0};
v3.prototype.o=function(a,b){var c=a.firstChild;c.getAttribute("format");b=b||0;Number.isFinite(b);c=Array.from(c.childNodes);c=g.q(c);for(var d=c.next();!d.done;d=c.next())if(d=d.value,1==d.nodeType)switch(d.tagName){case "head":var e=d;break;case "body":var f=d}if(e)for(e=Array.from(e.childNodes),e=g.q(e),c=e.next();!c.done;c=e.next())if(c=c.value,1==c.nodeType)switch(c.tagName){case "pen":d=c.getAttribute("id");var k=this.l,l={},m=c.getAttribute("p");m&&g.Sa(l,this.l[m]);m=x3(c,"b");null!=m&&(l.bold=
m);m=x3(c,"i");null!=m&&(l.Pe=m);m=x3(c,"u");null!=m&&(l.underline=m);m=y3(c,"et");null!=m&&(l.charEdgeStyle=m);m=y3(c,"of");null!=m&&(l.offset=m);m=A3(c,"bc");null!=m&&(l.background=m);m=A3(c,"ec");null!=m&&(l.zu=m);m=A3(c,"fc");null!=m&&(l.color=m);m=y3(c,"fs");null!=m&&0!=m&&(l.fontFamily=m);m=w3(c,"sz");void 0!=m&&(l.fontSizeIncrement=m/100-1);m=w3(c,"bo");void 0!=m&&(l.backgroundOpacity=m/255);m=w3(c,"fo");void 0!=m&&(l.textOpacity=m/255);m=y3(c,"rb");null!=m&&10!=m&&(l.Zc=10<m?m-1:m);m=y3(c,
"hg");null!=m&&(l.RD=m);c=y3(c,"te");null!=c&&(2==c&&(l.bold=!1,c=1),l.ze=c);k[d]=l;break;case "ws":d=c.getAttribute("id");this.H[d]=B3(this,c);break;case "wp":d=c.getAttribute("id"),this.F[d]=C3(this,c)}if(f){e=b;c=[];f=Array.from(f.childNodes);f=g.q(f);for(d=f.next();!d.done;d=f.next())if(d=d.value,1==d.nodeType)switch(d.tagName){case "w":this.g=D3(this,d,e,!1);g.H(this,this.g);(d=this.D[this.g.id])&&d.end>this.g.start&&(d.end=this.g.start);this.D[this.g.id]=this.g;c.push(this.g);break;case "p":var n=
e;k=[];l=d.getAttribute("w")||this.u;m=!!x3(d,"a");n=(w3(d,"t")||0)+n;var p=w3(d,"d")||5E3;m||(!this.C&&this.i&&this.i.windowId==l&&this.i.end>n&&(this.i.end=n),this.i&&"\n"==this.i.text&&(this.i.text=""));var r=m?6:5,u=this.l[d.getAttribute("p")],z=[].concat(g.fa(d.childNodes));z.length&&(this.C=null!=d.getAttribute("d"));for(var D=0;D<z.length;D++){var E=z[D];0<D&&(m=!0);var F=void 0;1==E.nodeType&&(F=E);if(F&&"s"==F.tagName)if((E=this.l[F.getAttribute("p")])&&E.Zc)1==E.Zc?(F=t3(n,p,l,m,r,z.slice(D,
D+4),this.l),D+=3):F=t3(n,p,l,m,r,[F],this.l);else{var L=F;F=n;E=p;var ba=l,qa=m,ya=r,ib=L.textContent?L.textContent:"",xe=this.l[L.getAttribute("p")];L=w3(L,"t")||0;F=new R2(F+L,E-L,ya,ba,ib,qa,xe)}else F=new R2(n,p,r,l,E.textContent||"",m,u);k.push(F);this.i=F}if(0<k.length)for(k[0].windowId==this.u&&(this.g=D3(this,d,e,!0),g.H(this,this.g),c.push(this.g)),d=g.q(k),k=d.next();!k.done;k=d.next())k=k.value,k.windowId=this.g.id,l=this.g,g.H(l,k),l.g.push(k),c.push(k)}e=c}else e=[];return e};g.t(E3,W2);E3.prototype.Io=function(a){var b=this.o.g;W2.prototype.Io.call(this,a);for(a=a.length;a<b.length;a++){var c=b[a];if(f&&c.g==e)var d=f;else{d={};g.Sa(d,c.g);g.Sa(d,Kpa);var e=c.g;var f=d}$2(this,c,d)}};
var Kpa={PD:!0};g.t(F3,a3);F3.prototype.u=function(a,b,c,d,e){if(c<d){var f="_"+T2++;c=c/1E3-this.C;d=d/1E3-this.C;a=new S2(c,d-c,5,f,{textAlign:0,Tf:0,Qe:2.5*b,Fg:5.33*a});e=new R2(c,d-c,5,f,e);this.l.push(a);this.l.push(e)}};
g.t(I3,u3);I3.prototype.o=function(a){a=new F3(a,a.byteLength,this.i);if(J3(a)){for(;a.g<a.i.byteLength;)for(0==a.version?a.o=H3(a)*(1E3/45):1==a.version&&(a.o=4294967296*H3(a)+H3(a)),a.A=G3(a);0<a.A;a.A--){var b=G3(a),c=G3(a),d=G3(a);b&4&&(b&3)==this.track&&(0==this.track||1==this.track)&&(b=this.g,b.g.push({time:a.o,type:this.track,tu:c,uu:d,order:b.g.length}))}ypa(this.g,a);return a.l}return[]};
I3.prototype.reset=function(){this.g.clear()};g.t(L3,W2);g.h=L3.prototype;g.h.Nz=function(){g.wo(this.ea)};
g.h.CK=function(){g.io(this.element,"ytp-rollup-mode");this.yh(this.Ga,!0)};
g.h.Dv=function(){return this.u?this.I:this.H};
g.h.Ev=function(){return this.u?this.H:this.I};
g.h.yh=function(a,b){this.Ga=a;if(this.o.params.Hk){for(var c=0,d=0;d<this.C.length&&c<a.length;d++)this.C[d]==a[c]&&c++;0<c&&c<a.length&&(a=this.C.concat(a.slice(c)));this.ya=this.I;this.H=this.I=0;W2.prototype.yh.call(this,a);Hpa(this,b);W2.prototype.yh.call(this,a)}else W2.prototype.yh.call(this,a)};g.t(N3,u3);
N3.prototype.o=function(a,b){for(var c=[],d=a.split(Lpa),e=1;e<d.length;e++){var f=d[e],k=b;if(""!=f&&!Mpa.test(f)){var l=f4.exec(f);if(l&&4<=l.length){var m=P3(l[1]),n=P3(l[2])-m;m+=k;var p,r=p=void 0,u=void 0,z=void 0,D=l[3];l={textAlign:2};D=g.q(D?D.split(" "):[]);for(var E=D.next();!E.done;E=D.next())if(E=E.value.split(":"),2==E.length){var F=E[1];switch(E[0]){case "line":E=F.split(",");E[0].endsWith("%")&&(z=E[0],l.Fg=Number.parseInt(z,10),2==E.length&&(u=E[1].trim()));break;case "position":E=F.split(",");
r=E[0];l.Qe=Number.parseInt(r,10);2==E.length&&(p=E[1].trim());break;case "align":switch(F){case "start":l.textAlign=0;break;case "middle":l.textAlign=2;break;case "end":l.textAlign=1}}}z||(l.Fg=100,u||(u="end"));if(!r)switch(l.textAlign){case 0:l.Qe=0;break;case 1:l.Qe=100;break;default:l.Qe=50}r=0;switch(u){case "center":r+=3;break;case "end":r+=6;break;default:r+=0}switch(p){case "line-left":r+=0;break;case "center":r+=1;break;case "line-right":r+=2;break;default:switch(l.textAlign){case 0:r+=
0;break;case 2:r+=1;break;case 1:r+=2}}l.Tf=0>r||8<r?7:r;p=l;f=f.substring(f4.lastIndex).replace(/[\x01-\x09\x0b-\x1f]/g,"");r=p;p=f;f={};if(0>p.indexOf("<")&&0>p.indexOf("&"))k=Q3(m,n,5,r),n=new R2(m,n,5,k.id,p,!1,g.Yb(f)?void 0:f),c.push(k),c.push(n),g.H(k,n),k.g.push(n);else for(u=p.split(Npa),1==u.length?(p=5,r=Q3(m,n,p,r)):(z=p=6,r=Object.assign({Ol:32},r),r=new S2(m,n,z,"_"+T2++,r)),c.push(r),z=m,l=0;l<u.length;l++)D=u[l],0==l%2?(E=g.ko("<html>"+D+"</html>"),E.getElementsByTagName("parsererror").length?
(F=E.createElement("span"),F.appendChild(E.createTextNode(D))):F=E.firstChild,O3(this,z,n-(z-m),p,r,0<l,F,f,c)):z=P3(D)+k}f4.lastIndex=0}}return c};
var Mpa=/^NOTE/,Lpa=/(?:\r\n|\r|\n){2,}/,f4=RegExp("^((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})[\\t ]+--\x3e[\\t ]+((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})(?:[\\t ]*)(.*)(?:\\r\\n|\\r|\\n)","gm"),Npa=/<((?:[\d]{2}:)?[\d]{2}:[\d]{2}\.[\d]{3})>/;g.t(R3,g.G);R3.prototype.clear=function(){this.g&&this.g.dispose();this.g=null};
R3.prototype.reset=function(){this.g&&this.g.reset()};
R3.prototype.T=function(){this.clear();g.G.prototype.T.call(this)};g.t(U3,g.RK);g.h=U3.prototype;g.h.T=function(){if(this.C||this.R){var a=this.I.app.u;a&&a.kj()}else e4(this,!1);g.RK.prototype.T.call(this)};
g.h.Mk=function(){return this.ka?this.C||this.R:W3(this)?!0:V3(this)};
g.h.load=function(){g.RK.prototype.load.call(this);this.D=this.player.getAudioTrack();if(this.i)this.g&&(this.Z.clear(),this.C?$3(this,!0):3!=this.player.getPresentingPlayerType()&&this.i.Fq(this.g,"srv3",(0,g.y)(this.jL,this))),this.g&&!Z3(this)?this.player.la("captionschanged",C2(this.g)):this.player.la("onCaptionsTrackListChanged");else{var a;this.na?a=new N2(this.l.ga,this.player):this.ya?a=new I2(this.u,this.l,this.player.getAudioTrack()):a=new Q2(this.l.ij,this.l.videoId,this.l.Xf||this.u.Xf||
g.RB(this.l,"yt:cc_default_lang")||this.u.Wb,this.l.So,this.u);this.i=a;g.H(this,this.i);a.Gq((0,g.y)(this.iL,this))}};
g.h.unload=function(){this.C&&this.g?$3(this,!1):(this.fa&&g.xo(this.fa),g.zK(this.player,"captions"),this.H=[],this.i&&this.i.Gg(),this.Z.clear(),this.F&&g.wK(this.player,this.F),this.Ns());g.RK.prototype.unload.call(this);var a=g.V(this.player.app);a&&a.o&&g.BD(a.o.l);this.player.la("captionschanged",{})};
g.h.iL=function(){var a;this.P||V3(this)?a=Y3(this,this.P):W3(this)&&(a=X3(this));if(this.C||this.R){for(var b=F2(this.i.i,!0),c=[],d=0;d<b.length;d++){var e=b[d],f={kind:"subtitles",label:g.Lz(e),srclang:D2(e),id:e.toString()};this.R||(f.src=this.i.Fj(e,"vtt"));e==a&&(f["default"]=1);c.push(g.Sd("TRACK",f))}this.I.app.u.dj(c);a=this.I.app.u.ha();this.wa&&this.aa.K(a.textTracks,"change",this.kL)}else!this.g&&a&&b4(this,a),this.player.la("onCaptionsTrackListChanged"),this.player.la("onApiChange")};
g.h.kL=function(){for(var a=this.I.app.u.ha().textTracks,b=null,c=0;c<a.length;c++)if("showing"==a[c].mode)a:{b=F2(this.i.i,!0);for(var d=0;d<b.length;d++)if(b[d].toString()==a[c].id){b=b[d];break a}b=null}(this.loaded?this.g:null)!=b&&b4(this,b,!0)};
g.h.LM=function(){!this.g&&this.C||this.unload()};
g.h.jL=function(a,b,c,d){if(a){this.i.pz()&&(this.H=[],g.zK(this.I,"captions"),this.X.Jj(),this.Z.reset());var e=this.Z;c=c||0;d=d||0;if(!g.v(a)){var f=new DataView(a);if(8<=f.byteLength&&1718909296==f.getUint32(4)&&(f=g.Zt(f,0,1835295092),a=a.slice(f.dataOffset,f.dataOffset+f.size),!K3(a))){a=new Uint8Array(a);f=[];for(var k=0,l=0;k<a.length;){var m=a[k++];if(128>m)f[l++]=String.fromCharCode(m);else if(191<m&&224>m){var n=a[k++];f[l++]=String.fromCharCode((m&31)<<6|n&63)}else if(239<m&&365>m){n=
a[k++];var p=a[k++],r=a[k++];m=((m&7)<<18|(n&63)<<12|(p&63)<<6|r&63)-65536;f[l++]=String.fromCharCode(55296+(m>>10));f[l++]=String.fromCharCode(56320+(m&1023))}else n=a[k++],p=a[k++],f[l++]=String.fromCharCode((m&15)<<12|(n&63)<<6|p&63)}a=f.join("")}}if(a)try{if(g.v(a)){if("WEBVTT"==a.substring(0,6)){b=a;var u=c;e.g||(e.g=new N3);var z=e.g.o(b,u);.01>Math.random()&&g.Sp(Error("Deprecated subtitles format in web player: WebVTT"));var D=z}else b:{z=a;u=g.ko(z);if(!u||!u.firstChild){var E=Error("Invalid caption track data");
E.params=z;throw E;}if("timedtext"==u.firstChild.tagName){if(3==parseInt(u.firstChild.getAttribute("format"),10)){if(!e.g){z={};var F=D2(b);F&&(z.lang=F,Jpa.test(F)&&(z.Ae=1));e.g=new v3(z,e.i)}D=e.g.o(u,c);break b}var L=Error("Unsupported subtitles format in web player (Format2)");L.params=z;throw L;}if("transcript"==u.firstChild.tagName){var ba=Error("Unsupported subtitles format in web player (Format1)");ba.params=z;throw ba;}var qa=Error("Invalid caption track data");qa.params=z;throw qa;}var ya=
D}else{D=a;u=c;F=d;if(!K3(D))throw Error("Invalid binary caption track data");e.g||(e.g=new I3(F,b));ya=e.g.o(D,u)}var ib=ya}catch(xe){g.N(xe),e.clear(),ib=[]}else ib=[];g.wK(this.player,ib);!this.P||this.R||Z3(this)||g.lz(this.u)||g.mz(this.u)||(g.xo(this.fa),ib=U2({Tf:0,Qe:5,Fg:5,Hk:2,textAlign:0,Ae:0,lang:"en"}),this.O=[ib],e=["Click "," for settings"],this.ea||(ya=new g.cD(g.ZP()),g.H(this,ya),this.ea=ya.element),ya=ib.end-ib.start,(b=g.Lz(this.g))&&this.O.push(new R2(ib.start,ya,0,ib.id,b)),
this.O.push(new R2(ib.start,ya,0,ib.id,e[0]),new R2(ib.start,ya,0,ib.id,this.ea,!0),new R2(ib.start,ya,0,ib.id,e[1],!0)),g.wK(this.player,this.O),g.vo(this.fa));!this.P||this.R||Z3(this)||(a4(this,"module-enabled",!0),this.D&&(this.D.g=this.g),(ib=g.V(this.player.app))&&ib.o&&g.BD(ib.o.l));this.P=!1}};
g.h.WE=function(a){this.H.push(a);this.X.Jj()};
g.h.XE=function(a){g.db(this.H,a);this.i instanceof N2&&this.i.A&&g.yK(this.player,[a]);this.X.Jj()};
g.h.VL=function(a){if(a instanceof S2){var b=this.M[a.id];b&&b.o!=a&&(b.dispose(),delete this.M[a.id],b=null);b||(b=Ipa(this,a))&&(this.M[a.id]=b)}else b=a.windowId,this.V[b]||(this.V[b]=[]),this.V[b].push(a)};
g.h.bM=function(){d4(this,this.O);this.O=null};
g.h.JA=function(){this.X.stop();g.Zb(this.V);this.H.sort(g.oE);var a=this.H;if(this.F){var b=(0,g.Zd)(a,function(c){return-1==this.F.indexOf(c)},this);
b.length&&(a=b)}(0,g.A)(a,this.VL,this);g.Lb(this.M,function(c,d){this.V[d]?(c.element.parentNode||g.DK(this.player,c.element,4),c.yh(this.V[d])):(c.dispose(),delete this.M[d])},this)};
g.h.fM=function(){S3(this,{},!0)};
g.h.eD=function(){var a=c4.wb;a={background:a.background,backgroundOpacity:a.backgroundOpacity,charEdgeStyle:a.charEdgeStyle,color:a.color,fontFamily:a.fontFamily,fontSizeIncrement:a.fontSizeIncrement,fontStyle:a.bold&&a.Pe?3:a.bold?1:a.Pe?2:0,textOpacity:a.textOpacity,windowColor:c4.windowColor,windowOpacity:c4.windowOpacity};var b=T3(this,"display-settings")||{};null!=b.background&&(a.background=b.background);null!=b.backgroundOverride&&(a.backgroundOverride=b.backgroundOverride);null!=b.backgroundOpacity&&
(a.backgroundOpacity=b.backgroundOpacity);null!=b.backgroundOpacityOverride&&(a.backgroundOpacityOverride=b.backgroundOpacityOverride);null!=b.charEdgeStyle&&(a.charEdgeStyle=b.charEdgeStyle);null!=b.charEdgeStyleOverride&&(a.charEdgeStyleOverride=b.charEdgeStyleOverride);null!=b.color&&(a.color=b.color);null!=b.colorOverride&&(a.colorOverride=b.colorOverride);null!=b.fontFamily&&(a.fontFamily=b.fontFamily);null!=b.fontFamilyOverride&&(a.fontFamilyOverride=b.fontFamilyOverride);null!=b.fontSizeIncrement&&
(a.fontSizeIncrement=b.fontSizeIncrement);null!=b.fontSizeIncrementOverride&&(a.fontSizeIncrementOverride=b.fontSizeIncrementOverride);null!=b.fontStyle&&(a.fontStyle=b.fontStyle);null!=b.fontStyleOverride&&(a.fontStyleOverride=b.fontStyleOverride);null!=b.textOpacity&&(a.textOpacity=b.textOpacity);null!=b.textOpacityOverride&&(a.textOpacityOverride=b.textOpacityOverride);null!=b.windowColor&&(a.windowColor=b.windowColor);null!=b.windowColorOverride&&(a.windowColorOverride=b.windowColorOverride);
null!=b.windowOpacity&&(a.windowOpacity=b.windowOpacity);null!=b.windowOpacityOverride&&(a.windowOpacityOverride=b.windowOpacityOverride);return a};
g.h.OA=function(a,b){var c={};g.Sa(c,T3(this,"display-settings"));g.Sa(c,a);S3(this,c,b);this.player.N("captionssettingschanged")};
g.h.Ns=function(){!this.C&&this.loaded&&(g.Lb(this.M,function(a,b){a.dispose();delete this.M[b]},this),this.JA())};
g.h.Zb=function(a,b){switch(a){case "fontSize":if(isNaN(b))break;var c=g.rd(b,-2,4);this.OA({fontSizeIncrement:c});return c;case "reload":b&&!this.C&&b4(this,this.g,!0);break;case "stickyLoading":void 0!=b&&this.u.sb&&a4(this,"module-enabled",!!b);break;case "track":if(!this.i)return{};if(b){if(this.C)break;if(!g.Oa(b))break;if(g.Yb(b)){b4(this,null,!0);break}for(var d=F2(this.i.i,!0),e=0;e<d.length;e++){var f=d[e];f.i!=b.languageCode||c&&f.l!=b.languageName||(c=b.translationLanguage?qpa(f,b.translationLanguage):
f)}!c||c==this.g&&this.loaded||b4(this,c,!0)}else return this.loaded&&this.g&&!Z3(this)?C2(this.g):{};return"";case "tracklist":return this.i?(0,g.C)(F2(this.i.i,!(!b||!b.includeAsr)),function(k){return C2(k)}):[];
case "translationLanguages":return this.i?this.i.u:[];case "sampleSubtitles":this.C||void 0==b||e4(this,!!b)}};
g.h.getOptions=function(){var a="reload fontSize track tracklist translationLanguages sampleSubtitle".split(" ");this.u.sb&&a.push("stickyLoading");return a};
g.h.Hj=function(){var a=this.g;return a?{cc:a.A}:{}};
g.h.FM=function(){this.loaded&&this.g&&!Z3(this)?(a4(this,"module-enabled",!1),this.unload(),W3(this,!0)&&b4(this,X3(this),!1)):b4(this,Z3(this)||!this.g?Y3(this,!0):this.g,!0)};
g.h.bI=function(){var a=Z3(this);W3(this,a)?b4(this,this.player.getAudioTrack().Wl,!1):this.l.captionTracks.length&&(this.loaded&&this.unload(),this.Mk()&&(a?b4(this,Y3(this),!1):this.load()))};g.oV.captions=U3;})(_yt_player);
