(function(g){var window=this;var g4=function(a,b,c){var d=b.oa();g.K(a.element,"ytp-suggestion-set",!!d.videoId);var e=b.getPlaylistId();c=b.yc(c?c:"mqdefault.jpg");var f=b instanceof g.oB&&b.lengthSeconds?g.WQ(b.lengthSeconds):null,k=!!e;e=k&&"RD"==(new g.qE(e.substr(0,2),e.substr(2))).type;var l=b instanceof g.oB?b.sa:null;d={title:b.title,author:b.author,author_and_views:d.shortViewCount?b.author+" \u2022 "+d.shortViewCount:b.author,aria_label:b.ej||g.BN("Watch $TITLE",{TITLE:b.title}),duration:f,url:b.Ij(),is_live:l,is_list:k,
is_mix:e,background:c?"background-image: url("+c+")":""};b instanceof g.sE&&(d.playlist_length=b.getLength());a.update(d)},h4=function(a,b){g.hD.call(this,{B:"div",
W:["html5-endscreen","ytp-player-content",b||"base-endscreen"]});this.player=a;this.created=!1},i4=function(a){g.W.call(this,{B:"div",
W:["ytp-upnext","ytp-player-content"],L:{"aria-label":"{{aria_label}}"},J:[{B:"div",G:"ytp-cued-thumbnail-overlay-image",L:{style:"{{background}}"}},{B:"span",G:"ytp-upnext-top",J:[{B:"span",G:"ytp-upnext-header",U:"Up Next"},{B:"span",G:"ytp-upnext-title",U:"{{title}}"},{B:"span",G:"ytp-upnext-author",U:"{{author}}"}]},{B:"a",G:"ytp-upnext-autoplay-icon",L:{role:"button",href:"{{url}}","aria-label":"Play next video"},J:[{B:"svg",L:{height:"100%",version:"1.1",viewBox:"0 0 72 72",width:"100%"},J:[{B:"circle",
G:"ytp-svg-autoplay-circle",L:{cx:"36",cy:"36",fill:"#fff","fill-opacity":"0.3",r:"31.5"}},{B:"circle",G:"ytp-svg-autoplay-ring",L:{cx:"-36",cy:"36","fill-opacity":"0",r:"33.5",stroke:"#FFFFFF","stroke-dasharray":"211","stroke-dashoffset":"-211","stroke-width":"4",transform:"rotate(-90)"}},{B:"path",G:"ytp-svg-fill",L:{d:"M 24,48 41,36 24,24 V 48 z M 44,24 v 24 h 4 V 24 h -4 z"}}]}]},{B:"span",G:"ytp-upnext-bottom",J:[{B:"span",G:"ytp-upnext-cancel"},{B:"span",G:"ytp-upnext-paused",U:"Autoplay is paused"}]}]});
this.A=null;var b=this.i["ytp-upnext-cancel"];this.A=new g.W({B:"button",W:["ytp-upnext-cancel-button","ytp-button"],L:{tabindex:"0","aria-label":"Cancel autoplay"},U:"Cancel"});g.H(this,this.A);this.A.ca("click",this.gI,this);this.A.g(b);this.l=a;this.I=this.i["ytp-svg-autoplay-ring"];this.D=this.C=this.o=this.u=null;this.F=new g.M(this.Nl,5E3,this);g.H(this,this.F);this.H=0;this.K(this.i["ytp-upnext-autoplay-icon"],"click",this.VJ);this.qy();this.K(a,"autonavvisibility",this.qy);this.K(a,"mdxnowautoplaying",
this.lJ);this.K(a,"mdxautoplaycanceled",this.mJ);this.K(a,"mdxautoplayupnext",this.NA);3==this.l.getPresentingPlayerType()&&(a=(a=g.qK(g.kK(this.l)))?a.cD():null)&&this.NA(a)},j4=function(a,b){if(!a.o){g.gq("a11y-announce","Up Next "+a.u.title);
a.H=g.O();a.o=new g.M((0,g.y)(a.Ho,a,b),25);a.Ho(b);var c=b||g.R(g.X(a.l).experiments,"autoplay_time")||1E4;a.l.la("onAutonavCoundownStarted",c)}g.io(a.element,"ytp-upnext-autoplay-paused")},l4=function(a){k4(a);
a.H=g.O();a.Ho();g.J(a.element,"ytp-upnext-autoplay-paused")},k4=function(a){a.o&&(a.o.dispose(),a.o=null)},m4=function(a,b){b=void 0===b?!1:b;
if(g.Q(g.X(a.l).experiments,"autonav_notifications")&&b&&window.Notification&&document.hasFocus){var c=Notification.permission;"default"==c?Notification.requestPermission():"granted"!=c||document.hasFocus()||(c=a.u.oa(),a.Nl(),a.C=new Notification("Up Next",{body:c.title,icon:c.yc()}),a.D=a.K(a.C,"click",a.NJ),a.F.start())}k4(a);a.l.nextVideo(!1,b)},n4=function(a){h4.call(this,a,"subscribecard-endscreen");
var b=a.getVideoData();this.l=new g.W({B:"div",G:"ytp-subscribe-card",J:[{B:"img",G:"ytp-author-image",L:{src:b.Pd}},{B:"div",G:"ytp-subscribe-card-right",J:[{B:"div",G:"ytp-author-name",U:b.author},{B:"div",G:"html5-subscribe-button-container"}]}]});g.H(this,this.l);this.l.g(this.element);this.o=new g.gW("Subscribe",null,"Unsubscribe",null,!0,!1,b.Qf,b.subscribed,"trailer-endscreen",null,null,a);g.H(this,this.o);this.o.g(this.l.i["html5-subscribe-button-container"]);this.hide()},o4=function(a){var b=
g.X(a),c=g.fx||g.Fh?{style:"will-change: opacity"}:void 0,d=b.i,e=["ytp-videowall-still"];
b.g&&e.push("ytp-videowall-show-text");g.W.call(this,{B:"a",W:e,L:{href:"{{url}}",target:d?b.A:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}"},J:[{B:"div",G:"ytp-videowall-still-image",L:{style:"{{background}}"}},{B:"span",G:"ytp-videowall-still-info",J:[{B:"span",G:"ytp-videowall-still-info-bg",J:[{B:"span",G:"ytp-videowall-still-info-content",L:c,J:[{B:"span",G:"ytp-videowall-still-info-title",U:"{{title}}"},{B:"span",G:"ytp-videowall-still-info-author",
U:"{{author_and_views}}"},{B:"span",G:"ytp-videowall-still-info-live",U:"Live"},{B:"span",G:"ytp-videowall-still-info-duration",U:"{{duration}}"}]}]}]},{B:"span",W:["ytp-videowall-still-listlabel-regular","ytp-videowall-still-listlabel"],J:[{B:"span",G:"ytp-videowall-still-listlabel-icon"},"Playlist",{B:"span",G:"ytp-videowall-still-listlabel-length",J:[" (",{B:"span",U:"{{playlist_length}}"},")"]}]},{B:"span",W:["ytp-videowall-still-listlabel-mix","ytp-videowall-still-listlabel"],J:[{B:"span",G:"ytp-videowall-still-listlabel-mix-icon"},
"Mix",{B:"span",G:"ytp-videowall-still-listlabel-length",U:" (50+)"}]}]});this.A=d;this.l=a;this.o=null;this.u=new g.Ls(this);g.H(this,this.u);this.ca("click",this.D);this.ca("keypress",this.F);this.u.K(a,"videodatachange",this.C);g.X(a).F&&g.pO(a.app.O,this.element,this);this.C()},p4=function(a){g.GK(a.l,a.element);
var b=a.o.oa().videoId,c=a.o.getPlaylistId();g.mY(a.l.app,b,a.o.sd,c,void 0,void 0)},q4=function(a){h4.call(this,a,"videowall-endscreen");
this.H=a;this.C=0;this.o=[];this.D=this.u=this.A=null;this.F=this.R=!1;this.O=null;this.aa=new g.Ls(this);g.H(this,this.aa);this.I=new g.M(g.Ra(g.J,this.element,"ytp-show-tiles"),0);g.H(this,this.I);var b=new g.W({B:"button",W:["ytp-button","ytp-endscreen-previous"],L:{"aria-label":"Previous"},J:[g.FP()]});g.H(this,b);b.g(this.element);b.ca("click",this.AF,this);this.M=new g.cD({B:"div",G:"ytp-endscreen-content"});g.H(this,this.M);this.M.g(this.element);b=new g.W({B:"button",W:["ytp-button","ytp-endscreen-next"],
L:{"aria-label":"Next"},J:[g.GP()]});g.H(this,b);b.g(this.element);b.ca("click",this.zF,this);this.l=new i4(a);g.H(this,this.l);g.DK(this.player,this.l.element,4);this.hide()},r4=function(a){return g.EK(a.player)&&a.mu()&&!a.D},s4=function(a,b){return(0,g.C)(b.suggestions,function(c){c=g.kS(g.X(a.H),c);
g.H(a,c);return c})},t4=function(a){var b=a.Me();
b!=a.R&&(a.R=b,a.player.N("autonavvisibility"))},v4=function(a){g.RK.call(this,a);
this.g=null;this.i=new g.Ls(this);g.H(this,this.i);this.l=g.X(a);u4(a)?this.g=new q4(this.player):this.l.Ga?this.g=new n4(this.player):this.g=new h4(this.player);g.H(this,this.g);g.DK(this.player,this.g.element,4);this.Mz();this.i.K(a,"videodatachange",this.Mz,this);this.i.K(a,g.pE("endscreen"),this.QE,this);this.i.K(a,"crx_endscreen",this.RE,this)},u4=function(a){a=g.X(a);
return a.Ba&&!a.Ga};
g.t(h4,g.hD);h4.prototype.create=function(){this.created=!0};
h4.prototype.destroy=function(){this.created=!1};
h4.prototype.mu=function(){return!1};
h4.prototype.Me=function(){return!1};g.t(i4,g.W);g.h=i4.prototype;g.h.Nl=function(){this.C&&(this.F.stop(),this.La(this.D),this.D=null,this.C.close(),this.C=null)};
g.h.qy=function(){g.gD(this,this.l.Me())};
g.h.NJ=function(){window.focus();this.Nl()};
g.h.hide=function(){g.W.prototype.hide.call(this)};
g.h.Ho=function(a){a=a||g.R(g.X(this.l).experiments,"autoplay_time")||1E4;var b=Math.min(g.O()-this.H,a);a=Math.min(b/a,1);this.I.setAttribute("stroke-dashoffset",-211*(a+1));1<=a&&3!=this.l.getPresentingPlayerType()?m4(this,!0):this.o&&this.o.start()};
g.h.VJ=function(a){!g.be(this.A.element,g.es(a))&&g.nS(a,this.l)&&m4(this)};
g.h.gI=function(){g.mK(this.l,!0)};
g.h.lJ=function(a){this.l.getPresentingPlayerType();this.show();j4(this,a)};
g.h.NA=function(a){this.l.getPresentingPlayerType();this.u&&this.u.oa().videoId==a.oa().videoId||(this.u=a,g4(this,a,"hqdefault.jpg"))};
g.h.mJ=function(){this.l.getPresentingPlayerType();k4(this);this.hide()};
g.h.T=function(){k4(this);this.Nl();g.W.prototype.T.call(this)};g.t(n4,h4);g.t(o4,g.W);o4.prototype.D=function(a){g.nS(a,this.l,this.A,this.o.sd||void 0)&&p4(this)};
o4.prototype.F=function(a){switch(a.keyCode){case 13:case 32:g.js(a)||(p4(this),g.is(a))}};
o4.prototype.C=function(){var a=this.l.getVideoData(),b=g.X(this.l);this.A=a.Mb?!1:b.i};g.t(q4,h4);g.h=q4.prototype;g.h.create=function(){h4.prototype.create.call(this);var a=this.player.getVideoData();a&&(this.A=s4(this,a),this.u=a);this.If();this.aa.K(this.player,"appresize",this.If);this.aa.K(this.player,"onVideoAreaChange",this.If);this.aa.K(this.player,"videodatachange",this.BF);this.aa.K(this.player,"autonavchange",this.Rq);this.aa.K(this.player,"autonavcancel",this.yF);a=this.u.autonavState;a!=this.O&&this.Rq(a);this.aa.K(this.element,"transitionend",this.lL)};
g.h.destroy=function(){g.Ns(this.aa);g.tf(this.o);this.o=[];this.A=null;h4.prototype.destroy.call(this);g.io(this.element,"ytp-show-tiles");this.I.stop();this.O=this.u.autonavState};
g.h.mu=function(){return 1!=this.u.autonavState};
g.h.show=function(){h4.prototype.show.call(this);g.io(this.element,"ytp-show-tiles");g.X(this.player).g?g.wo(this.I):this.I.start();(this.F||this.D&&this.D!=this.u.clientPlaybackNonce)&&g.mK(this.player,!1);r4(this)?(t4(this),2==this.u.autonavState?g.Q(g.X(this.player).experiments,"fast_autonav_in_background")&&3==this.player.getVisibilityState()?m4(this.l,!0):j4(this.l):3==this.u.autonavState&&l4(this.l)):(g.mK(this.player,!0),t4(this))};
g.h.hide=function(){h4.prototype.hide.call(this);l4(this.l);t4(this)};
g.h.lL=function(a){g.es(a)==this.element&&this.If()};
g.h.If=function(){if(this.A&&this.A.length){g.J(this.element,"ytp-endscreen-paginate");var a=g.uK(this.H,!0),b=g.wD(this.H);b&&(b=b.Ac()?48:32,a.width-=2*b);var c=a.width/a.height,d=96/54,e=b=2,f=Math.max(a.width/96,2),k=Math.max(a.height/54,2),l=this.A.length,m=Math.pow(2,2);var n=l*m+(Math.pow(2,2)-m);n+=Math.pow(2,2)-m;for(n-=m;0<n&&(b<f||e<k);){var p=b/2,r=e/2,u=b<=f-2&&n>=r*m,z=e<=k-2&&n>=p*m;if((p+1)/r*d/c>c/(p/(r+1)*d)&&z)n-=p*m,e+=2;else if(u)n-=r*m,b+=2;else if(z)n-=p*m,e+=2;else break}d=
!1;n>=3*m&&6>=l*m-n&&(4<=e||4<=b)&&(d=!0);m=96*b;n=54*e;c=m/n<c?a.height/n:a.width/m;c=Math.min(c,2);m*=c;n*=c;m*=g.rd(a.width/m||1,1,1.21);n*=g.rd(a.height/n||1,1,1.21);m=Math.floor(Math.min(a.width,m));n=Math.floor(Math.min(a.height,n));a=this.M.element;g.Uh(a,m,n);g.Ch(a,{marginLeft:m/-2+"px",marginTop:n/-2+"px"});c=this.l;f=this.A[0];c.u=f;g4(c,f,"hqdefault.jpg");g.K(this.element,"ytp-endscreen-takeover",r4(this));t4(this);m+=4;n+=4;for(f=c=0;f<b;f++)for(k=0;k<e;k++)if(p=c,r=0,d&&f>=b-2&&k>=e-
2?r=1:0==k%2&&0==f%2&&(2>k&&2>f?0==k&&0==f&&(r=2):r=2),p=g.sd(p+this.C,l),0!=r){u=this.o[c];u||(u=new o4(this.player),this.o[c]=u,a.appendChild(u.element));z=Math.floor(n*k/e);var D=Math.floor(m*f/b),E=Math.floor(n*(k+r)/e)-z-4,F=Math.floor(m*(f+r)/b)-D-4;g.Kh(u.element,D,z);g.Uh(u.element,F,E);g.Ch(u.element,"transitionDelay",(k+f)/20+"s");g.K(u.element,"ytp-videowall-still-mini",1==r);g.K(u.element,"ytp-videowall-still-large",2<r);r=u;p=this.A[p];r.o!=p&&(r.o=p,g4(r,p,g.go(r.element,"ytp-videowall-still-large")?
"hqdefault.jpg":"mqdefault.jpg"),p=(p=p.sd)&&p.itct)&&(u=r.l,g.X(u).F&&g.qO(u.app.O,r.element,p));c++}g.K(this.element,"ytp-endscreen-paginate",c<l);for(b=this.o.length-1;b>=c;b--)e=this.o[b],g.Yd(e.element),g.sf(e);this.o.length=c}};
g.h.BF=function(){var a=this.player.getVideoData();this.u!=a&&(this.C=0,this.A=s4(this,a),this.u=a,this.If())};
g.h.zF=function(){this.C+=this.o.length;this.If()};
g.h.AF=function(){this.C-=this.o.length;this.If()};
g.h.dE=function(){return!!this.l.o};
g.h.Rq=function(a){1==a?(this.F=!1,this.D=this.u.clientPlaybackNonce,k4(this.l),this.Fa()&&this.If()):(this.F=!0,this.Fa()&&r4(this)&&(2==a?j4(this.l):3==a&&l4(this.l)))};
g.h.yF=function(a){if(a){for(a=0;a<this.o.length;a++)g.HK(this.H,this.o[a].element,!0);this.Rq(1)}else this.D=null,this.F=!1;this.If()};
g.h.Me=function(){return this.Fa()&&r4(this)};g.t(v4,g.RK);g.h=v4.prototype;g.h.Mk=function(){var a=this.player.getVideoData(),b=!!(a&&a.suggestions&&a.suggestions.length);b=!u4(this.player)||b;a=a.Lc;var c=g.NX(this.player.app);return b&&!a&&!c};
g.h.Me=function(){return this.g.Me()};
g.h.ZD=function(){return this.Me()?this.g.dE():!1};
g.h.T=function(){g.zK(this.player,"endscreen");g.RK.prototype.T.call(this)};
g.h.load=function(){g.RK.prototype.load.call(this);this.g.show()};
g.h.unload=function(){g.RK.prototype.unload.call(this);this.g.hide();this.g.destroy()};
g.h.QE=function(a){this.Mk()&&(this.g.created||this.g.create(),"load"==a.getId()&&this.load())};
g.h.RE=function(a){"load"==a.getId()&&this.loaded&&this.unload()};
g.h.Mz=function(){g.zK(this.player,"endscreen");var a=Math.max(1E3*(this.player.getVideoData().lengthSeconds-10),0);a=new g.mE(a,0x8000000000000,{id:"preload",namespace:"endscreen"});g.H(this,a);var b=new g.mE(0x8000000000000,0x8000000000000,{id:"load",priority:6,namespace:"endscreen"});g.H(this,b);g.wK(this.player,[a,b])};g.oV.endscreen=v4;})(_yt_player);
