(function(g){var window=this;var y5=function(a){g.hD.call(this,{B:"div",G:"ytp-miniplayer-ui"});this.player=a;this.H=!1;this.F=this.A=this.l=void 0;this.K(a,"minimized",this.wJ);this.K(a,"onStateChange",this.yM)},z5=function(a){g.RK.call(this,a);
this.g=new y5(this.player);this.g.hide();g.DK(this.player,this.g.element,4);a.app.F.g&&(this.load(),g.K(a.getRootNode(),"ytp-player-minimized",!0))};
g.t(y5,g.hD);g.h=y5.prototype;
g.h.show=function(){this.l=new g.oo(this.IF,null,this);this.l.start();if(!this.H){this.D=new g.oW(this.player,this);g.H(this,this.D);g.DK(this.player,this.D.element,4);this.D.A=.6;this.O=new g.sV(this.player);g.H(this,this.O);this.C=new g.W({B:"div",G:"ytp-miniplayer-scrim"});g.H(this,this.C);this.C.g(this.element);this.K(this.C.element,"click",this.Sy);var a=new g.W({B:"button",W:["ytp-miniplayer-close-button","ytp-button"],L:{"aria-label":"Close"},J:[g.KP()]});g.H(this,a);a.g(this.C.element);this.K(a.element,
"click",this.qx);this.u=new g.W({B:"div",G:"ytp-miniplayer-controls"});g.H(this,this.u);this.u.g(this.C.element);this.K(this.u.element,"click",this.Sy);var b=new g.W({B:"div",G:"ytp-miniplayer-button-container"});g.H(this,b);b.g(this.u.element);a=new g.W({B:"div",G:"ytp-miniplayer-play-button-container"});g.H(this,a);a.g(this.u.element);var c=new g.W({B:"div",G:"ytp-miniplayer-button-container"});g.H(this,c);c.g(this.u.element);this.M=new g.uT(this.player,this,!1);g.H(this,this.M);this.M.g(b.element);
b=new g.rT(this.player,this);g.H(this,b);b.g(a.element);this.I=new g.uT(this.player,this,!0);g.H(this,this.I);this.I.g(c.element);this.F=new g.NU(this.player,this);g.H(this,this.F);this.F.g(this.C.element);this.A=new g.AT(this.player,this);g.H(this,this.A);g.DK(this.player,this.A.element,4);this.o=new g.W({B:"div",G:"ytp-miniplayer-buttons"});g.H(this,this.o);g.DK(this.player,this.o.element,4);this.o.hide();a=new g.W({B:"button",W:["ytp-miniplayer-close-button","ytp-button"],L:{"aria-label":"Close"},
J:[g.KP()]});g.H(this,a);a.g(this.o.element);this.K(a.element,"click",this.qx);a=new g.W({B:"button",W:["ytp-miniplayer-replay-button","ytp-button"],L:{"aria-label":"Close"},J:[g.XP()]});g.H(this,a);a.g(this.o.element);this.K(a.element,"click",this.vK);this.K(this.player,"presentingplayerstatechange",this.JF);this.K(this.player,"appresize",this.ib);this.K(this.player,"fullscreentoggled",this.ib);this.ib();this.H=!0}0!=this.player.getPlayerState()&&g.hD.prototype.show.call(this);this.A.show();this.player.unloadModule("annotations_module")};
g.h.hide=function(){this.l&&(this.l.dispose(),this.l=void 0);g.hD.prototype.hide.call(this);this.player.app.F.g||(this.H&&this.A.hide(),this.player.loadModule("annotations_module"))};
g.h.T=function(){this.l&&(this.l.dispose(),this.l=void 0);g.hD.prototype.T.call(this)};
g.h.qx=function(){this.player.stopVideo();this.player.la("onCloseMiniplayer")};
g.h.vK=function(){this.player.playVideo()};
g.h.Sy=function(a){if(a.target==this.C.element||a.target==this.u.element)g.Q(g.X(this.player).experiments,"kevlar_miniplayer_scrim_pause")?2==this.player.getPlayerState()?this.player.playVideo():this.player.pauseVideo():this.player.la("onExpandMiniplayer")};
g.h.wJ=function(){g.K(this.player.getRootNode(),"ytp-player-minimized",this.player.app.F.g);this.player.app.F.g&&0==this.player.getPlayerState()?this.o.show():this.o.hide()};
g.h.IF=function(){this.A.td();this.F.td();this.l&&this.l.start()};
g.h.JF=function(a){g.U(a.state,32)&&this.D.hide()};
g.h.ib=function(){var a=this.A,b=g.pK(this.player).getPlayerSize().width;a.Pa=0;a.A=b;a.D=!1;g.CT(a)};
g.h.yM=function(a){this.player.app.F.g&&(0==a?(this.hide(),this.o.show()):(this.show(),this.o.hide()))};
g.h.bb=function(){return this.D};
g.h.Ac=function(){return!1};
g.h.tg=function(){return!1};
g.h.ii=function(){return!1};
g.h.qs=function(){};
g.h.Qh=function(){};
g.h.qj=function(){};
g.h.jk=function(){return null};
g.h.Tq=function(){return new g.qh(0,0,0,0)};
g.h.handleGlobalKeyDown=function(){return!1};
g.h.handleGlobalKeyUp=function(){return!1};
g.h.vn=function(a,b,c,d,e){var f=0,k=d=0,l=g.Vh(a);if(b){c=g.go(b,"ytp-prev-button")||g.go(b,"ytp-next-button");var m=g.go(b,"ytp-play-button");c?f=k=12:m&&(b=g.Sh(b,this.element),k=b.x,f=b.y-12)}else k=c-l.width/2,d=25+(e||0);b=g.pK(this.player).getPlayerSize().width;e=f+(e||0);k=g.rd(k,0,b-l.width);e?(a.style.top=e+"px",a.style.bottom=""):(a.style.top="",a.style.bottom=d+"px");a.style.left=k+"px"};
g.h.showControls=function(){};
g.h.Uq=function(){};
g.h.Rh=function(){};g.t(z5,g.RK);z5.prototype.init=function(){};
z5.prototype.load=function(){this.player.hideControls();this.g.show()};
z5.prototype.unload=function(){this.player.showControls();this.g.hide()};g.oV.miniplayer=z5;})(_yt_player);
