(function(g){var window=this;var Upa=function(a,b){return g.Vb(a,b)},C5=function(){},Vpa=function(a){if(a.zc&&"function"==typeof a.zc)return a.zc();
if(g.v(a))return a.split("");if(g.Ma(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}return g.Rb(a)},Wpa=function(a,b){if(a.forEach&&"function"==typeof a.forEach)a.forEach(b,void 0);
else if(g.Ma(a)||g.v(a))(0,g.A)(a,b,void 0);else{if(a.Id&&"function"==typeof a.Id)var c=a.Id();else if(a.zc&&"function"==typeof a.zc)c=void 0;else if(g.Ma(a)||g.v(a)){c=[];for(var d=a.length,e=0;e<d;e++)c.push(e)}else c=g.Sb(a);d=Vpa(a);e=d.length;for(var f=0;f<e;f++)b.call(void 0,d[f],c&&c[f],a)}},D5=function(a){g.ln(a,"zx",g.cd());
return a},E5=function(a,b,c){g.La(c)||(c=[String(c)]);
g.qn(a.l,b,c)},F5=function(a){return(a=g.Io(a))?new ActiveXObject(a):new XMLHttpRequest},G5=function(a,b){return b+" ["+a.ba+" "+a.F+" "+a.getStatus()+"]"},Xpa=function(a){return"content-type"==a.toLowerCase()},H5=function(a){a.g&&a.I&&(a.g.ontimeout=null);
a.C&&(g.w.clearTimeout(a.C),a.C=null)},Ypa=function(a){return g.Nd&&g.pd(9)&&g.Ga(a.timeout)&&g.Ea(a.ontimeout)},I5=function(a){a.O||(a.O=!0,a.dispatchEvent("complete"),a.dispatchEvent("error"))},J5=function(a,b){if(a.g){H5(a);
var c=a.g,d=a.P[0]?g.Ia:null;a.g=null;a.P=null;b||a.dispatchEvent("ready");try{c.onreadystatechange=d}catch(e){}}},K5=function(a,b){a.i=!1;
a.g&&(a.o=!0,a.g.abort(),a.o=!1);a.l=b;a.u=5;I5(a);J5(a)},L5=function(a){return a.g?a.g.readyState:0},M5=function(a){if(a.i&&"undefined"!=typeof g.CY)if(a.P[1]&&4==L5(a)&&2==a.getStatus())G5(a,"Local request error detected and ignored");
else if(a.D&&4==L5(a))g.Jg(a.Vv,0,a);else if(a.dispatchEvent("readystatechange"),4==L5(a)){G5(a,"Request complete");a.i=!1;try{var b=a.getStatus();a:switch(b){case 200:case 201:case 202:case 204:case 206:case 304:case 1223:var c=!0;break a;default:c=!1}var d;if(!(d=c)){var e;if(e=0===b){var f=g.Tg(String(a.F))[1]||null;if(!f&&g.w.self&&g.w.self.location){var k=g.w.self.location.protocol;f=k.substr(0,k.length-1)}e=!Zpa.test(f?f.toLowerCase():"")}d=e}if(d)a.dispatchEvent("complete"),a.dispatchEvent("success");
else{a.u=6;try{var l=2<L5(a)?a.g.statusText:""}catch(m){l=""}a.l=l+" ["+a.getStatus()+"]";I5(a)}}finally{J5(a)}}},N5=function(a){g.Uf.call(this);
this.headers=new g.$m;this.M=a||null;this.i=!1;this.P=this.g=null;this.ba=this.F="";this.u=0;this.l="";this.o=this.V=this.D=this.O=!1;this.A=0;this.C=null;this.Z="";this.I=this.R=!1},O5=function(a){try{return a.g?a.g.responseText:""}catch(b){return""}},$pa=function(a,b){var c=[];
g.Xk(b,function(d){try{var e=g.Xo.prototype.i.call(this,d,!0)}catch(f){if("Storage: Invalid value was encountered"==f)return;throw f;}g.Ea(e)?g.Wo(e)&&c.push(d):c.push(d)},a);
return c},aqa=function(a,b){var c=$pa(a,b);
(0,g.A)(c,function(d){g.Xo.prototype.remove.call(this,d)},a)},P5=function(a){if(a.bd){if(a.bd.locationOverrideToken)return{locationOverrideToken:a.bd.locationOverrideToken};
if(null!=a.bd.latitudeE7&&null!=a.bd.longitudeE7)return{latitudeE7:a.bd.latitudeE7,longitudeE7:a.bd.longitudeE7}}return null},bqa=function(a,b){g.ab(a,b)||a.push(b)},Q5=function(a){var b=0,c;
for(c in a)b++;return b},R5=function(a,b){var c=b instanceof g.yc?b:g.Ec(b,/^data:image\//i.test(b));
a.src=g.zc(c)},cqa=function(a){try{return g.w.JSON.parse(a)}catch(b){}a=String(a);
if(/^\s*$/.test(a)?0:/^[\],:{}\s\u2028\u2029]*$/.test(a.replace(/\\["\\\/bfnrtu]/g,"@").replace(/(?:"[^"\\\n\r\u2028\u2029\x00-\x08\x0a-\x1f]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?)[\s\u2028\u2029]*(?=:|,|]|}|$)/g,"]").replace(/(?:^|:|,)(?:[\s\u2028\u2029]*\[)+/g,"")))try{return eval("("+a+")")}catch(b){}throw Error("Invalid JSON string: "+a);},dqa=function(a,b,c,d){var e=new g.cn(null,void 0);
a&&g.dn(e,a);b&&g.en(e,b);c&&g.fn(e,c);d&&(e.i=d);return e},S5=function(a){if(g.w.JSON)try{return g.w.JSON.parse(a)}catch(b){}return cqa(a)},T5=function(){this.g=[];
this.i=[]},U5=function(a,b){g.bq[a]=!0;
var c=g.$p();c&&c.publish.apply(c,arguments);g.bq[a]=!1},V5=function(a){this.app=this.name=this.id="";
this.type="REMOTE_CONTROL";this.obfuscatedGaiaId=this.avatar=this.username="";this.l=!1;this.capabilities=new Set;this.experiments=new Set;this.theme="u";new g.$m;this.g=this.i="";a&&(this.id=a.id||a.name,this.name=a.name,this.app=a.app,this.type=a.type||"REMOTE_CONTROL",this.username=a.user||"",this.avatar=a.userAvatarUri||"",this.obfuscatedGaiaId=a.obfuscatedGaiaId||"",this.theme=a.theme||"u",eqa(this,a.capabilities||""),fqa(this,a.experiments||""),this.i=a.remoteControllerUrl||"",this.g=a.localChannelEncryptionKey||
"")},eqa=function(a,b){a.capabilities.clear();
(0,g.Zd)(b.split(","),g.Ra(Upa,gqa)).forEach(function(c){a.capabilities.add(c)})},fqa=function(a,b){a.experiments.clear();
b.split(",").forEach(function(c){a.experiments.add(c)})},W5=function(a){a=a||{};
this.name=a.name||"";this.id=a.id||a.screenId||"";this.token=a.token||a.loungeToken||"";this.uuid=a.uuid||a.dialId||""},X5=function(a,b){return!!b&&(a.id==b||a.uuid==b)},Y5=function(a){return{name:a.name,
screenId:a.id,loungeToken:a.token,dialId:a.uuid}},hqa=function(a){return new W5(a)},Z5=function(a){return g.La(a)?(0,g.C)(a,hqa):[]},$5=function(a){return a?'{name:"'+a.name+'",id:'+a.id.substr(0,6)+"..,token:"+(a.token?".."+a.token.slice(-6):"-")+",uuid:"+(a.uuid?".."+a.uuid.slice(-6):"-")+"}":"null"},a6=function(a){return g.La(a)?"["+(0,g.C)(a,$5).join(",")+"]":"null"},b6=function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(a){var b=16*Math.random()|0;
return("x"==a?b:b&3|8).toString(16)})},iqa=function(a){return(0,g.C)(a,function(b){return{key:b.id,
name:b.name}})},c6=function(a,b){return g.Ya(a,function(c){return c||b?!c!=!b?!1:c.id==b.id:!0})},d6=function(a,b){return g.Ya(a,function(c){return X5(c,b)})},jqa=function(){var a=(0,g.ut)();
a&&aqa(a,a.g.hf(!0))},e6=function(){var a=g.xt("yt-remote-connected-devices")||[];
g.rb(a);return a},kqa=function(a){if(0==a.length)return[];
var b=a[0].indexOf("#"),c=-1==b?a[0]:a[0].substring(0,b);return(0,g.C)(a,function(d,e){return 0==e?d:d.substring(c.length)})},f6=function(a){g.wt("yt-remote-connected-devices",a,86400)},h6=function(){if(g6)return g6;
var a=g.xt("yt-remote-device-id");a||(a=b6(),g.wt("yt-remote-device-id",a,31536E3));for(var b=e6(),c=1,d=a;g.ab(b,d);)c++,d=a+"#"+c;return g6=d},i6=function(){var a=e6(),b=h6();
g.ab(a,b);g.At()&&g.tb(a,b);a=kqa(a);if(0==a.length)try{g.ys("remote_sid")}catch(c){}else try{g.xs("remote_sid",a.join(","),-1)}catch(c){}},j6=function(){return g.xt("yt-remote-session-browser-channel")},k6=function(){return g.xt("yt-remote-local-screens")||[]},l6=function(){g.wt("yt-remote-lounge-token-expiration",!0,86400)},lqa=function(a){5<a.length&&(a=a.slice(a.length-5));
var b=(0,g.C)(k6(),function(d){return d.loungeToken}),c=(0,g.C)(a,function(d){return d.loungeToken});
(0,g.mj)(c,function(d){return!g.ab(b,d)})&&l6();
g.wt("yt-remote-local-screens",a,31536E3)},mqa=function(a,b){g.wt("yt-remote-session-browser-channel",a);
g.wt("yt-remote-session-screen-id",b);var c=e6(),d=h6();g.ab(c,d)||c.push(d);f6(c);i6()},m6=function(a){a||(g.zt("yt-remote-session-screen-id"),g.zt("yt-remote-session-video-id"));
i6();a=e6();g.db(a,h6());f6(a)},o6=function(){if(!n6){var a=g.gp();
a&&(n6=new g.Ro(a))}return n6?!!n6.get("yt-remote-use-staging-server"):!1},p6=function(a){return!!document.currentScript&&(-1!=document.currentScript.src.indexOf("?"+a)||-1!=document.currentScript.src.indexOf("&"+a))},q6=function(){return"function"==typeof window.__onGCastApiAvailable?window.__onGCastApiAvailable:null},s6=function(a){a.length?r6(a.shift(),function(){s6(a)}):t6()},nqa=function(a){return"chrome-extension://"+a+u6},r6=function(a,b,c){var d=document.createElement("script");
d.onerror=b;c&&(d.onload=c);d.src=a;(document.head||document.documentElement).appendChild(d)},t6=function(){var a=q6();
a&&a(!1,"No cast extension found")},v6=function(){if(oqa){var a=2,b=q6(),c=function(){a--;
0==a&&b&&b(!0)};
window.__onGCastApiAvailable=c;r6("//www.gstatic.com/cast/sdk/libs/sender/1.0/cast_framework.js",t6,c)}},pqa=function(){v6();
var a=window.navigator.userAgent.match(/Chrome\/([0-9]+)/);s6(["//www.gstatic.com/eureka/clank/"+(a?parseInt(a[1],10):0)+u6,"//www.gstatic.com/eureka/clank"+u6])},w6=function(a,b,c){g.G.call(this);
this.A=null!=c?(0,g.y)(a,c):a;this.Vc=b;this.u=(0,g.y)(this.hD,this);this.g=!1;this.i=0;this.l=this.za=null;this.o=[]},x6=function(){},y6=function(a,b,c,d){this.g=a;
this.l=b;this.C=c;this.A=d||1;this.o=45E3;this.aa=new g.rn(this);this.i=new g.Ig;this.i.setInterval(250)},A6=function(a,b,c){a.Yh=1;
a.lg=D5(b.clone());a.rh=c;a.u=!0;z6(a,null)},B6=function(a,b,c,d,e){a.Yh=1;
a.lg=D5(b.clone());a.rh=null;a.u=c;e&&(a.Sz=!1);z6(a,d)},z6=function(a,b){a.Fi=(0,g.B)();
C6(a);a.Cg=a.lg.clone();E5(a.Cg,"t",a.A);a.Xk=0;a.tc=a.g.jp(a.g.Ok()?b:null);0<a.Pp&&(a.An=new g.Ll((0,g.y)(a.YA,a,a.tc),a.Pp));a.aa.ca(a.tc,"readystatechange",a.XL);var c=a.Xg?g.cc(a.Xg):{};a.rh?(a.jo="POST",c["Content-Type"]="application/x-www-form-urlencoded",a.tc.send(a.Cg,a.jo,a.rh,c)):(a.jo="GET",a.Sz&&!g.Pd&&(c.Connection="close"),a.tc.send(a.Cg,a.jo,null,c));a.g.te(1)},J6=function(a,b,c){for(var d=!0;!a.Ng&&a.Xk<c.length;){var e=qqa(a,c);
if(e==D6){4==b&&(a.mg=4,E6(15),d=!1);break}else if(e==F6){a.mg=4;E6(16);d=!1;break}else G6(a,e)}4==b&&0==c.length&&(a.mg=1,E6(17),d=!1);a.ye=a.ye&&d;d||(H6(a),I6(a))},qqa=function(a,b){var c=a.Xk,d=b.indexOf("\n",c);
if(-1==d)return D6;c=Number(b.substring(c,d));if(isNaN(c))return F6;d+=1;if(d+c>b.length)return D6;var e=b.substr(d,c);a.Xk=d+c;return e},M6=function(a,b){a.Fi=(0,g.B)();
C6(a);var c=b?window.location.hostname:"";a.Cg=a.lg.clone();g.ln(a.Cg,"DOMAIN",c);g.ln(a.Cg,"t",a.A);try{a.Ce=new ActiveXObject("htmlfile")}catch(n){H6(a);a.mg=7;E6(22);I6(a);return}var d="<html><body>";if(b){for(var e="",f=0;f<c.length;f++){var k=c.charAt(f);if("<"==k)e+="\\x3c";else if(">"==k)e+="\\x3e";else{var l=k;if(l in K6)k=K6[l];else if(l in L6)k=K6[l]=L6[l];else{var m=l.charCodeAt(0);if(31<m&&127>m)k=l;else{if(256>m){if(k="\\x",16>m||256<m)k+="0"}else k="\\u",4096>m&&(k+="0");k+=m.toString(16).toUpperCase()}k=
K6[l]=k}e+=k}}d+='<script>document.domain="'+e+'"\x3c/script>'}c=g.Sc(g.rc("b/12014412"),d+"</body></html>");a.Ce.open();a.Ce.write(g.Nc(c));a.Ce.close();a.Ce.parentWindow.m=(0,g.y)(a.oL,a);a.Ce.parentWindow.d=(0,g.y)(a.Xy,a,!0);a.Ce.parentWindow.rpcClose=(0,g.y)(a.Xy,a,!1);c=a.Ce.createElement("DIV");a.Ce.parentWindow.document.body.appendChild(c);d=g.Dc(a.Cg.toString());d=g.Zc(g.Ac(d));d=g.Sc(g.rc("b/12014412"),'<iframe src="'+d+'"></iframe>');g.Tc(c,d);a.g.te(1)},C6=function(a){a.Vs=(0,g.B)()+a.o;
N6(a,a.o)},N6=function(a,b){if(null!=a.Wi)throw Error("WatchDog timer not null");
a.Wi=O6((0,g.y)(a.yL,a),b)},P6=function(a){a.Wi&&(g.w.clearTimeout(a.Wi),a.Wi=null)},I6=function(a){a.g.Tv()||a.Ng||a.g.kn(a)},H6=function(a){P6(a);
g.sf(a.An);a.An=null;a.i.stop();g.tn(a.aa);if(a.tc){var b=a.tc;a.tc=null;b.abort();b.dispose()}a.Ce&&(a.Ce=null)},G6=function(a,b){try{a.g.Ry(a,b),a.g.te(4)}catch(c){}},R6=function(a,b,c,d,e){if(0==d)c(!1);
else{var f=e||0;d--;Q6(a,b,function(k){k?c(!0):g.w.setTimeout(function(){R6(a,b,c,d,f)},f)})}},Q6=function(a,b,c){var d=new Image;
d.onload=function(){try{S6(d),c(!0)}catch(e){}};
d.onerror=function(){try{S6(d),c(!1)}catch(e){}};
d.onabort=function(){try{S6(d),c(!1)}catch(e){}};
d.ontimeout=function(){try{S6(d),c(!1)}catch(e){}};
g.w.setTimeout(function(){if(d.ontimeout)d.ontimeout()},b);
R5(d,a)},S6=function(a){a.onload=null;
a.onerror=null;a.onabort=null;a.ontimeout=null},T6=function(a){this.g=a;
this.i=new x6},V6=function(a){var b=U6(a.g,a.gj,"/mail/images/cleardot.gif");
D5(b);R6(b.toString(),5E3,(0,g.y)(a.oC,a),3,2E3);a.te(1)},X6=function(a){var b=a.g.F;
if(null!=b)E6(5),b?(E6(11),W6(a.g,a,!1)):(E6(12),W6(a.g,a,!0));else if(a.Ed=new y6(a,void 0,void 0,void 0),a.Ed.Xg=a.Np,b=a.g,b=U6(b,b.Ok()?a.Nj:null,a.Op),E6(5),!g.Nd||g.qd(10))E5(b,"TYPE","xmlhttp"),B6(a.Ed,b,!1,a.Nj,!1);else{E5(b,"TYPE","html");var c=a.Ed;a=!!a.Nj;c.Yh=3;c.lg=D5(b.clone());M6(c,a)}},Y6=function(a,b,c){this.g=1;
this.i=[];this.o=[];this.u=new x6;this.D=a||null;this.F=null!=b?b:null;this.A=c||!1},rqa=function(a,b){this.g=a;
this.map=b;this.context=null},Z6=function(a){g.uf.call(this,"statevent",a)},$6=function(a,b){g.uf.call(this,"timingevent",a);
this.size=b},a7=function(a){g.uf.call(this,"serverreachability",a)},e7=function(a){b7(a);
if(3==a.g){var b=a.wk++,c=a.Xl.clone();g.ln(c,"SID",a.l);g.ln(c,"RID",b);g.ln(c,"TYPE","terminate");c7(a,c);b=new y6(a,a.l,b,void 0);b.Yh=2;b.lg=D5(c.clone());R5(new Image,b.lg.toString());b.Fi=(0,g.B)();C6(b)}d7(a)},g7=function(a){a.FC(1,0);
a.Xl=U6(a,null,a.Mp);f7(a)},b7=function(a){a.cg&&(a.cg.abort(),a.cg=null);
a.Sb&&(a.Sb.cancel(),a.Sb=null);a.kf&&(g.w.clearTimeout(a.kf),a.kf=null);h7(a);a.Bd&&(a.Bd.cancel(),a.Bd=null);a.hg&&(g.w.clearTimeout(a.hg),a.hg=null)},i7=function(a,b){if(0==a.g)throw Error("Invalid operation: sending map when state is closed");
a.i.push(new rqa(a.CH++,b));2!=a.g&&3!=a.g||f7(a)},f7=function(a){a.Bd||a.hg||(a.hg=O6((0,g.y)(a.Wy,a),0),a.Sh=0)},l7=function(a,b){if(1==a.g){if(!b){a.wk=Math.floor(1E5*Math.random());
var c=a.wk++,d=new y6(a,"",c,void 0);d.Xg=null;var e=j7(a),f=a.Xl.clone();g.ln(f,"RID",c);g.ln(f,"CVER","1");c7(a,f);A6(d,f,e);a.Bd=d;a.g=2}}else 3==a.g&&(b?k7(a,b):0==a.i.length||a.Bd||k7(a))},k7=function(a,b){if(b)if(6<a.Og){a.i=a.o.concat(a.i);
a.o.length=0;var c=a.wk-1;var d=j7(a)}else c=b.C,d=b.rh;else c=a.wk++,d=j7(a);var e=a.Xl.clone();g.ln(e,"SID",a.l);g.ln(e,"RID",c);g.ln(e,"AID",a.ki);c7(a,e);c=new y6(a,a.l,c,a.Sh+1);c.Xg=null;c.setTimeout(1E4+Math.round(1E4*Math.random()));a.Bd=c;A6(c,e,d)},c7=function(a,b){if(a.Tc){var c=a.Tc.xv();
c&&g.Lb(c,function(d,e){g.ln(b,e,d)})}},j7=function(a){var b=Math.min(a.i.length,1E3),c=["count="+b];
if(6<a.Og&&0<b){var d=a.i[0].g;c.push("ofs="+d)}else d=0;for(var e=0;e<b;e++){var f=a.i[e].g,k=a.i[e].map;f=6>=a.Og?e:f-d;try{g.Lb(k,function(l,m){c.push("req"+f+"_"+m+"="+encodeURIComponent(l))})}catch(l){c.push("req"+f+"_type="+encodeURIComponent("_badmap"))}}a.o=a.o.concat(a.i.splice(0,b));
return c.join("&")},m7=function(a){a.Sb||a.kf||(a.C=1,a.kf=O6((0,g.y)(a.Vy,a),0),a.Kh=0)},o7=function(a){if(a.Sb||a.kf||3<=a.Kh)return!1;
a.C++;a.kf=O6((0,g.y)(a.Vy,a),n7(a,a.Kh));a.Kh++;return!0},W6=function(a,b,c){a.fo=c;
a.Je=b.xf;a.A||g7(a)},h7=function(a){null!=a.Sg&&(g.w.clearTimeout(a.Sg),a.Sg=null)},n7=function(a,b){var c=5E3+Math.floor(1E4*Math.random());
a.isActive()||(c*=2);return c*b},q7=function(a,b){if(2==b||9==b){var c=null;
a.Tc&&(c=null);var d=(0,g.y)(a.DM,a);c||(c=new g.cn("//www.google.com/images/cleardot.gif"),D5(c));Q6(c.toString(),1E4,d)}else E6(2);p7(a,b)},p7=function(a,b){a.g=0;
a.Tc&&a.Tc.wu(b);d7(a);b7(a)},d7=function(a){a.g=0;
a.Je=-1;if(a.Tc)if(0==a.o.length&&0==a.i.length)a.Tc.Wo();else{g.gb(a.o);var b=g.gb(a.i);a.o.length=0;a.i.length=0;a.Tc.Wo(b)}},U6=function(a,b,c){var d=g.mn(c);
if(""!=d.g)b&&g.en(d,b+"."+d.g),g.fn(d,d.u);else{var e=window.location;d=dqa(e.protocol,b?b+"."+e.hostname:e.hostname,+e.port,c)}a.tj&&g.Lb(a.tj,function(f,k){g.ln(d,k,f)});
g.ln(d,"VER",a.Og);c7(a,d);return d},O6=function(a,b){if(!g.Na(a))throw Error("Fn must not be null and must be a function");
return g.w.setTimeout(function(){a()},b)},E6=function(a){r7.dispatchEvent(new Z6(r7,a))},s7=function(){},sqa=function(a,b){this.action=a;
this.params=b||{}},t7=function(a,b){g.G.call(this);
this.g=new g.M(this.gL,0,this);g.H(this,this.g);this.Vc=5E3;this.i=0;if(g.Na(a))b&&(a=(0,g.y)(a,b));else if(a&&g.Na(a.handleEvent))a=(0,g.y)(a.handleEvent,a);else throw Error("Invalid listener argument");this.l=a},u7=function(a,b,c){this.H=a;
this.A=b;this.l=new g.Qo;this.i=new t7(this.gM,this);this.g=null;this.Za=!1;this.u=null;this.F="";this.D=this.o=0;this.C=[];this.I=c||!1},tqa=function(a){return{firstTestResults:[""],
secondTestResults:!a.g.fo,sessionId:a.g.l,arrayId:a.g.ki}},v7=function(a,b){a.D=b||0;
a.i.stop();a.g&&(3==a.g.g&&l7(a.g),e7(a.g));a.D=0},w7=function(a){return!!a.g&&3==a.g.g},uqa=function(a,b){(a.A.loungeIdToken=b)||a.i.stop()},x7=function(a){this.port=this.domain="";
this.g="/api/lounge";this.i=!0;a=a||document.location.href;var b=g.Wg(a)||"";b&&(this.port=":"+b);this.domain=g.Vg(a)||"";a=g.Jb;0<=a.search("MSIE")&&(a=a.match(/MSIE ([\d.]+)/)[1],0>g.Ib(a,"10.0")&&(this.i=!1))},y7=function(a,b){var c=a.g;
if(g.Ea(void 0)?0:a.i)c="https://"+a.domain+a.port+a.g;return g.fh(c+b,{})},z7=function(a,b,c,d,e){a={format:"JSON",
method:"POST",context:a,timeout:5E3,withCredentials:!1,onSuccess:g.Ra(a.o,d,!0),onError:g.Ra(a.l,e),rd:g.Ra(a.u,e)};c&&(a.qb=c,a.headers={"Content-Type":"application/x-www-form-urlencoded"});return g.Uq(b,a)},xqa=function(){var a=A7;
vqa();B7.push(a);wqa(B7)},C7=function(a,b){vqa();
var c=B7,d=yqa(a,String(b));0==c.length?zqa(d):(wqa(c),(0,g.A)(c,function(e){e(d)}))},vqa=function(){B7||(B7=g.x("yt.mdx.remote.debug.handlers_")||[],g.Ha("yt.mdx.remote.debug.handlers_",B7,void 0))},zqa=function(a){var b=(D7+1)%50;
D7=b;E7[b]=a;F7||(F7=49==b)},wqa=function(a){var b=E7;
if(b[0]){var c=D7,d=F7?c:-1;do{d=(d+1)%50;var e=b[d];(0,g.A)(a,function(f){f(e)})}while(d!=c);
E7=Array(50);D7=-1;F7=!1}},yqa=function(a,b){var c=((0,g.B)()-Aqa)/1E3;
c.toFixed&&(c=c.toFixed(3));var d=[];d.push("[",c+"s","] ");d.push("[","yt.mdx.remote","] ");d.push(a+": "+b,"\n");return d.join("")},G7=function(a){g.P.call(this);
this.C=a;this.g=[]},Bqa=function(a,b){var c=a.get(b.uuid)||a.get(b.id);
if(c){var d=c.name;c.id=b.id||c.id;c.name=b.name;c.token=b.token;c.uuid=b.uuid||c.uuid;return c.name!=d}a.g.push(b);return!0},Cqa=function(a,b){var c=a.g.length!=b.length;
a.g=(0,g.Zd)(a.g,function(f){return!!c6(b,f)});
for(var d=0,e=b.length;d<e;d++)c=Bqa(a,b[d])||c;return c},Dqa=function(a,b){var c=a.g.length;
a.g=(0,g.Zd)(a.g,function(d){return!(d||b?!d!=!b?0:d.id==b.id:1)});
return a.g.length<c},H7=function(a,b,c,d){g.P.call(this);
this.A=a;this.u=b;this.l=c;this.o=d;this.i=0;this.g=null;this.za=NaN},J7=function(a){G7.call(this,"LocalScreenService");
this.l=a;this.i=NaN;I7(this);this.info("Initializing with "+a6(this.g))},Eqa=function(a){if(a.g.length){var b=(0,g.C)(a.g,function(d){return d.id}),c=y7(a.l,"/pairing/get_lounge_token_batch");
z7(a.l,c,{screen_ids:b.join(",")},(0,g.y)(a.rD,a),(0,g.y)(a.qD,a))}},I7=function(a){var b=Z5(k6());
b=(0,g.Zd)(b,function(c){return!c.uuid});
return Cqa(a,b)},K7=function(a,b){lqa((0,g.C)(a.g,Y5));
b&&l6()},M7=function(a,b){g.P.call(this);
this.A=b;var c=g.xt("yt-remote-online-screen-ids")||"";c=c?c.split(","):[];for(var d={},e=this.A(),f=0,k=e.length;f<k;++f){var l=e[f].id;d[l]=g.ab(c,l)}this.g=d;this.u=a;this.l=this.o=NaN;this.i=null;L7("Initialized with "+g.Ng(this.g))},Fqa=function(a,b,c){var d=y7(a.u,"/pairing/get_screen_availability");
z7(a.u,d,{lounge_token:b.token},(0,g.y)(function(e){e=e.screens||[];for(var f=0,k=e.length;f<k;++f)if(e[f].loungeToken==b.token){c("online"==e[f].status);return}c(!1)},a),(0,g.y)(function(){c(!1)},a))},N7=function(a,b){a:if(Q5(b)!=Q5(a.g))var c=!1;
else{c=g.Sb(b);for(var d=0,e=c.length;d<e;++d)if(!a.g[c[d]]){c=!1;break a}c=!0}c||(L7("Updated online screens: "+g.Ng(a.g)),a.g=b,a.N("screenChange"));Gqa(a)},O7=function(a){isNaN(a.l)||g.Zp(a.l);
a.l=g.Xp((0,g.y)(a.Ur,a),0<a.o&&a.o<(0,g.B)()?2E4:1E4)},L7=function(a){C7("OnlineScreenService",a)},Hqa=function(a){var b={};
(0,g.A)(a.A(),function(c){c.token?b[c.token]=c.id:this.Jb("Requesting availability of screen w/o lounge token.")});
return b},Gqa=function(a){a=g.Sb(g.Mb(a.g,function(b){return b}));
g.rb(a);a.length?g.wt("yt-remote-online-screen-ids",a.join(","),60):g.zt("yt-remote-online-screen-ids")},P7=function(a){G7.call(this,"ScreenService");
this.A=a;this.i=this.l=null;this.o=[];this.u={};Iqa(this)},Kqa=function(a,b,c,d,e,f){a.info("getAutomaticScreenByIds "+c+" / "+b);
c||(c=a.u[b]);var k=a.Kd();if(k=(c?d6(k,c):null)||d6(k,b)){k.uuid=b;var l=Q7(a,k);Fqa(a.i,l,function(m){e(m?l:null)})}else c?Jqa(a,c,(0,g.y)(function(m){var n=Q7(this,new W5({name:d,
screenId:c,loungeToken:m,dialId:b||""}));Fqa(this.i,n,function(p){e(p?n:null)})},a),f):e(null)},Lqa=function(a,b){for(var c=0,d=a.g.length;c<d;++c)if(a.g[c].name==b)return a.g[c];
return null},Jqa=function(a,b,c,d){a.info("requestLoungeToken_ for "+b);
var e={qb:{screen_ids:b},method:"POST",context:a,onSuccess:function(f,k){var l=k&&k.screens||[];l[0]&&l[0].screenId==b?c(l[0].loungeToken):d(Error("Missing lounge token in token response"))},
onError:function(){d(Error("Request screen lounge token failed"))}};
g.Uq(y7(a.A,"/pairing/get_lounge_token_batch"),e)},Mqa=function(a){a.g=a.l.Kd();
var b=a.u,c={},d;for(d in b)c[b[d]]=d;b=0;for(d=a.g.length;b<d;++b){var e=a.g[b];e.uuid=c[e.id]||""}a.info("Updated manual screens: "+a6(a.g))},Iqa=function(a){R7(a);
a.l=new J7(a.A);a.l.subscribe("screenChange",(0,g.y)(a.AD,a));Mqa(a);a.o=Z5(g.xt("yt-remote-automatic-screen-cache")||[]);R7(a);a.info("Initializing automatic screens: "+a6(a.o));a.i=new M7(a.A,(0,g.y)(a.Kd,a,!0));a.i.subscribe("screenChange",(0,g.y)(function(){this.N("onlineScreenChange")},a))},Q7=function(a,b){var c=a.get(b.id);
c?(c.uuid=b.uuid,b=c):((c=d6(a.o,b.uuid))?(c.id=b.id,c.token=b.token,b=c):a.o.push(b),g.wt("yt-remote-automatic-screen-cache",(0,g.C)(a.o,Y5)));R7(a);a.u[b.uuid]=b.id;g.wt("yt-remote-device-id-map",a.u,31536E3);return b},R7=function(a){a.u=g.xt("yt-remote-device-id-map")||{}},S7=function(a,b,c){g.P.call(this);
this.P=c;this.F=a;this.i=b;this.l=null},T7=function(a,b){C7(a.P,b)},U7=function(a,b){S7.call(this,a,b,"CastSession");
this.g=null;this.o=0;this.A=(0,g.y)(this.gN,this);this.u=(0,g.y)(this.JL,this);this.o=g.Xp((0,g.y)(function(){Nqa(this,null)},this),12E4)},Oqa=function(a){a.info("sendYoutubeMessage_: getMdxSessionStatus "+g.Ng(void 0));
var b={type:"getMdxSessionStatus"};a.g?a.g.sendMessage("urn:x-cast:com.google.youtube.mdx",b,g.Ia,(0,g.y)(function(){T7(this,"Failed to send message: getMdxSessionStatus.")},a)):T7(a,"Sending yt message without session: "+g.Ng(b))},Nqa=function(a,b){g.Zp(a.o);
if(b){if(a.info("onConnectedScreenId_: Received screenId: "+b),!a.l||a.l.id!=b){var c=(0,g.y)(a.ln,a),d=(0,g.y)(a.Nd,a);a.Nv(b,c,d,5)}}else a.Nd(Error("Waiting for session status timed out."))},V7=function(a,b,c){S7.call(this,a,b,"DialSession");
this.o=this.D=null;this.H="";this.M=c;this.u=null;this.C=g.Ia;this.A=NaN;this.I=(0,g.y)(this.jN,this);this.g=g.Ia},Pqa=function(a){a.g=a.F.dB(a.H,a.i.label,a.i.friendlyName,(0,g.y)(function(b){this.g=g.Ia;
this.ln(b)},a),(0,g.y)(function(b){this.g=g.Ia;
this.Nd(b)},a))},Qqa=function(a){var b={};
b.pairingCode=a.H;b.theme=a.M;if(a.u){var c=a.u.currentTime||0;b.v=a.u.videoId;b.t=c}o6()&&(b.env_useStageMdx=1);return g.dh(b)},W7=function(a,b){S7.call(this,a,b,"ManualSession");
this.g=g.Xp((0,g.y)(this.mi,this,null),150)},X7=function(a,b,c,d){g.P.call(this);
this.i=a;this.C=b||"233637DE";this.A=c||"cl";this.D=d||!1;this.g=null;this.u=!1;this.l=[];this.o=(0,g.y)(this.pK,this)},Rqa=function(a,b){return b?g.Ya(a.l,function(c){return X5(b,c.label)},a):null},Y7=function(a){C7("Controller",a)},A7=function(a){window.chrome&&chrome.cast&&chrome.cast.logMessage&&chrome.cast.logMessage(a)},Z7=function(a){return a.u||!!a.l.length||!!a.g},$7=function(a,b,c){b!=a.g&&(g.sf(a.g),(a.g=b)?(c?a.N("yt-remote-cast2-receiver-resumed",b.i):a.N("yt-remote-cast2-receiver-selected",
b.i),b.subscribe("sessionScreen",(0,g.y)(a.Uy,a,b)),b.l?a.N("yt-remote-cast2-session-change",b.l):c&&a.g.mi(null)):a.N("yt-remote-cast2-session-change",null))},Sqa=function(a){var b=a.i.cB(),c=a.g&&a.g.i;
a=(0,g.C)(b,function(d){c&&X5(d,c.label)&&(c=null);var e=d.uuid?d.uuid:d.id,f=Rqa(this,d);f?(f.label=e,f.friendlyName=d.name):(f=new chrome.cast.Receiver(e,d.name),f.receiverType=chrome.cast.ReceiverType.CUSTOM);return f},a);
c&&(c.receiverType!=chrome.cast.ReceiverType.CUSTOM&&(c=new chrome.cast.Receiver(c.label,c.friendlyName),c.receiverType=chrome.cast.ReceiverType.CUSTOM),a.push(c));return a},Yqa=function(a,b,c,d,e,f,k){Tqa()?Uqa(b,e,f,k)&&(b8(!0),window.chrome&&chrome.cast&&chrome.cast.isAvailable?Vqa(a,c):(window.__onGCastApiAvailable=function(l,m){l?Vqa(a,c):(c8("Failed to load cast API: "+m),d8(!1),b8(!1),g.zt("yt-remote-cast-available"),g.zt("yt-remote-cast-receiver"),Wqa(),c(!1))},d?g.jq("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js"):
0<=window.navigator.userAgent.indexOf("Android")&&0<=window.navigator.userAgent.indexOf("Chrome/")&&window.navigator.presentation?pqa():!window.chrome||!window.navigator.presentation||0<=window.navigator.userAgent.indexOf("Edge")?t6():(v6(),s6(Xqa.map(nqa))))):a8("Cannot initialize because not running Chrome")},Wqa=function(){a8("dispose");
var a=e8();a&&a.dispose();g.Ha("yt.mdx.remote.cloudview.instance_",null,void 0);Zqa(!1);g.eq(f8);f8.length=0},g8=function(){return!!g.xt("yt-remote-cast-installed")},$qa=function(){var a=g.xt("yt-remote-cast-receiver");
return a?a.friendlyName:null},ara=function(){a8("clearCurrentReceiver");
g.zt("yt-remote-cast-receiver")},bra=function(){return g8()?e8()?e8().getCastSession():(c8("getCastSelector: Cast is not initialized."),null):(c8("getCastSelector: Cast API is not installed!"),null)},i8=function(){g8()?e8()?h8()?(a8("Requesting cast selector."),e8().requestSession()):(a8("Wait for cast API to be ready to request the session."),f8.push(g.dq("yt-remote-cast2-api-ready",i8))):c8("requestCastSelector: Cast is not initialized."):c8("requestCastSelector: Cast API is not installed!")},j8=
function(a,b){h8()?e8().setConnectedScreenStatus(a,b):c8("setConnectedScreenStatus called before ready.")},Tqa=function(){var a=0<=g.Jb.search(/ (CrMo|Chrome|CriOS)\//);
return g.fx||a},cra=function(a,b){e8().init(a,b)},Uqa=function(a,b,c,d){var e=!1;
e8()||(a=new X7(a,b,c,d),a.subscribe("yt-remote-cast2-availability-change",function(f){g.wt("yt-remote-cast-available",f);U5("yt-remote-cast2-availability-change",f)}),a.subscribe("yt-remote-cast2-receiver-selected",function(f){a8("onReceiverSelected: "+f.friendlyName);
g.wt("yt-remote-cast-receiver",f);U5("yt-remote-cast2-receiver-selected",f)}),a.subscribe("yt-remote-cast2-receiver-resumed",function(f){a8("onReceiverResumed: "+f.friendlyName);
g.wt("yt-remote-cast-receiver",f)}),a.subscribe("yt-remote-cast2-session-change",function(f){a8("onSessionChange: "+$5(f));
f||g.zt("yt-remote-cast-receiver");U5("yt-remote-cast2-session-change",f)}),g.Ha("yt.mdx.remote.cloudview.instance_",a,void 0),e=!0);
a8("cloudview.createSingleton_: "+e);return e},e8=function(){return g.x("yt.mdx.remote.cloudview.instance_")},Vqa=function(a,b){d8(!0);
b8(!1);cra(a,function(c){c?(Zqa(!0),g.gq("yt-remote-cast2-api-ready")):(c8("Failed to initialize cast API."),d8(!1),g.zt("yt-remote-cast-available"),g.zt("yt-remote-cast-receiver"),Wqa());b(c)})},a8=function(a){C7("cloudview",a)},c8=function(a){C7("cloudview",a)},d8=function(a){a8("setCastInstalled_ "+a);
g.wt("yt-remote-cast-installed",a)},h8=function(){return!!g.x("yt.mdx.remote.cloudview.apiReady_")},Zqa=function(a){a8("setApiReady_ "+a);
g.Ha("yt.mdx.remote.cloudview.apiReady_",a,void 0)},b8=function(a){g.Ha("yt.mdx.remote.cloudview.initializing_",a,void 0)},k8=function(a){this.index=-1;
this.videoId=this.listId="";this.volume=this.playerState=-1;this.muted=!1;this.audioTrackId=null;this.A=this.C=0;this.g=null;this.hasNext=this.Ke=!1;this.F=this.D=this.i=this.o=0;this.l=NaN;this.u=!1;this.reset(a)},l8=function(a){a.audioTrackId=null;
a.g=null;a.playerState=-1;a.Ke=!1;a.hasNext=!1;a.C=0;a.A=(0,g.B)();a.o=0;a.i=0;a.D=0;a.F=0;a.l=NaN;a.u=!1},m8=function(a){return 1==a.playerState?((0,g.B)()-a.A)/1E3:0},n8=function(a,b){a.C=b;
a.A=(0,g.B)()},o8=function(a){switch(a.playerState){case 1:case 1081:return((0,g.B)()-a.A)/1E3+a.C;
case -1E3:return 0}return a.C},p8=function(a,b,c){var d=a.videoId;
a.videoId=b;a.index=c;b!=d&&l8(a)},q8=function(a){var b={};
b.index=a.index;b.listId=a.listId;b.videoId=a.videoId;b.playerState=a.playerState;b.volume=a.volume;b.muted=a.muted;b.audioTrackId=a.audioTrackId;b.trackData=g.dc(a.g);b.hasPrevious=a.Ke;b.hasNext=a.hasNext;b.playerTime=a.C;b.playerTimeAt=a.A;b.seekableStart=a.o;b.seekableEnd=a.i;b.duration=a.D;b.loadedTime=a.F;b.liveIngestionTime=a.l;return b},s8=function(a,b){g.P.call(this);
this.g=0;this.o=a;this.A=[];this.u=new T5;this.l=this.i=null;this.F=(0,g.y)(this.jI,this);this.C=(0,g.y)(this.zk,this);this.D=(0,g.y)(this.iI,this);this.H=(0,g.y)(this.vI,this);var c=0;a?(c=a.getProxyState(),3!=c&&(a.subscribe("proxyStateChange",this.Ys,this),dra(this))):c=3;0!=c&&(b?this.Ys(c):g.Xp((0,g.y)(function(){this.Ys(c)},this),0));
var d=bra();d&&r8(this,d);this.subscribe("yt-remote-cast2-session-change",this.H)},t8=function(a){return new k8(a.o.getPlayerContextData())},dra=function(a){(0,g.A)("nowAutoplaying autoplayDismissed remotePlayerChange remoteQueueChange autoplayModeChange autoplayUpNext previousNextChange".split(" "),function(b){this.A.push(this.o.subscribe(b,g.Ra(this.mK,b),this))},a)},era=function(a){(0,g.A)(a.A,function(b){this.o.unsubscribeByKey(b)},a);
a.A.length=0},u8=function(a,b){var c=a.u;
50>c.g.length+c.i.length&&a.u.i.push(b)},w8=function(a,b,c){var d=t8(a);
n8(d,c);-1E3!=d.playerState&&(d.playerState=b);v8(a,d)},x8=function(a,b,c){a.o.sendMessage(b,c)},v8=function(a,b){era(a);
a.o.setPlayerContextData(q8(b));dra(a)},r8=function(a,b){a.l&&(a.l.removeUpdateListener(a.F),a.l.removeMediaListener(a.C),a.zk(null));
a.l=b;a.l&&(C7("CP","Setting cast session: "+a.l.sessionId),a.l.addUpdateListener(a.F),a.l.addMediaListener(a.C),a.l.media.length&&a.zk(a.l.media[0]))},fra=function(a){var b=a.i.media,c=a.i.customData;
if(b&&c){var d=t8(a);b.contentId!=d.videoId&&C7("CP","Cast changing video to: "+b.contentId);d.videoId=b.contentId;d.playerState=c.playerState;n8(d,a.i.getEstimatedTime());v8(a,d)}else C7("CP","No cast media video. Ignoring state update.")},y8=function(a,b,c){return(0,g.y)(function(d){this.Jb("Failed to "+b+" with cast v2 channel. Error code: "+d.code);
d.code!=chrome.cast.ErrorCode.TIMEOUT&&(this.Jb("Retrying "+b+" using MDx browser channel."),x8(this,b,c))},a)},z8=function(a,b,c){g.P.call(this);
this.u=NaN;this.I=!1;this.D=this.C=this.F=this.H=NaN;this.P=[];this.o=this.A=this.l=this.Oa=this.g=null;this.O=a;this.P.push(g.cs(window,"beforeunload",(0,g.y)(this.kD,this)));this.i=[];this.Oa=new k8;this.M=b.id;this.g=gra(this,c);this.g.subscribe("handlerOpened",this.nI,this);this.g.subscribe("handlerClosed",this.kI,this);this.g.subscribe("handlerError",this.lI,this);this.g.subscribe("handlerMessage",this.mI,this);uqa(this.g,b.token);this.subscribe("remoteQueueChange",function(){var d=this.Oa.videoId;
g.At()&&g.wt("yt-remote-session-video-id",d)},this)},A8=function(a){C7("conn",a)},gra=function(a,b){return new u7(y7(a.O,"/bc"),b)},B8=function(a,b){a.N("proxyStateChange",b)},hra=function(a){a.u=g.Xp((0,g.y)(function(){A8("Connecting timeout");
this.Oh(1)},a),2E4)},C8=function(a){g.Zp(a.u);
a.u=NaN},D8=function(a){g.Zp(a.H);
a.H=NaN},ira=function(a){E8(a);
a.F=g.Xp((0,g.y)(function(){F8(this,"getNowPlaying")},a),2E4)},E8=function(a){g.Zp(a.F);
a.F=NaN},kra=function(a,b){b&&(C8(a),D8(a));
b==(w7(a.g)&&isNaN(a.u))?b&&(B8(a,1),F8(a,"getSubtitlesTrack")):b?(a.Kv()&&a.Oa.reset(),B8(a,1),F8(a,"getNowPlaying"),jra(a)):a.Oh(1)},lra=function(a,b){var c=b.params.videoId;
delete b.params.videoId;c==a.Oa.videoId&&(g.Yb(b.params)?a.Oa.g=null:a.Oa.g=b.params,a.N("remotePlayerChange"))},mra=function(a,b){var c=b.params.videoId||b.params.video_id,d=parseInt(b.params.currentIndex,10);
a.Oa.listId=b.params.listId||a.Oa.listId;p8(a.Oa,c,d);a.N("remoteQueueChange")},ora=function(a,b){b.params=b.params||{};
mra(a,b);nra(a,b);a.N("autoplayDismissed")},nra=function(a,b){var c=parseInt(b.params.currentTime||b.params.current_time,10);
n8(a.Oa,isNaN(c)?0:c);c=parseInt(b.params.state,10);c=isNaN(c)?-1:c;-1==c&&-1E3==a.Oa.playerState&&(c=-1E3);a.Oa.playerState=c;c=Number(b.params.loadedTime);a.Oa.F=isNaN(c)?0:c;c=Number(b.params.duration);a.Oa.D=isNaN(c)?0:c;c=a.Oa;var d=Number(b.params.liveIngestionTime);c.l=d;c.u=isNaN(d)?!1:!0;c=a.Oa;d=Number(b.params.seekableStartTime);var e=Number(b.params.seekableEndTime);c.o=isNaN(d)?0:d;c.i=isNaN(e)?0:e;1==a.Oa.playerState?ira(a):E8(a);a.N("remotePlayerChange")},pra=function(a,b){if(-1E3!=
a.Oa.playerState){var c=1085;
switch(parseInt(b.params.adState,10)){case 1:c=1081;break;case 2:c=1084;break;case 0:c=1083}a.Oa.playerState=c;c=parseInt(b.params.currentTime,10);n8(a.Oa,isNaN(c)?0:c);a.N("remotePlayerChange")}},qra=function(a,b){var c="true"==b.params.muted;
a.Oa.volume=parseInt(b.params.volume,10);a.Oa.muted=c;a.N("remotePlayerChange")},rra=function(a,b){a.A=b.params.videoId;
a.N("nowAutoplaying",parseInt(b.params.timeout,10))},sra=function(a,b){var c="true"==b.params.hasNext;
a.Oa.Ke="true"==b.params.hasPrevious;a.Oa.hasNext=c;a.N("previousNextChange")},jra=function(a){g.Zp(a.D);
a.D=g.Xp((0,g.y)(a.Oh,a,1),864E5)},F8=function(a,b,c){c?A8("Sending: action="+b+", params="+g.Ng(c)):A8("Sending: action="+b);
a.g.sendMessage(b,c)},G8=function(a){G7.call(this,"ScreenServiceProxy");
this.Hc=a;this.i=[];this.i.push(this.Hc.$_s("screenChange",(0,g.y)(this.eN,this)));this.i.push(this.Hc.$_s("onlineScreenChange",(0,g.y)(this.QJ,this)))},xra=function(a){var b={device:"Desktop",
app:"youtube-desktop"};b=g.Pp("MDX_CONFIG")||b;jqa();i6();H8||(H8=new x7(b?b.loungeApiHost:void 0),o6()&&(H8.g="/api/loungedev"));I8||(I8=g.x("yt.mdx.remote.deferredProxies_")||[],g.Ha("yt.mdx.remote.deferredProxies_",I8,void 0));tra();var c=J8();if(!c){var d=new P7(H8);g.Ha("yt.mdx.remote.screenService_",d,void 0);c=J8();var e=!1,f=void 0,k=void 0,l=!1;b&&(e=!!b.loadCastApiSetupScript,f=b.appId,k=b.theme,l=!!b.disableDial);Yqa(a,d,function(m){m?K8()&&j8(K8(),"YouTube TV"):d.subscribe("onlineScreenChange",
function(){U5("yt-remote-receiver-availability-change")})},e,f,k,l)}b&&!g.x("yt.mdx.remote.initialized_")&&(g.Ha("yt.mdx.remote.initialized_",!0,void 0),L8("Initializing: "+g.Ng(b)),M8.push(g.dq("yt-remote-cast2-availability-change",function(){U5("yt-remote-receiver-availability-change")})),M8.push(g.dq("yt-remote-cast2-receiver-selected",function(){N8(null);
U5("yt-remote-auto-connect","cast-selector-receiver")})),M8.push(g.dq("yt-remote-cast2-receiver-resumed",function(){U5("yt-remote-receiver-resumed","cast-selector-receiver")})),M8.push(g.dq("yt-remote-cast2-session-change",ura)),M8.push(g.dq("yt-remote-connection-change",function(m){m?j8(K8(),"YouTube TV"):O8()||(j8(null,null),ara())})),a=P8(),b.isAuto&&(a.id+="#dial"),g.Lq("desktop_enable_autoplay")&&(a.capabilities=["atp"]),a.name=b.device,a.app=b.app,(k=b.theme)&&(a.theme=k),L8(" -- with channel params: "+
g.Ng(a)),vra(a),c.start(),K8()||wra())},zra=function(){var a=yra();
g8()&&g.xt("yt-remote-cast-available")&&a.push({key:"cast-selector-receiver",name:"Cast..."});return a},yra=function(){var a=J8().Hc.$_gos();
var b=Q8();b&&R8()&&(c6(a,b)||a.push(b));return iqa(a)},S8=function(){var a=Ara();
!a&&g8()&&$qa()&&(a={key:"cast-selector-receiver",name:$qa()});return a},Ara=function(){var a=yra(),b=Q8();
b||(b=O8());return g.Ya(a,function(c){return b&&X5(b,c.key)?!0:!1})},Q8=function(){var a=K8();
if(!a)return null;var b=J8().Kd();return d6(b,a)},ura=function(a){L8("remote.onCastSessionChange_: "+$5(a));
if(a){var b=Q8();b&&b.id==a.id?j8(b.id,"YouTube TV"):(b&&T8(),U8(a,1))}else R8()&&T8()},T8=function(){h8()?e8().stopSession():c8("stopSession called before API ready.");
var a=R8();a&&(a.disconnect(1),V8(null))},W8=function(){var a=R8();
return!!a&&3!=a.getProxyState()},L8=function(a){C7("remote",a)},J8=function(){if(!X8){var a=g.x("yt.mdx.remote.screenService_");
X8=a?new G8(a):null}return X8},K8=function(){return g.x("yt.mdx.remote.currentScreenId_")},Bra=function(a){g.Ha("yt.mdx.remote.currentScreenId_",a,void 0)},Cra=function(){return g.x("yt.mdx.remote.connectData_")},N8=function(a){g.Ha("yt.mdx.remote.connectData_",a,void 0)},R8=function(){return g.x("yt.mdx.remote.connection_")},V8=function(a){var b=R8();
N8(null);a||Bra("");g.Ha("yt.mdx.remote.connection_",a,void 0);I8&&((0,g.A)(I8,function(c){c(a)}),I8.length=0);
b&&!a?U5("yt-remote-connection-change",!1):!b&&a&&U5("yt-remote-connection-change",!0)},O8=function(){var a=g.At();
if(!a)return null;var b=J8().Kd();return d6(b,a)},U8=function(a,b){Q8()&&Q8();
if(Y8)Z8=a;else{Bra(a.id);var c=new z8(H8,a,P8());c.connect(b,Cra());c.subscribe("beforeDisconnect",function(d){U5("yt-remote-before-disconnect",d)});
c.subscribe("beforeDispose",function(){R8()&&V8(null)});
V8(c)}},wra=function(){var a=O8();
a?(L8("Resume connection to: "+$5(a)),U8(a,0)):(m6(),ara(),L8("Skipping connecting because no session screen found."))},tra=function(){var a=P8();
if(g.Yb(a)){a=h6();var b=g.xt("yt-remote-session-name")||"",c=g.xt("yt-remote-session-app")||"";a={device:"REMOTE_CONTROL",id:a,name:b,app:c,mdxVersion:3};g.Ha("yt.mdx.remote.channelParams_",a,void 0)}},P8=function(){return g.x("yt.mdx.remote.channelParams_")||{}},vra=function(a){a?(g.wt("yt-remote-session-app",a.app),g.wt("yt-remote-session-name",a.name)):(g.zt("yt-remote-session-app"),g.zt("yt-remote-session-name"));
g.Ha("yt.mdx.remote.channelParams_",a,void 0)},$8=function(a,b,c){g.G.call(this);
this.u=a;this.i=b;this.l=new g.Ls(this);g.H(this,this.l);this.l.K(b,"onCaptionsTrackListChanged",this.jJ);this.l.K(b,"captionschanged",this.hI);this.l.K(b,"captionssettingschanged",this.rA);this.l.K(b,"videoplayerreset",this.mn);this.l.K(b,"mdxautoplaycancel",this.nC);this.O=this.l.K(b,"onVolumeChange",this.Fy);this.D=!1;this.g=c;c.subscribe("proxyStateChange",this.Qy,this);c.subscribe("remotePlayerChange",this.Bk,this);c.subscribe("remoteQueueChange",this.mn,this);c.subscribe("autoplayUpNext",this.ty,
this);c.subscribe("previousNextChange",this.Ny,this);c.subscribe("nowAutoplaying",this.Jy,this);c.subscribe("autoplayDismissed",this.ry,this);this.suggestion=null;this.F=new g.DC(64);this.o=new g.M(this.pA,500,this);g.H(this,this.o);this.A=new g.M(this.qA,1E3,this);g.H(this,this.A);this.I=new w6(this.MM,0,this);g.H(this,this.I);this.C={};this.P=new g.M(this.PA,1E3,this);g.H(this,this.P);this.H=new g.Ll(this.HF,1E3,this);g.H(this,this.H);this.M=g.Ia;this.rA();this.mn();this.Bk()},a9=function(a,b){a.u.td(b,
a.i.getVideoData().lengthSeconds)},Dra=function(a){a9(a,0);
a.o.stop();b9(a,new g.DC(64))},d9=function(a,b){if(c9(a)&&!a.D){var c=null;
b&&(c={style:a.i.getSubtitlesUserSettings()},g.fc(c,b));a.g.fA(a.i.getVideoData(1).videoId,c);a.C=t8(a.g).g}},e9=function(a,b){var c=a.i.getPlaylist();
if(c){var d=c.Ra;var e=c.listId.toString()}c=a.i.getVideoData(1);a.g.playVideo(c.videoId,b,d,e,c.playerParams,c.Af,P5(c));b9(a,new g.DC(1))},Era=function(a,b){if(b){var c=a.i.getOption("captions","tracklist",{zQ:1});
c&&c.length?(a.i.setOption("captions","track",b),a.D=!1):(a.i.loadModule("captions"),a.D=!0)}else a.i.setOption("captions","track",{})},c9=function(a){return t8(a.g).videoId==a.i.getVideoData(1).videoId},b9=function(a,b){a.A.stop();
var c=a.F;if(!g.JC(c,b)){var d=g.U(b,2);d!=g.U(a.F,2)&&g.sK(a.i,d);a.F=b;Fra(a.u,c,b)}},f9=function(){g.W.call(this,{B:"div",
G:"ytp-mdx-popup-dialog",L:{role:"dialog"},J:[{B:"div",G:"ytp-mdx-popup-dialog-inner-content",J:[{B:"div",G:"ytp-mdx-popup-title",U:"You're signed out"},{B:"div",G:"ytp-mdx-popup-description",U:"Videos you watch may be added to the TV's watch history and influence TV recommendations. To avoid this, cancel and sign in to YouTube on your computer."},{B:"div",G:"ytp-mdx-privacy-popup-buttons",J:[{B:"button",W:["ytp-button","ytp-mdx-privacy-popup-cancel"],U:"Cancel"},{B:"button",W:["ytp-button","ytp-mdx-privacy-popup-confirm"],
U:"Confirm"}]}]}]});this.l=new g.nQ(this,250);g.H(this,this.l);this.C=this.i["ytp-mdx-privacy-popup-cancel"];this.K(this.C,"click",this.o);this.u=this.i["ytp-mdx-privacy-popup-confirm"];this.K(this.u,"click",this.A)},g9=function(a){g.W.call(this,{B:"div",
G:"ytp-remote",J:[{B:"div",G:"ytp-remote-display-status",J:[{B:"div",G:"ytp-remote-display-status-icon",J:[g.DP()]},{B:"div",G:"ytp-remote-display-status-text",U:"{{statustext}}"}]}]});this.l=new g.nQ(this,250);g.H(this,this.l);this.o=a;this.K(a,"presentingplayerstatechange",this.u);Gra(this,g.oK(a))},Gra=function(a,b){if(3==a.o.getPresentingPlayerType()){var c={RECEIVER_NAME:a.o.getOption("remote","currentReceiver").name};
c=g.U(b,128)?g.BN("Error on $RECEIVER_NAME",c):g.KC(b)||g.U(b,4)?g.BN("Playing on $RECEIVER_NAME",c):g.BN("Connected to $RECEIVER_NAME",c);a.updateValue("statustext",c);a.l.show()}else a.l.hide()},h9=function(a,b){g.ZT.call(this,"Play on",0,a,b);
this.l=a;this.F={};this.K(a,"onMdxReceiversChange",this.I);this.K(a,"presentingplayerstatechange",this.I);this.I()},i9=function(a){g.RK.call(this,a);
this.i={key:b6(),name:"This computer"};this.u=null;this.l=[];this.C=this.g=null;this.A=[this.i];this.o=this.i;this.hk=new g.DC(64);this.H=0;this.Dm=-1;if(!g.mz(g.X(this.player))){a=this.player;var b=g.wD(a);b&&(b=b.jk())&&(b=new h9(a,b),g.H(this,b));b=new g9(a);g.H(this,b);g.DK(a,b.element,4);this.F=new f9;g.H(this,this.F);g.DK(a,this.F.element,4);this.D=!!O8()}},Fra=function(a,b,c){a.hk=c;
a.player.N("presentingplayerstatechange",new g.KD(c,b))},j9=function(a,b){if(b.key!=a.o.key)if(b.key==a.i.key)T8();
else{var c;if(c=g.Q(g.X(a.player).experiments,"mdx_enable_privacy_disclosure"))c=g.Pp("PLAYER_CONFIG"),c=!(c&&c.args&&void 0!==c.args.authuser||g.Pp("SESSION_INDEX")||g.Pp("LOGGED_IN"));c&&!a.D&&(a.player.pauseVideo(),a.F.l.show(),R8()||(Y8=!0));a.o=b;var d=a.player.getPlaylistId();c=a.player.getVideoData(1);var e=c.videoId;if(d||e){var f=a.player.getPlaylist();if(f){var k=[];for(var l=0;l<f.getLength();l++)k[l]=f.oa(l).videoId}else k=[e];f=a.player.getCurrentTime(1);d={videoIds:k,listId:d,videoId:e,
playerParams:c.playerParams,clickTrackingParams:c.Af,index:Math.max(a.player.getPlaylistIndex(),0),currentTime:0==f?void 0:f};(c=P5(c))&&(d.locationInfo=c);c=d}else c=null;L8("Connecting to: "+g.Ng(b));"cast-selector-receiver"==b.key?(N8(c||null),h8()?e8().setLaunchParams(c||null):c8("setLaunchParams called before ready.")):!c&&W8()&&K8()==b.key?U5("yt-remote-connection-change",!0):(T8(),N8(c||null),c=J8().Kd(),(c=d6(c,b.key))&&U8(c,1))}},Zpa=/^https?$/i,Hra=["POST",
"PUT"];g.Ta(N5,g.Uf);g.h=N5.prototype;
g.h.send=function(a,b,c,d){if(this.g)throw Error("[goog.net.XhrIo] Object is active with another request="+this.F+"; newUri="+a);b=b?b.toUpperCase():"GET";this.F=a;this.l="";this.u=0;this.ba=b;this.O=!1;this.i=!0;this.g=this.M?F5(this.M):F5(g.ZY);this.P=this.M?this.M.getOptions():g.ZY.getOptions();this.g.onreadystatechange=(0,g.y)(this.Vv,this);try{C5(G5(this,"Opening Xhr")),this.V=!0,this.g.open(b,String(a),!0),this.V=!1}catch(f){C5(G5(this,"Error opening Xhr: "+f.message));K5(this,f);return}a=c||
"";var e=this.headers.clone();d&&Wpa(d,function(f,k){e.set(k,f)});
d=g.Ya(e.Id(),Xpa);c=g.w.FormData&&a instanceof g.w.FormData;!g.ab(Hra,b)||d||c||e.set("Content-Type","application/x-www-form-urlencoded;charset=utf-8");e.forEach(function(f,k){this.g.setRequestHeader(k,f)},this);
this.Z&&(this.g.responseType=this.Z);"withCredentials"in this.g&&this.g.withCredentials!==this.R&&(this.g.withCredentials=this.R);try{H5(this),0<this.A&&(this.I=Ypa(this.g),C5(G5(this,"Will abort after "+this.A+"ms if incomplete, xhr2 "+this.I)),this.I?(this.g.timeout=this.A,this.g.ontimeout=(0,g.y)(this.Wv,this)):this.C=g.Jg(this.Wv,this.A,this)),C5(G5(this,"Sending request")),this.D=!0,this.g.send(a),this.D=!1}catch(f){C5(G5(this,"Send error: "+f.message)),K5(this,f)}};
g.h.Wv=function(){"undefined"!=typeof g.CY&&this.g&&(this.l="Timed out after "+this.A+"ms, aborting",this.u=8,G5(this,this.l),this.dispatchEvent("timeout"),this.abort(8))};
g.h.abort=function(a){this.g&&this.i&&(G5(this,"Aborting"),this.i=!1,this.o=!0,this.g.abort(),this.o=!1,this.u=a||7,this.dispatchEvent("complete"),this.dispatchEvent("abort"),J5(this))};
g.h.T=function(){this.g&&(this.i&&(this.i=!1,this.o=!0,this.g.abort(),this.o=!1),J5(this,!0));N5.Xa.T.call(this)};
g.h.Vv=function(){this.da()||(this.V||this.D||this.o?M5(this):this.oK())};
g.h.oK=function(){M5(this)};
g.h.isActive=function(){return!!this.g};
g.h.getStatus=function(){try{return 2<L5(this)?this.g.status:-1}catch(a){return-1}};
g.h.getLastError=function(){return g.v(this.l)?this.l:String(this.l)};
var L6={"\x00":"\\0","\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\x0B",'"':'\\"',"\\":"\\\\","<":"<"},K6={"'":"\\'"},Ira={};g.h=T5.prototype;g.h.isEmpty=function(){return 0==this.g.length&&0==this.i.length};
g.h.clear=function(){this.g=[];this.i=[]};
g.h.contains=function(a){return g.ab(this.g,a)||g.ab(this.i,a)};
g.h.remove=function(a){var b=this.g;var c=(0,g.Jma)(b,a);0<=c?(g.cb(b,c),b=!0):b=!1;return b||g.db(this.i,a)};
g.h.zc=function(){for(var a=[],b=this.g.length-1;0<=b;--b)a.push(this.g[b]);var c=this.i.length;for(b=0;b<c;++b)a.push(this.i[b]);return a};
var gqa={CN:"atp",NP:"ska",CP:"que",bP:"mus",MP:"sus",sO:"dsp",JP:"seq"};V5.prototype.dg=function(){var a=new V5({id:this.id,name:this.name,app:this.app,type:this.type,user:this.username,userAvatarUri:this.avatar,obfuscatedGaiaId:this.obfuscatedGaiaId,theme:this.theme,capabilities:Array.from(this.capabilities.values()).join(","),experiments:Array.from(this.experiments.values()).join(",")});a.l=this.l;a.i=this.i;a.g=this.g};
var n6,g6="",u6=p6("loadGamesSDK")?"/cast_game_sender.js":"/cast_sender.js",oqa=p6("loadCastFramework")||p6("loadCastApplicationFramework"),Xqa=["pkedcjkdefgpdelpbcmbmeomcjbeemfm","enhhojjnijigcajfphajepfemndkmdlo"];g.Ta(w6,g.G);g.h=w6.prototype;g.h.gD=function(a){this.o=arguments;this.g=!1;this.za?this.l=(0,g.B)()+this.Vc:this.za=g.Jg(this.u,this.Vc)};
g.h.stop=function(){this.za&&(g.w.clearTimeout(this.za),this.za=null);this.l=null;this.g=!1;this.o=[]};
g.h.pause=function(){++this.i};
g.h.resume=function(){this.i&&(--this.i,!this.i&&this.g&&(this.g=!1,this.A.apply(null,this.o)))};
g.h.T=function(){this.stop();w6.Xa.T.call(this)};
g.h.hD=function(){this.l?(this.za=g.Jg(this.u,this.l-(0,g.B)()),this.l=null):(this.za=null,this.i?this.g=!0:(this.g=!1,this.A.apply(null,this.o)))};x6.prototype.stringify=function(a){return g.w.JSON.stringify(a,void 0)};
x6.prototype.parse=function(a){return g.w.JSON.parse(a,void 0)};g.h=y6.prototype;g.h.Xg=null;g.h.ye=!1;g.h.Wi=null;g.h.Vs=null;g.h.Fi=null;g.h.Yh=null;g.h.lg=null;g.h.Cg=null;g.h.rh=null;g.h.tc=null;g.h.Xk=0;g.h.Ce=null;g.h.jo=null;g.h.mg=null;g.h.Oj=-1;g.h.Sz=!0;g.h.Ng=!1;g.h.Pp=0;g.h.An=null;var F6={},D6={};g.h=y6.prototype;g.h.setTimeout=function(a){this.o=a};
g.h.XL=function(a){a=a.target;var b=this.An;b&&3==L5(a)?b.Kj():this.YA(a)};
g.h.YA=function(a){try{if(a==this.tc)a:{var b=L5(this.tc),c=this.tc.u,d=this.tc.getStatus();if(g.Nd&&!g.qd(10)||g.Pd&&!g.pd("420+")){if(4>b)break a}else if(3>b||3==b&&!g.Fh&&!O5(this.tc))break a;this.Ng||4!=b||7==c||(8==c||0>=d?this.g.te(3):this.g.te(2));P6(this);var e=this.tc.getStatus();this.Oj=e;var f=O5(this.tc);(this.ye=200==e)?(4==b&&H6(this),this.u?(J6(this,b,f),g.Fh&&this.ye&&3==b&&(this.aa.ca(this.i,"tick",this.RL),this.i.start())):G6(this,f),this.ye&&!this.Ng&&(4==b?this.g.kn(this):(this.ye=
!1,C6(this)))):(400==e&&0<f.indexOf("Unknown SID")?(this.mg=3,E6(13)):(this.mg=0,E6(14)),H6(this),I6(this))}}catch(k){this.tc&&O5(this.tc)}finally{}};
g.h.RL=function(){var a=L5(this.tc),b=O5(this.tc);this.Xk<b.length&&(P6(this),J6(this,a,b),this.ye&&4!=a&&C6(this))};
g.h.oL=function(a){O6((0,g.y)(this.nL,this,a),0)};
g.h.nL=function(a){this.Ng||(P6(this),G6(this,a),C6(this))};
g.h.Xy=function(a){O6((0,g.y)(this.mL,this,a),0)};
g.h.mL=function(a){this.Ng||(H6(this),this.ye=a,this.g.kn(this),this.g.te(4))};
g.h.cancel=function(){this.Ng=!0;H6(this)};
g.h.yL=function(){this.Wi=null;var a=(0,g.B)();0<=a-this.Vs?(2!=this.Yh&&this.g.te(3),H6(this),this.mg=2,E6(18),I6(this)):N6(this,this.Vs-a)};
g.h.getLastError=function(){return this.mg};g.h=T6.prototype;g.h.Np=null;g.h.Ed=null;g.h.Bn=!1;g.h.Uv=null;g.h.Vl=null;g.h.Bq=null;g.h.Op=null;g.h.de=null;g.h.xf=-1;g.h.Nj=null;g.h.gj=null;g.h.connect=function(a){this.Op=a;a=U6(this.g,null,this.Op);E6(3);this.Uv=(0,g.B)();var b=this.g.D;null!=b?(this.Nj=b[0],(this.gj=b[1])?(this.de=1,V6(this)):(this.de=2,X6(this))):(E5(a,"MODE","init"),this.Ed=new y6(this,void 0,void 0,void 0),this.Ed.Xg=this.Np,B6(this.Ed,a,!1,null,!0),this.de=0)};
g.h.oC=function(a){if(a)this.de=2,X6(this);else{E6(4);var b=this.g;b.Je=b.cg.xf;q7(b,9)}a&&this.te(2)};
g.h.jp=function(a){return this.g.jp(a)};
g.h.abort=function(){this.Ed&&(this.Ed.cancel(),this.Ed=null);this.xf=-1};
g.h.Tv=function(){return!1};
g.h.Ry=function(a,b){this.xf=a.Oj;if(0==this.de)if(b){try{var c=this.i.parse(b)}catch(d){c=this.g;c.Je=this.xf;q7(c,2);return}this.Nj=c[0];this.gj=c[1]}else c=this.g,c.Je=this.xf,q7(c,2);else if(2==this.de)if(this.Bn)E6(7),this.Bq=(0,g.B)();else if("11111"==b){if(E6(6),this.Bn=!0,this.Vl=(0,g.B)(),c=this.Vl-this.Uv,!g.Nd||g.qd(10)||500>c)this.xf=200,this.Ed.cancel(),E6(12),W6(this.g,this,!0)}else E6(8),this.Vl=this.Bq=(0,g.B)(),this.Bn=!1};
g.h.kn=function(){this.xf=this.Ed.Oj;if(this.Ed.ye)0==this.de?this.gj?(this.de=1,V6(this)):(this.de=2,X6(this)):2==this.de&&((!g.Nd||g.qd(10)?!this.Bn:200>this.Bq-this.Vl)?(E6(11),W6(this.g,this,!1)):(E6(12),W6(this.g,this,!0)));else{0==this.de?E6(9):2==this.de&&E6(10);var a=this.g;this.Ed.getLastError();a.Je=this.xf;q7(a,2)}};
g.h.Ok=function(){return this.g.Ok()};
g.h.isActive=function(){return this.g.isActive()};
g.h.te=function(a){this.g.te(a)};g.h=Y6.prototype;g.h.tj=null;g.h.Bd=null;g.h.Sb=null;g.h.Mp=null;g.h.Xl=null;g.h.nu=null;g.h.km=null;g.h.wk=0;g.h.CH=0;g.h.Tc=null;g.h.hg=null;g.h.kf=null;g.h.Sg=null;g.h.cg=null;g.h.fo=null;g.h.ki=-1;g.h.Bw=-1;g.h.Je=-1;g.h.Sh=0;g.h.Kh=0;g.h.Og=8;var r7=new g.Uf;g.Ta(Z6,g.uf);g.Ta($6,g.uf);g.Ta(a7,g.uf);g.h=Y6.prototype;g.h.connect=function(a,b,c,d,e){E6(0);this.Mp=b;this.tj=c||{};d&&g.Ea(e)&&(this.tj.OSID=d,this.tj.OAID=e);this.A?(O6((0,g.y)(this.Eu,this,a),100),g7(this)):this.Eu(a)};
g.h.Eu=function(a){this.cg=new T6(this);this.cg.Np=null;this.cg.i=this.u;this.cg.connect(a)};
g.h.Tv=function(){return 0==this.g};
g.h.Wy=function(a){this.hg=null;l7(this,a)};
g.h.Vy=function(){this.kf=null;this.Sb=new y6(this,this.l,"rpc",this.C);this.Sb.Xg=null;this.Sb.Pp=0;var a=this.nu.clone();g.ln(a,"RID","rpc");g.ln(a,"SID",this.l);g.ln(a,"CI",this.fo?"0":"1");g.ln(a,"AID",this.ki);c7(this,a);if(!g.Nd||g.qd(10))g.ln(a,"TYPE","xmlhttp"),B6(this.Sb,a,!0,this.km,!1);else{g.ln(a,"TYPE","html");var b=this.Sb,c=!!this.km;b.Yh=3;b.lg=D5(a.clone());M6(b,c)}};
g.h.Ry=function(a,b){if(0!=this.g&&(this.Sb==a||this.Bd==a))if(this.Je=a.Oj,this.Bd==a&&3==this.g)if(7<this.Og){try{var c=this.u.parse(b)}catch(f){c=null}if(g.La(c)&&3==c.length)if(0==c[0])a:{if(!this.kf){if(this.Sb)if(this.Sb.Fi+3E3<this.Bd.Fi)h7(this),this.Sb.cancel(),this.Sb=null;else break a;o7(this);E6(19)}}else this.Bw=c[1],0<this.Bw-this.ki&&37500>c[2]&&this.fo&&0==this.Kh&&!this.Sg&&(this.Sg=O6((0,g.y)(this.dI,this),6E3));else q7(this,11)}else b!=Ira.XN.g&&q7(this,11);else if(this.Sb==a&&
h7(this),!g.xb(b)){c=this.u.parse(b);g.La(c);for(var d=0;d<c.length;d++){var e=c[d];this.ki=e[0];e=e[1];2==this.g?"c"==e[0]?(this.l=e[1],this.km=e[2],e=e[3],null!=e?this.Og=e:this.Og=6,this.g=3,this.Tc&&this.Tc.yu(),this.nu=U6(this,this.Ok()?this.km:null,this.Mp),m7(this)):"stop"==e[0]&&q7(this,7):3==this.g&&("stop"==e[0]?q7(this,7):"noop"!=e[0]&&this.Tc&&this.Tc.xu(e),this.Kh=0)}}};
g.h.dI=function(){null!=this.Sg&&(this.Sg=null,this.Sb.cancel(),this.Sb=null,o7(this),E6(20))};
g.h.kn=function(a){if(this.Sb==a){h7(this);this.Sb=null;var b=2}else if(this.Bd==a)this.Bd=null,b=1;else return;this.Je=a.Oj;if(0!=this.g)if(a.ye)1==b?(b=(0,g.B)()-a.Fi,r7.dispatchEvent(new $6(r7,a.rh?a.rh.length:0,b,this.Sh)),f7(this),this.o.length=0):m7(this);else{var c=a.getLastError(),d;if(!(d=3==c||7==c||0==c&&0<this.Je)){if(d=1==b)this.Bd||this.hg||1==this.g||2<=this.Sh?d=!1:(this.hg=O6((0,g.y)(this.Wy,this,a),n7(this,this.Sh)),this.Sh++,d=!0);d=!(d||2==b&&o7(this))}if(d)switch(c){case 1:q7(this,
5);break;case 4:q7(this,10);break;case 3:q7(this,6);break;case 7:q7(this,12);break;default:q7(this,2)}}};
g.h.FC=function(a){if(!g.ab(arguments,this.g))throw Error("Unexpected channel state: "+this.g);};
g.h.DM=function(a){a?E6(2):(E6(1),p7(this,8))};
g.h.jp=function(a){if(a)throw Error("Can't create secondary domain capable XhrIo object.");a=new N5;a.R=!1;return a};
g.h.isActive=function(){return!!this.Tc&&this.Tc.isActive(this)};
g.h.te=function(a){r7.dispatchEvent(new a7(r7,a))};
g.h.Ok=function(){return!(!g.Nd||g.qd(10))};
g.h=s7.prototype;g.h.yu=function(){};
g.h.xu=function(){};
g.h.wu=function(){};
g.h.Wo=function(){};
g.h.xv=function(){return{}};
g.h.isActive=function(){return!0};g.Ta(t7,g.G);g.h=t7.prototype;g.h.gL=function(){this.Vc=Math.min(3E5,2*this.Vc);this.l();this.i&&this.start()};
g.h.start=function(){var a=this.Vc+15E3*Math.random();g.vo(this.g,a);this.i=(0,g.B)()+a};
g.h.stop=function(){this.g.stop();this.i=0};
g.h.isActive=function(){return this.g.isActive()};
g.h.reset=function(){this.g.stop();this.Vc=5E3};g.Ta(u7,s7);g.h=u7.prototype;g.h.subscribe=function(a,b,c){return this.l.subscribe(a,b,c)};
g.h.unsubscribe=function(a,b,c){return this.l.unsubscribe(a,b,c)};
g.h.Hf=function(a){return this.l.Yg(a)};
g.h.N=function(a,b){return this.l.N.apply(this.l,arguments)};
g.h.dispose=function(){this.Za||(this.Za=!0,g.sf(this.l),v7(this),g.sf(this.i),this.i=null)};
g.h.da=function(){return this.Za};
g.h.connect=function(a,b,c){if(!this.g||2!=this.g.g){this.F="";this.i.stop();this.u=a||null;this.o=b||0;a=this.H+"/test";b=this.H+"/bind";var d=new Y6(c?c.firstTestResults:null,c?c.secondTestResults:null,this.I),e=this.g;e&&(e.Tc=null);d.Tc=this;this.g=d;e?this.g.connect(a,b,this.A,e.l,e.ki):c?this.g.connect(a,b,this.A,c.sessionId,c.arrayId):this.g.connect(a,b,this.A)}};
g.h.sendMessage=function(a,b){var c={_sc:a};b&&g.fc(c,b);this.i.isActive()||2==(this.g?this.g.g:0)?this.C.push(c):w7(this)&&i7(this.g,c)};
g.h.yu=function(){this.i.reset();this.u=null;this.o=0;if(this.C.length){var a=this.C;this.C=[];for(var b=0,c=a.length;b<c;++b)i7(this.g,a[b])}this.N("handlerOpened")};
g.h.wu=function(a){var b=2==a&&401==this.g.Je;4==a||b||this.i.start();this.N("handlerError",a)};
g.h.Wo=function(a){if(!this.i.isActive())this.N("handlerClosed");else if(a)for(var b=0,c=a.length;b<c;++b){var d=a[b].map;d&&this.C.push(d)}};
g.h.xv=function(){var a={v:2};this.F&&(a.gsessionid=this.F);0!=this.o&&(a.ui=""+this.o);0!=this.D&&(a.ui=""+this.D);this.u&&g.fc(a,this.u);return a};
g.h.xu=function(a){"S"==a[0]?this.F=a[1]:"gracefulReconnect"==a[0]?(this.i.start(),e7(this.g)):this.N("handlerMessage",new sqa(a[0],a[1]))};
g.h.gM=function(){this.i.isActive();var a=this.g,b=0;a.Sb&&b++;a.Bd&&b++;0==b&&this.connect(this.u,this.o)};x7.prototype.o=function(a,b,c,d){b?a(d):a({text:c.responseText})};
x7.prototype.l=function(a,b){a(Error("Request error: "+b.status))};
x7.prototype.u=function(a){a(Error("request timed out"))};var Aqa=(0,g.B)(),B7=null,E7=Array(50),D7=-1,F7=!1;g.Ta(G7,g.P);G7.prototype.Kd=function(){return this.g};
G7.prototype.contains=function(a){return!!c6(this.g,a)};
G7.prototype.get=function(a){return a?d6(this.g,a):null};
G7.prototype.info=function(a){C7(this.C,a)};g.t(H7,g.P);g.h=H7.prototype;g.h.start=function(){!this.g&&isNaN(this.za)&&this.bB()};
g.h.stop=function(){this.g&&(this.g.abort(),this.g=null);isNaN(this.za)||(g.Zp(this.za),this.za=NaN)};
g.h.T=function(){this.stop();g.P.prototype.T.call(this)};
g.h.bB=function(){this.za=NaN;this.g=g.Uq(y7(this.A,"/pairing/get_screen"),{method:"POST",qb:{pairing_code:this.u},timeout:5E3,onSuccess:(0,g.y)(this.cN,this),onError:(0,g.y)(this.bN,this),rd:(0,g.y)(this.dN,this)})};
g.h.cN=function(a,b){this.g=null;var c=b.screen||{};c.dialId=this.l;c.name=this.o;this.N("pairingComplete",new W5(c))};
g.h.bN=function(a){this.g=null;a.status&&404==a.status?this.i>=Jra.length?this.N("pairingFailed",Error("DIAL polling timed out")):(a=Jra[this.i],this.za=g.Xp((0,g.y)(this.bB,this),a),this.i++):this.N("pairingFailed",Error("Server error "+a.status))};
g.h.dN=function(){this.g=null;this.N("pairingFailed",Error("Server not responding"))};
var Jra=[2E3,2E3,1E3,1E3,1E3,2E3,2E3,5E3,5E3,1E4];g.Ta(J7,G7);g.h=J7.prototype;g.h.start=function(){I7(this)&&this.N("screenChange");!g.xt("yt-remote-lounge-token-expiration")&&Eqa(this);g.Zp(this.i);this.i=g.Xp((0,g.y)(this.start,this),1E4)};
g.h.add=function(a,b){I7(this);Bqa(this,a);K7(this,!1);this.N("screenChange");b(a);a.token||Eqa(this)};
g.h.remove=function(a,b){var c=I7(this);Dqa(this,a)&&(K7(this,!1),c=!0);b(a);c&&this.N("screenChange")};
g.h.ao=function(a,b,c,d){var e=I7(this),f=this.get(a.id);f?(f.name!=b&&(f.name=b,K7(this,!1),e=!0),c(a)):d(Error("no such local screen."));e&&this.N("screenChange")};
g.h.T=function(){g.Zp(this.i);J7.Xa.T.call(this)};
g.h.rD=function(a){I7(this);var b=this.g.length;a=a&&a.screens||[];for(var c=0,d=a.length;c<d;++c){var e=a[c],f=this.get(e.screenId);f&&(f.token=e.loungeToken,--b)}K7(this,!b);b&&C7(this.C,"Missed "+b+" lounge tokens.")};
g.h.qD=function(a){C7(this.C,"Requesting lounge tokens failed: "+a)};g.t(M7,g.P);g.h=M7.prototype;g.h.start=function(){var a=parseInt(g.xt("yt-remote-fast-check-period")||"0",10);(this.o=(0,g.B)()-144E5<a?0:a)?O7(this):(this.o=(0,g.B)()+3E5,g.wt("yt-remote-fast-check-period",this.o),this.Ur())};
g.h.isEmpty=function(){return g.Yb(this.g)};
g.h.update=function(){L7("Updating availability on schedule.");var a=this.A(),b=g.Mb(this.g,function(c,d){return c&&!!d6(a,d)},this);
N7(this,b)};
g.h.T=function(){g.Zp(this.l);this.l=NaN;this.i&&(this.i.abort(),this.i=null);g.P.prototype.T.call(this)};
g.h.Ur=function(){g.Zp(this.l);this.l=NaN;this.i&&this.i.abort();var a=Hqa(this);if(Q5(a)){var b=y7(this.u,"/pairing/get_screen_availability");this.i=z7(this.u,b,{lounge_token:g.Sb(a).join(",")},(0,g.y)(this.KK,this,a),(0,g.y)(this.JK,this))}else N7(this,{}),O7(this)};
g.h.KK=function(a,b){this.i=null;var c=g.Sb(Hqa(this));if(g.sb(c,g.Sb(a))){c=b.screens||[];for(var d={},e=0,f=c.length;e<f;++e)d[a[c[e].loungeToken]]="online"==c[e].status;N7(this,d);O7(this)}else this.Jb("Changing Screen set during request."),this.Ur()};
g.h.JK=function(a){this.Jb("Screen availability failed: "+a);this.i=null;O7(this)};
g.h.Jb=function(a){C7("OnlineScreenService",a)};g.Ta(P7,G7);g.h=P7.prototype;g.h.start=function(){this.l.start();this.i.start();this.g.length&&(this.N("screenChange"),this.i.isEmpty()||this.N("onlineScreenChange"))};
g.h.add=function(a,b,c){this.l.add(a,b,c)};
g.h.remove=function(a,b,c){this.l.remove(a,b,c);this.i.update()};
g.h.ao=function(a,b,c,d){this.l.contains(a)?this.l.ao(a,b,c,d):(a="Updating name of unknown screen: "+a.name,C7(this.C,a),d(Error(a)))};
g.h.Kd=function(a){return a?this.g:g.fb(this.g,(0,g.Zd)(this.o,function(b){return!this.contains(b)},this))};
g.h.cB=function(){return(0,g.Zd)(this.Kd(!0),function(a){return!!this.i.g[a.id]},this)};
g.h.dB=function(a,b,c,d,e){this.info("getDialScreenByPairingCode "+a+" / "+b);var f=new H7(this.A,a,b,c);f.subscribe("pairingComplete",(0,g.y)(function(k){g.sf(f);d(Q7(this,k))},this));
f.subscribe("pairingFailed",function(k){g.sf(f);e(k)});
f.start();return(0,g.y)(f.stop,f)};
g.h.fN=function(a,b,c,d){g.Uq(y7(this.A,"/pairing/get_screen"),{method:"POST",qb:{pairing_code:a},timeout:5E3,onSuccess:(0,g.y)(function(e,f){var k=new W5(f.screen||{});if(!k.name||Lqa(this,k.name)){a:{var l=k.name;for(var m=2,n=b(l,m);Lqa(this,n);){m++;if(20<m)break a;n=b(l,m)}l=n}k.name=l}c(Q7(this,k))},this),
onError:(0,g.y)(function(e){d(Error("pairing request failed: "+e.status))},this),
rd:(0,g.y)(function(){d(Error("pairing request timed out."))},this)})};
g.h.T=function(){g.sf(this.l);g.sf(this.i);P7.Xa.T.call(this)};
g.h.AD=function(){Mqa(this);this.N("screenChange");this.i.update()};
P7.prototype.dispose=P7.prototype.dispose;g.Ta(S7,g.P);g.h=S7.prototype;g.h.ln=function(a){this.l=a;this.N("sessionScreen",this.l)};
g.h.Nd=function(a){this.da()||(a&&T7(this,""+a),this.l=null,this.N("sessionScreen",null))};
g.h.info=function(a){C7(this.P,a)};
g.h.fB=function(){return null};
g.h.ks=function(a){var b=this.i;a?(b.displayStatus=new chrome.cast.ReceiverDisplayStatus(a,[]),b.displayStatus.showStop=!0):b.displayStatus=null;chrome.cast.setReceiverDisplayStatus(b,(0,g.y)(function(){this.info("Updated receiver status for "+b.friendlyName+": "+a)},this),(0,g.y)(function(){T7(this,"Failed to update receiver status for: "+b.friendlyName)},this))};
g.h.T=function(){this.ks("");S7.Xa.T.call(this)};g.Ta(U7,S7);g.h=U7.prototype;g.h.hs=function(a){if(this.g){if(this.g==a)return;T7(this,"Overriding cast sesison with new session object");this.g.removeUpdateListener(this.A);this.g.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.u)}this.g=a;this.g.addUpdateListener(this.A);this.g.addMessageListener("urn:x-cast:com.google.youtube.mdx",this.u);Oqa(this)};
g.h.mi=function(a){this.info("launchWithParams no-op for Cast: "+g.Ng(a))};
g.h.stop=function(){this.g?this.g.stop((0,g.y)(function(){this.Nd()},this),(0,g.y)(function(){this.Nd(Error("Failed to stop receiver app."))},this)):this.Nd(Error("Stopping cast device witout session."))};
g.h.ks=g.Ia;g.h.T=function(){this.info("disposeInternal");g.Zp(this.o);this.o=0;this.g&&(this.g.removeUpdateListener(this.A),this.g.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.u));this.g=null;U7.Xa.T.call(this)};
g.h.JL=function(a,b){if(!this.da())if(b){var c=S5(b);if(g.Oa(c)){var d=""+c.type;c=c.data||{};this.info("onYoutubeMessage_: "+d+" "+g.Ng(c));switch(d){case "mdxSessionStatus":Nqa(this,c.screenId);break;default:T7(this,"Unknown youtube message: "+d)}}else T7(this,"Unable to parse message.")}else T7(this,"No data in message.")};
g.h.Nv=function(a,b,c,d){Kqa(this.F,this.i.label,a,this.i.friendlyName,(0,g.y)(function(e){e?b(e):0<=d?(T7(this,"Screen "+a+" appears to be offline. "+d+" retries left."),g.Xp((0,g.y)(this.Nv,this,a,b,c,d-1),300)):c(Error("Unable to fetch screen."))},this),c)};
g.h.fB=function(){return this.g};
g.h.gN=function(a){this.da()||a||(T7(this,"Cast session died."),this.Nd())};g.Ta(V7,S7);g.h=V7.prototype;g.h.hs=function(a){this.o=a;this.o.addUpdateListener(this.I)};
g.h.mi=function(a){this.u=a;this.C()};
g.h.stop=function(){this.g();this.g=g.Ia;g.Zp(this.A);this.o?this.o.stop((0,g.y)(this.Nd,this,null),(0,g.y)(this.Nd,this,"Failed to stop DIAL device.")):this.Nd()};
g.h.T=function(){this.g();this.g=g.Ia;g.Zp(this.A);this.o&&this.o.removeUpdateListener(this.I);this.o=null;V7.Xa.T.call(this)};
g.h.jN=function(a){this.da()||a||(T7(this,"DIAL session died."),this.g(),this.g=g.Ia,this.Nd())};
g.h.cq=function(a){this.H=b6();if(this.u){var b=new chrome.cast.DialLaunchResponse(!0,Qqa(this));a(b);Pqa(this)}else this.C=(0,g.y)(function(){g.Zp(this.A);this.C=g.Ia;this.A=NaN;var c=new chrome.cast.DialLaunchResponse(!0,Qqa(this));a(c);Pqa(this)},this),this.A=g.Xp((0,g.y)(function(){this.C()},this),100)};
g.h.XD=function(a,b,c){Kqa(this.F,this.D.receiver.label,a,this.i.friendlyName,(0,g.y)(function(d){d&&d.token?(this.ln(d),b(new chrome.cast.DialLaunchResponse(!1))):this.cq(b,c)},this),(0,g.y)(function(d){T7(this,"Failed to get DIAL screen: "+d);
this.cq(b,c)},this))};g.Ta(W7,S7);W7.prototype.stop=function(){this.Nd()};
W7.prototype.hs=g.Ia;W7.prototype.mi=function(){g.Zp(this.g);this.g=NaN;var a=d6(this.F.Kd(),this.i.label);a?this.ln(a):this.Nd(Error("No such screen"))};
W7.prototype.T=function(){g.Zp(this.g);this.g=NaN;W7.Xa.T.call(this)};g.Ta(X7,g.P);g.h=X7.prototype;
g.h.init=function(a,b){chrome.cast.timeout.requestSession=3E4;var c=new chrome.cast.SessionRequest(this.C);this.D||(c.dialRequest=new chrome.cast.DialRequest("YouTube"));var d=chrome.cast.AutoJoinPolicy.TAB_AND_ORIGIN_SCOPED,e=a?chrome.cast.DefaultActionPolicy.CAST_THIS_TAB:chrome.cast.DefaultActionPolicy.CREATE_SESSION;c=new chrome.cast.ApiConfig(c,(0,g.y)(this.Ty,this),(0,g.y)(this.tK,this),d,e);c.customDialLaunchCallback=(0,g.y)(this.FI,this);chrome.cast.initialize(c,(0,g.y)(function(){this.da()||
(chrome.cast.addReceiverActionListener(this.o),xqa(),this.i.subscribe("onlineScreenChange",(0,g.y)(this.eB,this)),this.l=Sqa(this),chrome.cast.setCustomReceivers(this.l,g.Ia,(0,g.y)(function(f){this.Jb("Failed to set initial custom receivers: "+g.Ng(f))},this)),this.N("yt-remote-cast2-availability-change",Z7(this)),b(!0))},this),(0,g.y)(function(f){this.Jb("Failed to initialize API: "+g.Ng(f));
b(!1)},this))};
g.h.qM=function(a,b){Y7("Setting connected screen ID: "+a+" -> "+b);if(this.g){var c=this.g.l;if(!a||c&&c.id!=a)Y7("Unsetting old screen status: "+this.g.i.friendlyName),$7(this,null)}if(a&&b){if(!this.g){c=d6(this.i.Kd(),a);if(!c){Y7("setConnectedScreenStatus: Unknown screen.");return}var d=Rqa(this,c);d||(Y7("setConnectedScreenStatus: Connected receiver not custom..."),d=new chrome.cast.Receiver(c.uuid?c.uuid:c.id,c.name),d.receiverType=chrome.cast.ReceiverType.CUSTOM,this.l.push(d),chrome.cast.setCustomReceivers(this.l,
g.Ia,(0,g.y)(function(e){this.Jb("Failed to set initial custom receivers: "+g.Ng(e))},this)));
Y7("setConnectedScreenStatus: new active receiver: "+d.friendlyName);$7(this,new W7(this.i,d),!0)}this.g.ks(b)}else Y7("setConnectedScreenStatus: no screen.")};
g.h.rM=function(a){this.da()?this.Jb("Setting connection data on disposed cast v2"):this.g?this.g.mi(a):this.Jb("Setting connection data without a session")};
g.h.iN=function(){this.da()?this.Jb("Stopping session on disposed cast v2"):this.g?(this.g.stop(),$7(this,null)):Y7("Stopping non-existing session")};
g.h.requestSession=function(){chrome.cast.requestSession((0,g.y)(this.Ty,this),(0,g.y)(this.PK,this))};
g.h.T=function(){this.i.unsubscribe("onlineScreenChange",(0,g.y)(this.eB,this));window.chrome&&chrome.cast&&chrome.cast.removeReceiverActionListener(this.o);g.db(g.x("yt.mdx.remote.debug.handlers_")||[],A7);g.sf(this.g);X7.Xa.T.call(this)};
g.h.Jb=function(a){C7("Controller",a)};
g.h.Uy=function(a,b){this.g==a&&(b||$7(this,null),this.N("yt-remote-cast2-session-change",b))};
g.h.pK=function(a,b){if(!this.da())if(a)switch(a.friendlyName=chrome.cast.unescape(a.friendlyName),Y7("onReceiverAction_ "+a.label+" / "+a.friendlyName+"-- "+b),b){case chrome.cast.ReceiverAction.CAST:if(this.g)if(this.g.i.label!=a.label)Y7("onReceiverAction_: Stopping active receiver: "+this.g.i.friendlyName),this.g.stop();else{Y7("onReceiverAction_: Casting to active receiver.");this.g.l&&this.N("yt-remote-cast2-session-change",this.g.l);break}switch(a.receiverType){case chrome.cast.ReceiverType.CUSTOM:$7(this,
new W7(this.i,a));break;case chrome.cast.ReceiverType.DIAL:$7(this,new V7(this.i,a,this.A));break;case chrome.cast.ReceiverType.CAST:$7(this,new U7(this.i,a));break;default:this.Jb("Unknown receiver type: "+a.receiverType)}break;case chrome.cast.ReceiverAction.STOP:this.g&&this.g.i.label==a.label?this.g.stop():this.Jb("Stopping receiver w/o session: "+a.friendlyName)}else this.Jb("onReceiverAction_ called without receiver.")};
g.h.FI=function(a){if(this.da())return Promise.reject(Error("disposed"));var b=a.receiver;b.receiverType!=chrome.cast.ReceiverType.DIAL&&(this.Jb("Not DIAL receiver: "+b.friendlyName),b.receiverType=chrome.cast.ReceiverType.DIAL);var c=this.g?this.g.i:null;if(!c||c.label!=b.label)return this.Jb("Receiving DIAL launch request for non-clicked DIAL receiver: "+b.friendlyName),Promise.reject(Error("illegal DIAL launch"));if(c&&c.label==b.label&&c.receiverType!=chrome.cast.ReceiverType.DIAL){if(this.g.l)return Y7("Reselecting dial screen."),
this.N("yt-remote-cast2-session-change",this.g.l),Promise.resolve(new chrome.cast.DialLaunchResponse(!1));this.Jb('Changing CAST intent from "'+c.receiverType+'" to "dial" for '+b.friendlyName);$7(this,new V7(this.i,b,this.A))}b=this.g;b.D=a;return b.D.appState==chrome.cast.DialAppState.RUNNING?new Promise((0,g.y)(b.XD,b,(b.D.extraData||{}).screenId||null)):new Promise((0,g.y)(b.cq,b))};
g.h.Ty=function(a){if(!this.da()){Y7("New cast session ID: "+a.sessionId);var b=a.receiver;if(b.receiverType!=chrome.cast.ReceiverType.CUSTOM){if(!this.g)if(b.receiverType==chrome.cast.ReceiverType.CAST)Y7("Got resumed cast session before resumed mdx connection."),b.friendlyName=chrome.cast.unescape(b.friendlyName),$7(this,new U7(this.i,b),!0);else{this.Jb("Got non-cast session without previous mdx receiver event, or mdx resume.");return}var c=this.g.i,d=d6(this.i.Kd(),c.label);d&&X5(d,b.label)&&
c.receiverType!=chrome.cast.ReceiverType.CAST&&b.receiverType==chrome.cast.ReceiverType.CAST&&(Y7("onSessionEstablished_: manual to cast session change "+b.friendlyName),g.sf(this.g),this.g=new U7(this.i,b),this.g.subscribe("sessionScreen",(0,g.y)(this.Uy,this,this.g)),this.g.mi(null));this.g.hs(a)}}};
g.h.hN=function(){return this.g?this.g.fB():null};
g.h.PK=function(a){this.da()||(this.Jb("Failed to estabilish a session: "+g.Ng(a)),a.code!=chrome.cast.ErrorCode.CANCEL&&$7(this,null))};
g.h.tK=function(a){Y7("Receiver availability updated: "+a);if(!this.da()){var b=Z7(this);this.u=a==chrome.cast.ReceiverAvailability.AVAILABLE;Z7(this)!=b&&this.N("yt-remote-cast2-availability-change",Z7(this))}};
g.h.eB=function(){this.da()||(this.l=Sqa(this),Y7("Updating custom receivers: "+g.Ng(this.l)),chrome.cast.setCustomReceivers(this.l,g.Ia,(0,g.y)(function(){this.Jb("Failed to set custom receivers.")},this)),this.N("yt-remote-cast2-availability-change",Z7(this)))};
X7.prototype.setLaunchParams=X7.prototype.rM;X7.prototype.setConnectedScreenStatus=X7.prototype.qM;X7.prototype.stopSession=X7.prototype.iN;X7.prototype.getCastSession=X7.prototype.hN;X7.prototype.requestSession=X7.prototype.requestSession;X7.prototype.init=X7.prototype.init;X7.prototype.dispose=X7.prototype.dispose;var f8=[];k8.prototype.reset=function(a){this.listId="";this.index=-1;this.videoId="";l8(this);this.volume=-1;this.muted=!1;a&&(this.index=a.index,this.listId=a.listId,this.videoId=a.videoId,this.playerState=a.playerState,this.volume=a.volume,this.muted=a.muted,this.audioTrackId=a.audioTrackId,this.g=a.trackData,this.Ke=a.hasPrevious,this.hasNext=a.hasNext,this.C=a.playerTime,this.A=a.playerTimeAt,this.o=a.seekableStart,this.i=a.seekableEnd,this.D=a.duration,this.F=a.loadedTime,this.l=a.liveIngestionTime,this.u=
!isNaN(this.l))};
k8.prototype.isAdPlaying=function(){return 1081==this.playerState};
k8.prototype.getDuration=function(){return this.u?this.D+m8(this):this.D};
k8.prototype.clone=function(){return new k8(q8(this))};g.t(s8,g.P);g.h=s8.prototype;g.h.play=function(){1==this.g?(this.i?this.i.play(null,g.Ia,y8(this,"play")):x8(this,"play"),w8(this,1,o8(t8(this))),this.N("remotePlayerChange")):u8(this,this.play)};
g.h.pause=function(){1==this.g?(this.i?this.i.pause(null,g.Ia,y8(this,"pause")):x8(this,"pause"),w8(this,2,o8(t8(this))),this.N("remotePlayerChange")):u8(this,this.pause)};
g.h.seekTo=function(a){if(1==this.g){if(this.i){var b=t8(this),c=new chrome.cast.media.SeekRequest;c.currentTime=a;c.resumeState=1==b.playerState||3==b.playerState?chrome.cast.media.ResumeState.PLAYBACK_START:chrome.cast.media.ResumeState.PLAYBACK_PAUSE;this.i.seek(c,g.Ia,y8(this,"seekTo",{newTime:a}))}else x8(this,"seekTo",{newTime:a});w8(this,3,a);this.N("remotePlayerChange")}else u8(this,g.Ra(this.seekTo,a))};
g.h.stop=function(){if(1==this.g){this.i?this.i.stop(null,g.Ia,y8(this,"stopVideo")):x8(this,"stopVideo");var a=t8(this);a.index=-1;a.videoId="";l8(a);v8(this,a);this.N("remotePlayerChange")}else u8(this,this.stop)};
g.h.setVolume=function(a,b){if(1==this.g){var c=t8(this);if(this.l){if(c.volume!=a){var d=Math.round(a)/100;this.l.setReceiverVolumeLevel(d,(0,g.y)(function(){C7("CP","set receiver volume: "+d)},this),(0,g.y)(function(){this.Jb("failed to set receiver volume.")},this))}c.muted!=b&&this.l.setReceiverMuted(b,(0,g.y)(function(){C7("CP","set receiver muted: "+b)},this),(0,g.y)(function(){this.Jb("failed to set receiver muted.")},this))}else{var e={volume:a,
muted:b};-1!=c.volume&&(e.delta=a-c.volume);x8(this,"setVolume",e)}c.muted=b;c.volume=a;v8(this,c)}else u8(this,g.Ra(this.setVolume,a,b))};
g.h.fA=function(a,b){if(1==this.g){var c=t8(this),d={videoId:a};b&&(c.g={trackName:b.name,languageCode:b.languageCode,sourceLanguageCode:b.translationLanguage?b.translationLanguage.languageCode:"",languageName:b.languageName,kind:b.kind},d.style=g.Ng(b.style),g.fc(d,c.g));x8(this,"setSubtitlesTrack",d);v8(this,c)}else u8(this,g.Ra(this.fA,a,b))};
g.h.setAudioTrack=function(a,b){if(1==this.g){var c=b.getLanguageInfo().getId();x8(this,"setAudioTrack",{videoId:a,audioTrackId:c});var d=t8(this);d.audioTrackId=c;v8(this,d)}else u8(this,g.Ra(this.setAudioTrack,a,b))};
g.h.playVideo=function(a,b,c,d,e,f,k){var l=t8(this);c=c||0;var m={videoId:a,currentIndex:c};p8(l,a,c);g.Ea(b)&&(n8(l,b),m.currentTime=b);g.Ea(d)&&(m.listId=d);null!=e&&(m.playerParams=e);null!=f&&(m.clickTrackingParams=f);null!=k&&(m.locationInfo=g.Ng(k));x8(this,"setPlaylist",m);d||v8(this,l)};
g.h.wn=function(a,b){if(1==this.g){if(a&&b){var c=t8(this);p8(c,a,b);v8(this,c)}x8(this,"previous")}else u8(this,g.Ra(this.wn,a,b))};
g.h.nextVideo=function(a,b){if(1==this.g){if(a&&b){var c=t8(this);p8(c,a,b);v8(this,c)}x8(this,"next")}else u8(this,g.Ra(this.nextVideo,a,b))};
g.h.Xu=function(){1==this.g?x8(this,"dismissAutoplay"):u8(this,this.Xu)};
g.h.dispose=function(){if(3!=this.g){var a=this.g;this.g=3;this.N("proxyStateChange",a,this.g)}g.P.prototype.dispose.call(this)};
g.h.T=function(){era(this);this.o=null;this.u.clear();r8(this,null);g.P.prototype.T.call(this)};
g.h.Ys=function(a){if((a!=this.g||2==a)&&3!=this.g&&0!=a){var b=this.g;this.g=a;this.N("proxyStateChange",b,a);if(1==a)for(;!this.u.isEmpty();)b=a=this.u,0==b.g.length&&(b.g=b.i,b.g.reverse(),b.i=[]),a.g.pop().apply(this);else 3==a&&this.dispose()}};
g.h.mK=function(a,b){this.N(a,b)};
g.h.jI=function(a){if(!a)this.zk(null),r8(this,null);else if(this.l.receiver.volume){a=this.l.receiver.volume;var b=t8(this),c=Math.round(100*a.level||0);if(b.volume!=c||b.muted!=a.muted)C7("CP","Cast volume update: "+a.level+(a.muted?" muted":"")),b.volume=c,b.muted=!!a.muted,v8(this,b)}};
g.h.zk=function(a){C7("CP","Cast media: "+!!a);this.i&&this.i.removeUpdateListener(this.D);if(this.i=a)this.i.addUpdateListener(this.D),fra(this),this.N("remotePlayerChange")};
g.h.iI=function(a){a?(fra(this),this.N("remotePlayerChange")):this.zk(null)};
g.h.Hs=function(){x8(this,"sendDebugCommand",{debugCommand:"stats4nerds "})};
g.h.vI=function(){var a=bra();a&&r8(this,a)};
g.h.Jb=function(a){C7("CP",a)};g.t(z8,g.P);g.h=z8.prototype;
g.h.connect=function(a,b){if(b){var c=b.listId,d=b.videoId,e=b.playerParams,f=b.clickTrackingParams,k=b.index,l={videoId:d},m=b.currentTime,n=b.locationInfo;g.Ea(m)&&(l.currentTime=5>=m?0:m);e&&(l.playerParams=e);n&&(l.locationInfo=n);f&&(l.clickTrackingParams=f);c&&(l.listId=c);g.Ea(k)&&(l.currentIndex=k);c&&(this.Oa.listId=c);this.Oa.videoId=d;this.Oa.index=k||0;this.Oa.state=3;n8(this.Oa,m);this.o="UNSUPPORTED";A8("Connecting with setPlaylist and params: "+g.Ng(l));this.g.connect({method:"setPlaylist",
params:g.Ng(l)},a,j6())}else A8("Connecting without params"),this.g.connect({},a,j6());hra(this)};
g.h.dispose=function(){this.da()||(this.N("beforeDispose"),B8(this,3));g.P.prototype.dispose.call(this)};
g.h.T=function(){C8(this);E8(this);D8(this);g.Zp(this.C);this.C=NaN;g.Zp(this.D);this.D=NaN;this.l=null;g.ds(this.P);this.P.length=0;this.g.dispose();g.P.prototype.T.call(this);this.o=this.A=this.i=this.Oa=this.g=null};
g.h.kD=function(){this.Oh(2)};
g.h.nI=function(){A8("Channel opened");this.I&&(this.I=!1,D8(this),this.H=g.Xp((0,g.y)(function(){A8("Timing out waiting for a screen.");this.Oh(1)},this),15E3));
mqa(tqa(this.g),this.M)};
g.h.kI=function(){A8("Channel closed");isNaN(this.u)?m6(!0):m6();this.dispose()};
g.h.lI=function(a){m6();isNaN(this.Dj())?(A8("Channel error: "+a+" without reconnection"),this.dispose()):(this.I=!0,A8("Channel error: "+a+" with reconnection in "+this.Dj()+" ms"),B8(this,2))};
g.h.mI=function(a){a.params?A8("Received: action="+a.action+", params="+g.Ng(a.params)):A8("Received: action="+a.action+" {}");switch(a.action){case "loungeStatus":a=S5(a.params.devices);this.i=(0,g.C)(a,function(c){return new V5(c)});
a=!!g.Ya(this.i,function(c){return"LOUNGE_SCREEN"==c.type});
kra(this,a);break;case "loungeScreenDisconnected":g.eb(this.i,function(c){return"LOUNGE_SCREEN"==c.type});
kra(this,!1);break;case "remoteConnected":var b=new V5(S5(a.params.device));g.Ya(this.i,function(c){return b?c.id==b.id:!1})||bqa(this.i,b);
break;case "remoteDisconnected":b=new V5(S5(a.params.device));g.eb(this.i,function(c){return b?c.id==b.id:!1});
break;case "gracefulDisconnect":break;case "playlistModified":mra(this,a);break;case "nowPlaying":ora(this,a);break;case "onStateChange":nra(this,a);break;case "onAdStateChange":pra(this,a);break;case "onVolumeChanged":qra(this,a);break;case "onSubtitlesTrackChanged":lra(this,a);break;case "nowAutoplaying":rra(this,a);break;case "autoplayDismissed":this.N("autoplayDismissed");break;case "autoplayUpNext":this.A=a.params.videoId||null;this.N("autoplayUpNext",this.A);break;case "onAutoplayModeChanged":this.o=
a.params.autoplayMode;this.N("autoplayModeChange",this.o);"DISABLED"==this.o&&this.N("autoplayDismissed");break;case "onHasPreviousNextChanged":sra(this,a);break;case "requestAssistedSignIn":this.N("assistedSignInRequested",a.params.authCode);break;default:A8("Unrecognized action: "+a.action)}};
g.h.dM=function(){if(this.l){var a=this.l;this.l=null;this.Oa.videoId!=a&&F8(this,"getNowPlaying")}};
g.h.aD=function(){var a=3;this.da()||(a=0,isNaN(this.Dj())?w7(this.g)&&isNaN(this.u)&&(a=1):a=2);return a};
g.h.Oh=function(a){A8("Disconnecting with "+a);C8(this);this.N("beforeDisconnect",a);1==a&&m6();v7(this.g,a);this.dispose()};
g.h.ZC=function(){var a=this.Oa;this.l&&(a=this.Oa.clone(),p8(a,this.l,a.index));return q8(a)};
g.h.sM=function(a){var b=new k8(a);b.videoId&&b.videoId!=this.Oa.videoId&&(this.l=b.videoId,g.Zp(this.C),this.C=g.Xp((0,g.y)(this.dM,this),5E3));var c=[];this.Oa.listId==b.listId&&this.Oa.videoId==b.videoId&&this.Oa.index==b.index||c.push("remoteQueueChange");this.Oa.playerState==b.playerState&&this.Oa.volume==b.volume&&this.Oa.muted==b.muted&&o8(this.Oa)==o8(b)&&g.Ng(this.Oa.g)==g.Ng(b.g)||c.push("remotePlayerChange");this.Oa.reset(a);(0,g.A)(c,function(d){this.N(d)},this)};
g.h.Kv=function(){var a=this.g.A.id,b=g.Ya(this.i,function(c){return"REMOTE_CONTROL"==c.type&&c.id!=a});
return b?b.id:""};
g.h.Dj=function(){var a=this.g;return a.i.isActive()?a.i.i-(0,g.B)():NaN};
g.h.SC=function(){return this.o||"UNSUPPORTED"};
g.h.TC=function(){return this.A||""};
g.h.aN=function(){if(!isNaN(this.Dj())){var a=this.g.i;g.wo(a.g);a.start()}};
g.h.lM=function(a,b){F8(this,a,b);jra(this)};
z8.prototype.subscribe=z8.prototype.subscribe;z8.prototype.unsubscribeByKey=z8.prototype.Hf;z8.prototype.getProxyState=z8.prototype.aD;z8.prototype.disconnect=z8.prototype.Oh;z8.prototype.getPlayerContextData=z8.prototype.ZC;z8.prototype.setPlayerContextData=z8.prototype.sM;z8.prototype.getOtherConnectedRemoteId=z8.prototype.Kv;z8.prototype.getReconnectTimeout=z8.prototype.Dj;z8.prototype.getAutoplayMode=z8.prototype.SC;z8.prototype.getAutoplayVideoId=z8.prototype.TC;z8.prototype.reconnect=z8.prototype.aN;
z8.prototype.sendMessage=z8.prototype.lM;g.t(G8,G7);g.h=G8.prototype;g.h.Kd=function(a){return this.Hc.$_gs(a)};
g.h.contains=function(a){return!!this.Hc.$_c(a)};
g.h.get=function(a){return this.Hc.$_g(a)};
g.h.start=function(){this.Hc.$_st()};
g.h.add=function(a,b,c){this.Hc.$_a(a,b,c)};
g.h.remove=function(a,b,c){this.Hc.$_r(a,b,c)};
g.h.ao=function(a,b,c,d){this.Hc.$_un(a,b,c,d)};
g.h.T=function(){for(var a=0,b=this.i.length;a<b;++a)this.Hc.$_ubk(this.i[a]);this.i.length=0;this.Hc=null;G7.prototype.T.call(this)};
g.h.eN=function(){this.N("screenChange")};
g.h.QJ=function(){this.N("onlineScreenChange")};
P7.prototype.$_st=P7.prototype.start;P7.prototype.$_gspc=P7.prototype.fN;P7.prototype.$_gsppc=P7.prototype.dB;P7.prototype.$_c=P7.prototype.contains;P7.prototype.$_g=P7.prototype.get;P7.prototype.$_a=P7.prototype.add;P7.prototype.$_un=P7.prototype.ao;P7.prototype.$_r=P7.prototype.remove;P7.prototype.$_gs=P7.prototype.Kd;P7.prototype.$_gos=P7.prototype.cB;P7.prototype.$_s=P7.prototype.subscribe;P7.prototype.$_ubk=P7.prototype.Hf;var Z8=null,Y8=!1,H8=null,I8=null,X8=null,M8=[];g.t($8,g.G);g.h=$8.prototype;
g.h.T=function(){g.G.prototype.T.call(this);this.o.stop();this.A.stop();this.I.stop();this.M();this.g.unsubscribe("proxyStateChange",this.Qy,this);this.g.unsubscribe("remotePlayerChange",this.Bk,this);this.g.unsubscribe("remoteQueueChange",this.mn,this);this.g.unsubscribe("autoplayUpNext",this.ty,this);this.g.unsubscribe("previousNextChange",this.Ny,this);this.g.unsubscribe("nowAutoplaying",this.Jy,this);this.g.unsubscribe("autoplayDismissed",this.ry,this);this.g=this.u=null};
g.h.ox=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];if(2!=this.g.g)if(c9(this)){if(!t8(this.g).isAdPlaying()||"control_seek"!=a)switch(a){case "control_toggle_play_pause":1==t8(this.g).playerState?this.g.pause():this.g.play();break;case "control_play":this.g.play();break;case "control_pause":this.g.pause();break;case "control_seek":this.H.Kj(c[0],c[1]);break;case "control_subtitles_set_track":d9(this,c[0]);break;case "control_set_audio_track":c=c[0],c9(this)&&this.g.setAudioTrack(this.i.getVideoData(1).videoId,
c)}}else switch(a){case "control_toggle_play_pause":case "control_play":case "control_pause":c=this.i.getCurrentTime();e9(this,0==c?void 0:c);break;case "control_seek":e9(this,c[0]);break;case "control_subtitles_set_track":d9(this,c[0]);break;case "control_set_audio_track":c=c[0],c9(this)&&this.g.setAudioTrack(this.i.getVideoData(1).videoId,c)}};
g.h.hI=function(a){this.I.gD(a)};
g.h.MM=function(a){this.ox("control_subtitles_set_track",g.Yb(a)?null:a)};
g.h.rA=function(){var a=this.i.getOption("captions","track");g.Yb(a)||d9(this,a)};
g.h.Fy=function(a){if(c9(this)){this.g.unsubscribe("remotePlayerChange",this.Bk,this);var b=Math.round(a.volume);a=!!a.muted;var c=t8(this.g);if(b!=c.volume||a!=c.muted)this.g.setVolume(b,a),this.P.start();this.g.subscribe("remotePlayerChange",this.Bk,this)}};
g.h.jJ=function(){g.Yb(this.C)||Era(this,this.C);this.D=!1};
g.h.Qy=function(a,b){this.A.stop();2==b&&this.qA()};
g.h.Bk=function(){if(c9(this)){this.o.stop();var a=t8(this.g);switch(a.playerState){case 1080:case 1081:case 1084:case 1085:this.u.Dm=1;break;case 1082:case 1083:this.u.Dm=0;break;default:this.u.Dm=-1}switch(a.playerState){case 1081:case 1:b9(this,new g.DC(8));this.pA();break;case 1085:case 3:b9(this,new g.DC(9));break;case 1083:case 0:b9(this,new g.DC(2));this.H.stop();a9(this,this.i.getVideoData().lengthSeconds);break;case 1084:b9(this,new g.DC(4));break;case 2:b9(this,new g.DC(4));a9(this,o8(a));
break;case -1:b9(this,new g.DC(64));break;case -1E3:b9(this,new g.DC(128,{errorCode:"mdx.remoteerror",message:"This video is not available for remote playback."}))}a=t8(this.g).g;var b=this.C;(a||b?a&&b&&a.trackName==b.trackName&&a.languageCode==b.languageCode&&a.languageName==b.languageName&&a.kind==b.kind:1)||(this.C=a,Era(this,a));a=t8(this.g);-1==a.volume||Math.round(this.i.getVolume())==a.volume&&this.i.isMuted()==a.muted||this.P.isActive()||this.PA()}else Dra(this)};
g.h.Ny=function(){this.i.N("mdxpreviousnextchange")};
g.h.mn=function(){c9(this)||Dra(this)};
g.h.nC=function(){this.g.Xu()};
g.h.ty=function(a){a&&(a=g.Uq("/watch_queue_ajax",{method:"GET",Ec:{action_get_watch_queue_item:1,video_id:a},onSuccess:(0,g.y)(this.rL,this)}))&&(this.M=(0,g.y)(a.abort,a))};
g.h.rL=function(a,b){var c=new g.oB(g.X(this.i),{videoId:b.videoId,title:b.title,author:b.author,murlmq_webp:b.url});this.suggestion=c;this.i.N("mdxautoplayupnext",c)};
g.h.Jy=function(a){isNaN(a)||this.i.N("mdxnowautoplaying",a)};
g.h.ry=function(){this.i.N("mdxautoplaycanceled")};
g.h.HF=function(a,b){-1==t8(this.g).playerState?e9(this,a):b&&this.g.seekTo(a)};
g.h.PA=function(){if(c9(this)){var a=t8(this.g);this.l.La(this.O);a.muted?this.i.mute():this.i.unMute();this.i.setVolume(a.volume);this.O=this.l.K(this.i,"onVolumeChange",this.Fy)}};
g.h.pA=function(){this.o.stop();if(!this.g.da()){var a=t8(this.g);1==a.playerState&&b9(this,new g.DC(8));a9(this,o8(a));this.o.start()}};
g.h.qA=function(){this.A.stop();this.o.stop();var a=this.g.o.getReconnectTimeout();2==this.g.g&&!isNaN(a)&&this.A.start()};g.t(f9,g.W);f9.prototype.o=function(){U5("mdx-privacy-popup-cancel");this.l.hide()};
f9.prototype.A=function(){U5("mdx-privacy-popup-confirm");this.l.hide()};g.t(g9,g.W);g9.prototype.u=function(a){Gra(this,a.state)};g.t(h9,g.ZT);h9.prototype.I=function(){var a=this.l.getOption("remote","receivers");a&&1<a.length&&!this.l.getOption("remote","quickCast")?(this.F=g.ub(a,this.A,this),g.$T(this,(0,g.C)(a,this.A)),a=this.l.getOption("remote","currentReceiver"),this.se(this.A(a)),this.enable(!0)):this.enable(!1)};
h9.prototype.A=function(a){return a.key};
h9.prototype.re=function(a){return"cast-selector-receiver"==a?"Cast...":this.F[a].name};
h9.prototype.Jc=function(a){g.ZT.prototype.Jc.call(this,a);this.l.setOption("remote","currentReceiver",this.F[a]);this.o.gb()};g.t(i9,g.RK);g.h=i9.prototype;
g.h.create=function(){xra(g.$y(g.X(this.player)));this.l.push(g.dq("yt-remote-before-disconnect",this.eI,this));this.l.push(g.dq("yt-remote-connection-change",this.uK,this));this.l.push(g.dq("yt-remote-receiver-availability-change",this.Oy,this));this.l.push(g.dq("yt-remote-auto-connect",this.sK,this));this.l.push(g.dq("yt-remote-receiver-resumed",this.rK,this));this.l.push(g.dq("mdx-privacy-popup-confirm",this.UL,this));this.l.push(g.dq("mdx-privacy-popup-cancel",this.TL,this));this.Oy()};
g.h.load=function(){this.player.cancelPlayback();g.RK.prototype.load.call(this);this.u=new $8(this,this.player,this.g);var a=(a=Cra())?a.currentTime:0;var b=W8()?new s8(R8(),void 0):null;0==a&&b&&(a=o8(t8(b)));0!=a&&this.td(a);Fra(this,this.hk,this.hk);g.YX(this.player.app,6)};
g.h.unload=function(){this.player.N("mdxautoplaycanceled");this.o=this.i;g.tf(this.u,this.g);this.g=this.u=null;g.RK.prototype.unload.call(this);g.YX(this.player.app,5)};
g.h.T=function(){g.eq(this.l);g.RK.prototype.T.call(this)};
g.h.We=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];this.loaded&&this.u.ox.apply(this.u,[a].concat(g.fa(c)))};
g.h.getAdState=function(){return this.Dm};
g.h.cD=function(){return this.loaded?this.u.suggestion:null};
g.h.Ke=function(){return this.g?t8(this.g).Ke:!1};
g.h.hasNext=function(){return this.g?t8(this.g).hasNext:!1};
g.h.td=function(a,b){this.H=a||0;this.player.N("progresssync",a,b)};
g.h.getCurrentTime=function(){return this.H};
g.h.getProgressState=function(){var a=t8(this.g),b=this.player.getVideoData();return{allowSeeking:g.Q(g.X(this.player).experiments,"web_player_mdx_allow_seeking_change_killswitch")?this.player.ec():!a.isAdPlaying()&&this.player.ec(),clipEnd:b.clipEnd,clipStart:b.clipStart,current:this.getCurrentTime(),displayedStart:-1,duration:a.getDuration(),ingestionTime:a.u?a.l+m8(a):a.l,isAtLiveHead:1>=(a.u?a.i+m8(a):a.i)-this.getCurrentTime(),loaded:a.F,seekableEnd:a.u?a.i+m8(a):a.i,seekableStart:0<a.o?a.o+
m8(a):a.o}};
g.h.nextVideo=function(){this.g&&this.g.nextVideo()};
g.h.wn=function(){this.g&&this.g.wn()};
g.h.eI=function(a){1==a&&(this.C=this.g?t8(this.g):null)};
g.h.uK=function(){var a=W8()?new s8(R8(),void 0):null;if(a){var b=this.o;this.loaded&&this.unload();this.g=a;this.C=null;b.key!=this.i.key&&(this.o=b,this.load())}else g.sf(this.g),this.g=null,this.loaded&&(this.unload(),(a=this.C)&&a.videoId==this.player.getVideoData().videoId&&this.player.cueVideoById(a.videoId,o8(a)));this.player.N("videodatachange","newdata",this.player.getVideoData(),3)};
g.h.Oy=function(){this.A=[this.i].concat(zra());var a=S8()||this.i;j9(this,a);this.player.la("onMdxReceiversChange")};
g.h.sK=function(){var a=S8();j9(this,a)};
g.h.rK=function(){this.o=S8()};
g.h.UL=function(){this.D=!0;Y8=!1;Z8&&U8(Z8,1);Z8=null};
g.h.TL=function(){this.D=!1;j9(this,this.i);this.player.playVideo()};
g.h.Zb=function(a,b){switch(a){case "casting":return this.loaded;case "receivers":return this.A;case "currentReceiver":return b&&("cast-selector-receiver"==b.key?i8():j9(this,b)),this.loaded?this.o:this.i;case "quickCast":return 2==this.A.length&&"cast-selector-receiver"==this.A[1].key?(b&&i8(),!0):!1}};
g.h.Hs=function(){this.g.Hs()};
g.h.Ib=function(){return!1};
g.h.getOptions=function(){return["casting","receivers","currentReceiver","quickCast"]};g.oV.remote=i9;})(_yt_player);
